### ISSUE TITLE
Documentar lógica de nomes de arquivo do IMSLP

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#1]
## Instruções

Os nomes dos arquivos `pdf` do [IMSLP](http://imslp.org) muitas vezes têm apenas números, como em `IMSLP00794-BWV0829`, e em outras vezes têm informações sobre autor e obra, como em `IMSLP00012-Beethoven__L.v._-_Piano_Sonata_12`. Mesmo no caso de Bach, que tem a numeração de BWV, não parece haver padrão. Em algumas situações há o nome da obra: `IMSLP06546-Bach_-_BGA_-_English_Suites_Band_13`. No caso das 12 fantasias de Telemann há uma informação adicional antes do título: `IMSLP32138-PMLP54405-Teleman_12_Fantasias_for_Traversiere`.

A tarefa consiste em encontrar informações sobre a lógica de criação desses nomes de arquivo e documenta-las. É importante inserir na documentação todas as fontes de informação utilizadas para consultas posteriores.

Com este trabalho será possível definir diretrizes para o programa de análise das músicas.

Um bom ponto de partida é o [sitemap do IMSLP](http://imslp.org/wiki/IMSLP:Sitemap).

**Comment by daniloabrahao** [comment]
@msampaio , peças importantes para flauta solo como a Partita de J.S.Bach tem muitas transcrições para outros instrumentos. devo baixá-las também?

**Comment by msampaio** [comment]
@daniloabrahao, por enquanto acho melhor não baixar as partituras. Aguarde a palestra de @robattolucas sobre edição musical no dia 08/08. Ele deverá dar essas diretrizes sobre o trabalho. Por enquanto observe o [manual](http://genosmus.com/pesquisa/flauta-solo/manual/) para colocar as partituras no local correto.

**Comment by msampaio** [comment]
@daniloabrahao, eu desconfio que o IMSLP tem um código numérico geral para a partitura mais um sufixo livre. Usando esse raciocínio podemos pensar que o arquivo `IMSLP00794-BWV0829` é a partitura `00794` da coleção. Uma forma de verificar se meu pensamento está correto é observar os nomes de arquivo de partituras que têm várias edições diferentes.

**Comment by daniloabrahao** [comment]
Eu comecei a baixar as partituras para poder observar isso, @msampaio. Porque ainda não encontrei informação sobre os nomes dados aos arquivos pelo IMSLP. Vou verificar se seu pensamento está correto.

**Comment by msampaio** [comment]
Beleza. Entāo siga em frente ;-)

**Comment by daniloabrahao** [comment]
Como eu farei para documentar isso, @msampaio? Posso fazê-lo aqui nos comentários ou devo redigi-lo? Se tiver que redigir um documento, existe um modelo para isso?

**Comment by msampaio** [comment]
@daniloabrahao, pode documentar as informações aqui nos comentários. Em breve irei organizar nossos modelos de documentos.

**Comment by daniloabrahao** [comment]
Ok!

**Comment by msampaio** [comment]
@daniloabrahao, já criei os templates para redigir anotações sobre a pesquisa. Veja no [manual](http://genosmus.com/pesquisa/flauta-solo/manual/#Uso_de_templates).

**Comment by daniloabrahao** [comment]
@msampaio, conforme o que vc disse, o número que vem depois de "IMSLP", no nome do arquivo é o index number. Como por exemplo, no arquivo '-IMSLP01479-CPEBach_-_Sonata_solo_flute_a_min-fl-a4.', '-01479-' é o index number. Desconfio que o restante seja aleatório.

**Comment by msampaio** [comment]
@daniloabrahao, veja se há alguma informação no guia do IMSLP. Pelo que vi nos arquivos que você baixou, apenas esse index number tem importância. Por exemplo, na Partita de Bach (BWV 1013), cada movimento em cada edição tem um index number diferente. Uma das edições tem os números `05673`, `05674`, `05675` e `05676` para os movimentos e uma outra edição tem os números `171888`, `171889`, `171890` e `171891`. No entanto há edições em que todos os movimentos aparecem com um único index number, como `99157` e `216096`.
Documente essas notas conforme o [manual](http://genosmus.com/pesquisa/flauta-solo/manual/#Uso_de_templates).

**Comment by msampaio** [comment]
@daniloabrahao, consulte esses links. Observe que há informações novas e antigas.

http://imslp.org/wiki/User:Feldmahler/New_Indexing_and_Imaging_System
http://imslp.org/wiki/IMSLP:Special:IMSLPTagFinder/Manual

**Comment by daniloabrahao** [comment]
@msampaio, eu ontem li as informações desse link "New Indexing and imaging System" e entendi que o nome dos arquivos têm esta forma:

[IMSLP index number+Último nome do compositor+Descrição do arquivo (sistema de numeração específico do compositor, nome do movimento e/ou instrumentação)]

Os códigos adicionais, como "PMLP13663" ou "WIMA.411e", podem ser o Image ID Number. Mas não tenho certeza. E creio que a lógica do index number segue a ordem dos uploads. Por exemplo, partituras que foram enviadas de uma vez só possuem um index number parecido.
Não entendi ainda o que é esse TagFinder nem o Image ID Number.

**Comment by msampaio** [comment]
@daniloabrahao, bom trabalho. Acredito que teremos mais informações quando eu concluir a tarefa #6. Estou fechando esta tarefa, mas se obtiver informações sobre TagFinder e Image ID Number, basta comentar aqui.

**Comment by daniloabrahao** [comment]
Ok!
