### ISSUE TITLE
Escrever resumo do evento VIII Seminário de Metodologia para Projetos de Extensão

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#10]
Assistir o "VIII Seminário de Metodologia para Projetos de Extensão" e escrever um resumo sobre os pontos principais tratados. Ver modelos de documentos no manual da pesquisa.

Proposto pelo Fórum de Pró-Reitores de Extensão das universidades públicas do Brasil, o evento, que ocorre de 18 a 20 de agosto de 2013 no Teatro da Universidade do Estado da Bahia (UNEB), busca discutir com a academia e a sociedade as metodologias aplicadas nos projetos de extensão universitária.

A conferência de abertura, intitulada Metodologias Participativas na Construção do Conhecimento, será proferida pelo professor Silvio Gamboa (UNICAMP) às 19h de 18 de agosto e mediada pela professora e Vice-Reitora da Universidade do Estado da Bahia (UNEB) Adriana Lima. Além da UNEB, estão envolvidas na organização do Seminário a Universidade Federal da Bahia (UFBA), a Universidade Estadual de Feira de Santana (UEFS), a Universidade Estadual do Sudoeste da Bahia (UESB), a Universidade Estadual de Santa Cruz (UESC) e a Universidade Federal do Recôncavo da Bahia (UFRB).

**Comment by SimeiFerreira** [comment]
@msampaio, já está na pasta "produção" do copy o resumo das minhas anotações realizadas no "VIII SEMPE". Peço que dê uma conferida para ver se está tudo ok.

**Comment by msampaio** [comment]
Ótimo, @SimeiFerreira.
