### ISSUE TITLE
Delegar as tarefas de transcrição do IMSLP111786 L'art de preluder

### ISSUE THREAD

**Issue by ZeRodriguez** [msampaio/flauta-solo#105]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em delegar as transcrições das obras indicadas para cada um dos colaboradores da pesquisa criando novos **_issues**_ aqui no GitHub.
Para realizar esta tarefa seguir estas recomendações:
1. O colaborador já deverá ter cumprido suas tarefas anteriores. Não delegar tarefa a quem tem trabalho atrasado.
2. Priorizar os colaboradores que têm tarefas de transcrição em seus planos de trabalho.
3. Inserir na descrição da tarefa o código da fonte, código interno do pdf definido por @daniloabrahao, e o código da transcrição que deverá ser usado para salvar na pasta do Copy
4. Inserir o cabeçalho padrão de instruções gerais e específicas (copie o desta tarefa)
5. Definir como milestone a data da próxima reunião
6. Usar o label `Edição e segmentação`.

**Comment by ZeRodriguez** [comment]
@daniloabrahao, a medida que for identificando as peças a serem transcritas, por favor informe aqui nessa tarefa para que eu possa delegá-las. Abraço! =D

**Comment by ZeRodriguez** [comment]
@msampaio, também preciso que me informe para quem eu devo delegar tais tarefas. =D

**Comment by daniloabrahao** [comment]
Já identifiquei as obras. O que falta é decidir se vamos considerar os exemplos de Hotteterre como obras. De qualquer forma, as obras mais importantes já foram identificadas.

**Comment by msampaio** [comment]
Delegue para todos que estiverem ociosos exceto sara e menahem
Em 19/10/2013 12:10, "ZeRodriguez" notifications@github.com escreveu:

**Comment by msampaio** [comment]
@ZeRodriguez, de acordo com os planos de trabalho, a principal tarefa de @luanpiano e @DaianaMaciel é fazer transcrições. Como esses trechos são bem curtos, a partir da próxima semana pode colocar a média para eles de 10 a 15 por semana e de 5 a 10 para os demais. Coloque um número menor para quem já tem tarefas. Por hora deixe @menahemhein e @SaraFadigas sem transcrições, pois eles estão focados em outras tarefas (estudar PD e estatística).

**Comment by ZeRodriguez** [comment]
@msampaio , tarefa concluída! O que faltava do Hotteterre, obras 124 à 136 foram delegados à Luã e Daiana nas tarefas #130 e #131 .
