### ISSUE TITLE
Filtrar obras para flauta solo no IMSLP

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#107]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em filtrar as obras para flauta solo nesta [lista](http://imslp.org/index.php?title=Category:For_flute&intersect=For_1_player&transclude=Template:Catintro). Embora esta lista esteja filtrada "For flute && For 1 player", é bom conferir se todas são obras para flauta solo. Esta tarefa é pré-requisito para a tarefa #96.
A lista resultante deverá ser colocada no arquivo IMSLP-FlautaSolo.txt, na pasta Copy/Produção. O arquivo deverá ter um formato como esse:

```
1. À Part for Solo Flute (Harrington, Jeffrey Michael)
2. Alexander's New Scrap Book (Various)
3. Allegretto in F major (Baclay, George)
```

**Comment by MarinaMonroy** [comment]
@msampaio, recapitulando, vou filtrar as obras dessa pasta e acrescentar na lista já existente, confere?
A dúvida que me surge é: o filtro é apenas flauta solo, ou tem restrição de datas também nessa etapa?

**Comment by msampaio** [comment]
Sim, @MarinaMonroy. Você vai filtrar as obras da pasta e acrescentar na lista.
O período é aproximadamente de 1710 a 1810. Caso encontre obras próximas a esse período, mas fora dele, pergunte por aqui.

**Comment by MarinaMonroy** [comment]
@msampaio,
Outra dúvida quanto ao filtro: devo restringir ao que foi composto exclusivamente se pensando em ser para flauta ou podem ser peças em que tanto faz ser para flauta ou violino, por exemplo?

**Comment by msampaio** [comment]
@MarinaMonroy, você deve se restringir ao que está escrito para flauta, ainda que sejam transcrições de obras para  outros instrumentos, como violino. (Estou correto, @robattolucas?)

**Comment by robattolucas** [comment]
Sim, vamos trabalhar com originais. Porém, alguns originais são destinados
para flauta, ou oboé, ou violino…

Vamos seguir a indicação da partitura. Se mencionar flauta, é conosco.

**Comment by MarinaMonroy** [comment]
![image](https://f.cloud.github.com/assets/5719052/1408480/9a108c2e-3d82-11e3-83c4-5b610dd9ce91.png)

No caso de obras como essa, preciso abrir o arquivo, ou já previamente posso excluir da lista?
@robattolucas @msampaio

**Comment by MarinaMonroy** [comment]
@msampaio, conforme conversamos, por questões de imprecisão do imslp, vou gerar três listas a partir desse filtro inicial For flute && foi 1 player: uma com as obras que certamente não nos interessam, uma com as que obviamente nos interessam e uma terceira com obras que necessitam uma análise.

**Comment by MarinaMonroy** [comment]
@robattolucas, "Cadenzas to Mozart Flute Concertos (Tillmetz, Rudolf)" são excluídas no nosso filtro por serem parte de concerto? Ou consideraria por ser parte para flauta solo?

**Comment by MarinaMonroy** [comment]
@msampaio @robattolucas 
Berbiguier, Tranquille
Jensen, Niels Peter
Mostraram-se compositores especialmente difíceis de classificar obras devido a suas datas de nascimento. Consideraremos eles no trabalho ou não?
Uma das obras tem compositor anônimo. Retirei no filtro por isso. Fiz certo?
Ainda espero a resposta da questão das cadências.

A tarefa está concluída e agora surge a necessidade de olhar com mais calma as obras que sinalizei.

**Comment by robattolucas** [comment]
Sobre o Berbiguier, consegui o artigo do Grove, que vai abaixo, e também há
o verbete no De Lorenzo (que cita o Fetis). Sobre o Jensen ainda não não
consegui nada.

Marina, além do New Grove online (basta cadastrar no VPN da UFBA, se vc já
não o fez), uma grande fonte é o dicionário biográfico de Fetis de 1866
(que está no próprio IMSLP -
http://imslp.org/wiki/Biographie_universelle_des_musiciens_(Fétis,_François-Joseph)e
no Googlebooks (online). Lá estão milhares de músicos hoje
desconhecidos.
Já que vc está com esta tarefa, "biográfica" consultar o Fetis pode ser
útil, apesar das informações de lá não serem tão "rigorosamente
cientificas" quanto as do Grove (por exemplo). Porém, em muitos casos o
Fetis vai ser a única fonte.

Outra boa fonte - que poderiamos escanear - o "My Complete History of the
Flute" de Leonardo de Lorenzo. 'E um livro meio desorganizado, mas com
muita informação interessante.

**Comment by msampaio** [comment]
@robattolucas, recomendo salvarmos em nosso repositório todas as referências que usarmos.
@ZeRodriguez, você pode ajudar lucas e marina com isso? Pode delegar o preenchimento do mendeley para @menahemhein.

**Comment by msampaio** [comment]
@MarinaMonroy, bom trabalho. Irei abrir tarefas específicas para você processar as obras que sinalizou.
