### ISSUE TITLE
Documentar questões editoriais no manual da pesquisa

### ISSUE THREAD

**Issue by robattolucas** [msampaio/flauta-solo#11]
Documentar o texto abaixo no manual da pesquisa.

QUESTÕES EDITORIAIS NA PESQUISA FLAUTA SOLO

1)  Método a ser utilizado: transcrição diplomática de fonte única
2)  Critério para escolha de fontes:
2.1. Adotaremos as obras constantes no IMSLP, mas não necessariamente as fontes que lá estão
2.2. Prioridade para fontes editadas modernas (com aparato crítico)
3)  Em obras compostas por vários movimentos, cada movimento será considerado enquanto unidade, e assim será respectivamente catalogado
4)    Ainda serão decididos os critérios para catalogação (definição dos tags do banco de dados)
5)  No caso de obras pedagógicas, ainda serão decididos critérios editoriais para o recolhimento de unidades

**Comment by msampaio** [comment]
@robattolucas, imagino que você queira documentar essas questões editoriais da pesquisa. Você quer que um aluno coloque esses itens no manual da pesquisa? Basta selecionar no local indicado na figura abaixo.

![screen shot 2013-08-10 at 19 11 16](https://f.cloud.github.com/assets/1006488/943316/d718cf28-0209-11e3-94ec-f6129732842f.png)

**Comment by SimeiFerreira** [comment]
@msampaio, como não encontrei ferramentas de edição de texto, fui buscar informação para incluir as questões editoriais no manual diretamente no código html da página. Felizmente consegui, mas no menu que fica no topo da pasta não aparece a lista, somente o título "questões editoriais da pesquisa"...

http://genosmus.com/pesquisa/flauta-solo/manual/

 Como resolver isso?

**Comment by msampaio** [comment]
@SimeiFerreira, eu não entendi qual problema você teve. Para mim a tarefa já está concluída. Apenas mudei o local do item que você inseriu.
Farei um tutorial de edição da página do manual da pesquisa.

**Comment by SimeiFerreira** [comment]
@msampaio, apenas tive uma dificuldade com a plataforma, mas já peguei mais ou menos o macete porque já trabalhei um pouco com html. A dúvida remanescente é o porque de não aparecerem os itens da lista do item do "Definições editoriais" como aparecem nos outros itens marcados em vermelho:
![blog](https://f.cloud.github.com/assets/3719195/982719/feb539cc-0817-11e3-83c1-fe77591b47c1.jpg)

**Comment by SimeiFerreira** [comment]
@robattolucas, tarefa concluida. Peço que confira no blog se está tudo de acordo com o solicitado antes de fechar a tarefa.

**Comment by msampaio** [comment]
@SimeiFerreira, apenas os textos marcados como títulos (h1, h2, h3, etc) são incluídos no índice.

**Comment by msampaio** [comment]
Tudo ok.
