### ISSUE TITLE
Fazer leituras iniciais

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#111]
@azevedospider, esta tarefa consiste nas leituras iniciais necessárias ao projeto. Os itens estão disponíveis na pasta Flauta Solo/Bibliografia, no Copy. Ao concluí-la, por favor informe por aqui via comentário.
1. Sampaio, Marcos da Silva. 2012. “A Teoria de Relações de Contornos Musicais: Inconsistências, Soluções e Ferramentas”. Universidade Federal da Bahia.
2. Sampaio, Marcos, Guilherme Bertissolo, Lucas Robatto, José Martinez Neto, and Alisson da Silva. 2013. “Estudo Interdisciplinar de Obras Para Flauta Solo.” In SBCM 2013 - Artigos Técnicos/Posters (). Brasilia, DF.
3. Volk, Anja, and Aline Honingh. 2012. “Mathematical and Computational Approaches to Music: Challenges in an Interdisciplinary Enterprise.” Journal of Mathematics and Music 6 (2) (July): 73–81.
4. Volk, Anja, Frans Wiering, and Peter Van Kranenburg. 2011. “Unfolding the Potential of Computational Musicology.” Proceedings of The13th International Conference on Informatics and Semiotics in Organisations (ICISO): 137–144.

**Comment by ghost** [comment]
certo, já terminei de me organizar para o semestre e também já o artigo de
musicologia computacional aplicado aos corais de Bach, vou iniciar o estudo
dessas acima hoje..

Em 25 de outubro de 2013 08:51, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> @azevedospider https://github.com/azevedospider, esta tarefa consiste
> nas leituras iniciais necessárias ao projeto. Os itens estão disponíveis na
> pasta Flauta Solo/Bibliografia, no Copy. Ao concluí-la, por favor informe
> por aqui via comentário.
> 
>    1.
> 
>    Sampaio, Marcos da Silva. 2012. “A Teoria de Relações de Contornos
>    Musicais: Inconsistências, Soluções e Ferramentas”. Universidade Federal da
>    Bahia.
>    2.
> 
>    Sampaio, Marcos, Guilherme Bertissolo, Lucas Robatto, José Martinez
>    Neto, and Alisson da Silva. 2013. “Estudo Interdisciplinar de Obras Para
>    Flauta Solo.” In SBCM 2013 - Artigos Técnicos/Posters (). Brasilia, DF.
>    3.
> 
>    Volk, Anja, and Aline Honingh. 2012. “Mathematical and Computational
>    Approaches to Music: Challenges in an Interdisciplinary Enterprise.”
>    Journal of Mathematics and Music 6 (2) (July): 73–81.
>    4.
> 
>    Volk, Anja, Frans Wiering, and Peter Van Kranenburg. 2011. “Unfolding
>    the Potential of Computational Musicology.” Proceedings of The13th
>    International Conference on Informatics and Semiotics in Organisations
>    (ICISO): 137–144.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/111
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
Ótimo. Avise caso precise de alguma ajuda.

**Comment by ghost** [comment]
Oi professor Marcos, tenho quanto aos algoritmos, são esses que estão
compartilhados no copy?

2013/10/25 Marcos da Silva Sampaio notifications@github.com

> Ótimo. Avise caso precise de alguma ajuda.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/111#issuecomment-27119506
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
Não entendi a sua pergunta, @azevedospider. Você quer saber onde os algoritmos estão disponíveis?

**Comment by ghost** [comment]
Quero saber se os algoritmos são estes que estão no copy?

Em 30 de outubro de 2013 09:19, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> Não entendi a sua pergunta, @azevedospiderhttps://github.com/azevedospider.
> Você quer saber onde os algoritmos estão disponíveis?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/111#issuecomment-27384195
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
Os algoritmos de contornos não estão no Copy. Você pode encontrá-los no [MusiContour](http://genosmus.com/MusiContour/).

**Comment by ghost** [comment]
certo, quanto as 2 primeiras referências eu li e fiz um pequeno resumo para
meu estudo inicial, quero saber quais e quando serão as atividades de
elaboração/práticas?

Em 4 de novembro de 2013 11:23, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> Os algoritmos de contornos não estão no Copy. Você pode encontrá-los no
> MusiContour http://genosmus.com/MusiContour/.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/111#issuecomment-27688004
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
Bom trabalho, @azevedospider. Recomendo guardar seu resumo na nossa pasta Copy/Produção.
Após a sua conclusão das leituras irei atribuir as tarefas práticas, de modelagem do sistema de análise.

**Comment by ghost** [comment]
Certo.

Em 4 de novembro de 2013 17:27, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> Bom trabalho, @azevedospider https://github.com/azevedospider.
> Recomendo guardar seu resumo na nossa pasta Copy/Produção.
> Após a sua conclusão das leituras irei atribuir as tarefas práticas, de
> modelagem do sistema de análise.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/111#issuecomment-27714640
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by ghost** [comment]
Oi professor, foi um pouco demorado mas terminei as leituras iniciais. Foi
um pouco demorado porque ainda estou cursando algumas disciplinas do curso.
Mas estou no aguardo de próximas atividades inclusive amanhã vou olhar os
códigos do MusiContour e tentar tirar algumas conclusões sobre o código.

Em 4 de novembro de 2013 22:34, Danilo Azevedo
azevedo.spider@gmail.comescreveu:

> Certo.
> 
> Em 4 de novembro de 2013 17:27, Marcos da Silva Sampaio <
> notifications@github.com> escreveu:
> 
> Bom trabalho, @azevedospider https://github.com/azevedospider.
> 
> > Recomendo guardar seu resumo na nossa pasta Copy/Produção.
> > Após a sua conclusão das leituras irei atribuir as tarefas práticas, de
> > modelagem do sistema de análise.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/111#issuecomment-27714640
> > .
> 
> ## 
> 
> Danilo Azevedo Santos
> Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
> Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
> TEL. (71) 33863619/ 82869358 /92802927
> E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
> Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
Bom trabalho, @azevedospider. Estou fechando esta tarefa.
