### ISSUE TITLE
Inserir Crawford et al 2009 no Mendeley

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#113]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Inserir a referência abaixo no Mendeley

Tim Crawford and Laura Gibson (ed.). Modern Methods for Musicology:
prospect, proposal and realities.  Burlington: Ashgate, 2009.

**Comment by menahemhein** [comment]
Feito ! Professor fiquei em dúvida da cidade...quando fui pesquisar tinha algumas fontes que diziam uma cidade diferente.

**Comment by msampaio** [comment]
Coloque Burlington.

**Comment by msampaio** [comment]
@menahemhein, qual o estado da tarefa?

**Comment by menahemhein** [comment]
Coloquei Burlington no mesmo dia ! não esclareci direito isso ! Tá fechada !
