### ISSUE TITLE
Verificar obras do IMSLP sinalizadas em IMSLP-FlautaSolo

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#117]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em verificar se as obras sinalizadas no arquivo IMSLP-FlautaSolo estão no escopo da pesquisa.
Esta tarefa é uma continuidade da tarefa #107.

**Comment by msampaio** [comment]
@MarinaMonroy, qual o estado desta tarefa?

**Comment by MarinaMonroy** [comment]
@msampaio,
Eu gerei uma lista com apenas as obras que necessitam análise (são 58). A partir disso dividi elas nos três grupos das diferentes avaliações que tenho que fazer e fiz o download das obras (não as coloquei no copy, pois não sei ainda quais nos serão úteis).
Com isso faço o trabalho por etapas e grau de dificuldade. Por exemplo, estudando todos os compositores de análise de período de uma vez, abrindo todas as obras que necessitam análise de instrumentação.
O maior desafio são os livros de músicas anônimas e os compêndios de diversos autores, que precisamos ver até que ponto devo analisar. 
Deixei para colocar no copy apenas a lista final, por isso que ainda não coloquei nenhum arquivo novo.

**Comment by MarinaMonroy** [comment]
Não iniciei ainda o trabalho das obras de diversos autores e/ou anônimos, como estou partindo do mais simples para o mais complexo, comecei com a parte de  instrumentação e obras de apenas um compositor para verificar período.

**Comment by MarinaMonroy** [comment]
@msampaio @robattolucas, usaremos peças para german flute?

**Comment by robattolucas** [comment]
Sim, este era nome que os anglofonos chamavam o traverso.
 Em 02/12/2013 14:31, "MarinaMonroy" notifications@github.com escreveu:

**Comment by MarinaMonroy** [comment]
Ok, no caso de obras escritas com indicação para outro instrumento mas "adaptadas para german flute" usaremos, confere?

**Comment by robattolucas** [comment]
Isto!

2013/12/2 MarinaMonroy notifications@github.com

**Comment by MarinaMonroy** [comment]
Ok. Daqui a algumas horas postarei novas duas listas atualizadas com as obras inadequadas e as que usaremos já com as obras que já analisei. Ainda faltam obras para analisar, mas vou aos poucos acrescentando. O que vou colocar hoje já representará um longo trabalho para a equipe de transcrição (bem mais de 300 pequenas peças)

**Comment by MarinaMonroy** [comment]
Status: Prossigo com a avaliação das obras contando agora com um total de 29 obras adequadas e 45 sob análise.

**Comment by msampaio** [comment]
Ótimo, @MarinaMonroy

**Comment by MarinaMonroy** [comment]
@msampaio @robattolucas, algumas obras eu deixei separadas por uma questão: No caso de coletâneas, o que define  é o ano da primeira publicação?
Em caso de coletânea sem data, levo em consideração cada obra individualmente?

**Comment by msampaio** [comment]
Eu não sei. O que acha, @robattolucas?

**Comment by robattolucas** [comment]
Acho que a data deve ser enquanto possivel a da finalização de cada obra,
e isto pode ser determinado por indicação do compositor, data da 1a
publicação da obra, data da 1a publicação da coleção ou então (quando não
forem encontradas nenhumas indicações) por "média" do período de vida do
compositor - nesta ordem.

Em 12/01/2014 09:01, "Marcos da Silva Sampaio" notifications@github.com
escreveu:

**Comment by MarinaMonroy** [comment]
@robattolucas e quando a coletânea tem ano posterior de publicação, porém as canções são folclóricas?

**Comment by robattolucas** [comment]
Conta o ano da publicação, pois editores sempre "interferem" e "atualizam"
o conteúdo musical de obras, ainda mais neste período.

Em 12 de janeiro de 2014 19:04, MarinaMonroy notifications@github.comescreveu:

**Comment by msampaio** [comment]
@MarinaMonroy, essa tarefa já está Concluída?

**Comment by MarinaMonroy** [comment]
Sim Marcos!
