### ISSUE TITLE
Documentar patch exemplo-markov.pd

### ISSUE THREAD

**Issue by gbertis** [msampaio/flauta-solo#118]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas
- Complementar documentação do patch `exemplo-markov.pd`
-  Adicionar comentários específicos em cada módulo

**Comment by msampaio** [comment]
@menahemhein, essa tarefa está aberta há um mês. Qual o estado?

**Comment by menahemhein** [comment]
Tarefa Concluída Marcos ! Esperando o Prof. Guilherme fechar !

**Comment by gbertis** [comment]
Marcos,
Como a tarefa não tinha sido concluída no prazo, ficou aberta.
Foi finalizada na semana passada. Acabei de fechar.
