### ISSUE TITLE
Propor código identificador para movimentos de composições

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#12]
Os arquivos PDF do IMSLP têm um prefixo como `IMSLP00001` e um sufixo como `Fantasias_Telemann`. Prefixo e sufixo são separados por `-`. Usaremos o prefixo como identificador no software que desenvolveremos.
Nesta pesquisa consideraremos como unidade cada movimento de uma composição (vide [ata](http://genosmus.com/2013/07/ata-da-reuniao-de-25072013/)). No IMSLP há casos em que os movimentos estão em arquivos separados, e casos em que todos os movimentos estão em um único arquivo.
Nos casos em que os movimentos estão em um só arquivo, teremos que separa-los. Precisaremos então gerar um código novo para cada um desses movimentos.
No software eu usarei o `-` como delimitador do prefixo. Eu pensei em inserir uma letra para cada movimento antes do `-`. Por exemplo, `IMSLP00001a` e `IMSLP00001b`.
A tarefa é definir um código identificador dos movimentos da composição que aproveite o prefixo do IMLSP.
Verifique se essa minha proposta das letras é eficiente, se existem letras no código do IMSLP, e como fazer com o caso de métodos que têm mais de 26 exercícios em um único livro.
Leia os resultados da tarefa #1 antes de começar.

**Comment by msampaio** [comment]
@patrickandrews, anos atrás eu trabalhei na criação de um código de identificação de documentos (sob orientação de Lucas). Escrevi um [artigo](http://www.mendeley.com/c/6018908224/g/3494461/sampaio-2004-os-documentos-do-teatro-sao-joao-no-arquivo-publico-do-estado-da-bahia-catalogando-e-gerenciando-informacoes/) sobre este código. Talvez seja útil para realizar esta tarefa. O PDF está em `Bibliografia`, no Copy.

**Comment by msampaio** [comment]
@patrickandrews, qual o estado desta tarefa? Precisa de alguma ajuda?

**Comment by patrickandrews** [comment]
Estou retomando. Como havia comentado, fiquei sem computador. Consegui comprar um outro processador e por sorte, ele chegou ontem e já estou configurando meu pc.

Eu vi a tarefa #1 bem como o seu artigo e chequei alguns arquivos do IMSLP. O que estou me questionando é em relação ao tamanho do arquivo. O Windows geralmente limita os nomes de arquivos em 260 caracteres. Mas o nome do arquivo, na verdade, deve ser mais curto que isso, já que o caminho completo (como C:\Arquivos de Programa\nome_do_arquivo.txt) está incluído nessa contagem de caracteres. Por isso que podemos, ocasionalmente, encontrar um erro ao copiar um arquivo com um nome muito longo para um local que possua um caminho mais longo que o local atual.

No mac antigamente só possuia nome de arquivo máximo de 31 caracteres, mas já corrigiu isso tendo capacidade máxima de 255 caracteres (acho que é a mesma quantidade para o windows xp). Como funciona isso no Linux?

Acha que é algo pertinente a se levar em consideração?

**Comment by msampaio** [comment]
@patrickandrews, foi bom você observar estas questões dos caracteres no nome do arquivo. Acho que o ideal seria ter até 8 caracteres, como existia originalmente no DOS. Poderíamos ter, por exemplo, `I000001` para o arquivo `IMSLP000001-qualquer_extensão_possível`. Ainda poderíamos ter um caractere para cada composição e outro para os movimentos. Então, o movimento 2 da música 3 da fonte `I000001` seria algo como `I000001bc`. O que você acha?

**Comment by msampaio** [comment]
@patrickandrews, continuarei a anotar as ideias sobre esta codificação aqui.
Durante a transcrição das 12 Fantasias de Telemann nós usamos a codificação `EXTRA0001` a `EXTRA0012` para cada uma das fantasias. Esta codificação é problemática, pois de fato tempos apenas uma fonte: "EXTRA0001-Telemann - Fantasies flute (with facsimile - Musica Rara)". Acho importante manter a referência a essa única fonte na codificação. Então talvez seja melhor usar algo como `EXTRA0001_01` a `EXTRA0001_12` para cada uma das fantasias. Os movimentos podem ser inseridos depois: `EXTRA0001_01a`, `EXTRA0001_01b` e assim por diante.
Nas partituras transcritas teremos ainda uma versão "expandida". Nesta versão nós escrevemos os sinais de repetição da música por extenso. Estas partituras podem conter o símbolo `E` no final, como em `EXTRA0001_01aE`.
Para simplificar o código podemos usar o prefixo `E` no lugar de `EXTRA`. Dessa forma, a transcrição expandida do segundo movimento da primeira peça da fonte `EXTRA0001` seria `E0001_01bE`. O que você acha?
@ZeRodriguez, @AlissonGSilva e @daniloabrahao, qual a opinião de vocês sobre esta codificação? Uma vez batido o martelo, teremos que nos acostumar a chamar todas as partituras com esses códigos.

**Comment by patrickandrews** [comment]
@msampaio Por que "EXTRA"? E você pode exemplificar, só para ter certeza de que eu entendi, como ficaria um nome completo, por exemplo da 2ª Fantasia 2b?

**Comment by ZeRodriguez** [comment]
@patrickandrews, a nomenclatura `EXTRA` se dá pelo fato de ser o nome da fonte. É assim que o arquivo é nomeado quando baixado. @msampaio, por mim não tem problemas com essa nova nomenclatura. Só é preciso um tempo para nos adaptarmos.

**Comment by msampaio** [comment]
@patrickandrews e @ZeRodriguez:
1. o código `EXTRA` é arbitrário e serve para os casos em que usaremos fontes próprias para músicas que estão no IMSLP. Se tiver ideia melhor, pode sugerir. Coloquei `EXTRA` para diferenciar de `IMSLP` e podermos começar com as transcrições.
2. A fonte `EXTRA0001` contém todos os movimentos de todas as 12 fantasias de Telemann. O movimento n. 2 da Fantasia 2 desta fonte seria codificada como `EXTRA0001_02b`.
3. Estou propondo simplificarmos os códigos `EXTRA` e `IMLSP` para `E` e `I`, respectivamente. Dessa forma, o código da fonte `EXTRA0001_02b` seria transformado em `E0001_02b`. O código de uma fonte genérica `IMSLP123456` seria transformado em `I123456`.
4. Precisamos testar se essa nomenclatura cobrirá outros tipos de obras musicais. Teremos exemplos para testar logo que a tarefa #45 estiver concluída.

**Comment by patrickandrews** [comment]
Entendi. Bem, era justamente isso que iria sugerir. Acho que realmente não é necessário aumentar o número de caracteres, no caso de usarmos EXTRA, por exemplo, apenas o E e do IMLSP o I, como você mencionou, é suficiente.

**Comment by ZeRodriguez** [comment]
Entendi.

**Comment by msampaio** [comment]
Ótimo, @patrickandrews. Você pode escrever um texto documentando como o código funciona para colocarmos no manual da pesquisa?

**Comment by patrickandrews** [comment]
Sim. Vou fazer.

**Comment by AlissonGSilva** [comment]
Eu acredito que funciona  essa que Marcos sugeriu: `EXTRA` e `IMLSP` para `E` e `I`. É um sistema parecido com o sistema alfanumérico de placas de identificação de veículos antigamente, a letra indicava o Estado de origem do veículo.

**Comment by daniloabrahao** [comment]
@msampaio, eu acho que a sua sugestão de codificação (ex.:`E0001_01b` e `E0001_01bE`) é boa. Acho que é, de certa forma,  mais simples. Vai ser só uma rápida questão de tempo até nos acostumar. Mas não tenho tato suficiente para saber se essa nova codificação pode gerar algum problema.

**Comment by msampaio** [comment]
@patrickandrews, você está precisando de alguma ajuda para documentar o código no manual da pesquisa? Estou precisando que você conclua esta tarefa para que eu possa seguir em frente no projeto.

**Comment by patrickandrews** [comment]
@msampaio Eu estava preparando um texto, mas realmente agora estou com dúvida. O tipo de texto tem que ser curto e direto ou precisa relatar em detalhes o que se foi pensado até chegar a conclusão?

**Comment by msampaio** [comment]
Curto e direto.

**Comment by patrickandrews** [comment]
https://docs.google.com/document/d/1nSecR_DbSAyrIQG94scwfBoKKlr6WWl14J0Wg3LxU3o/edit?usp=sharing

**Comment by msampaio** [comment]
@patrickandrews, o caminho é esse. Falta explicar o que é `0001` e `01`, dizer que a versão expandida é opcional, e dizer que depois desse código pode haver um sufixo aleatório separado por `-`, indicando nome da peça, do compositor, ou qualquer outra informação. Em geral o sufixo é fornecido pelo IMSLP.

```
¹                ² 
E0001_01aE

E¹ - Simboliza EXTRA, mesmo código utilizado na transcrição das 12 Fantasias de Telemann.
0001_01 - Número da peça.
a - 1º movimento. No caso de 2º movimento, utilizar b.
E² - Refere-se a versão expandida.
```

**Comment by patrickandrews** [comment]
@msampaio Fiquei em dúvida da necessidade do 0001 e 01. Me ferido dos dois aparecerem juntos.

**Comment by msampaio** [comment]
@patrickandrews, existem casos em que uma fonte contém uma única música. Nesse caso o `01` seria desnecessário. No entanto há casos em que uma fonte contém várias músicas, como o nosso EXTRA0001. Nesse caso é preciso diferenciar cada uma das músicas. Nesse caso é necessário ter o `01`.

**Comment by patrickandrews** [comment]
https://docs.google.com/document/d/1nSecR_DbSAyrIQG94scwfBoKKlr6WWl14J0Wg3LxU3o/edit

**Comment by msampaio** [comment]
@patrickandrews uma maneira mais formal de descrever seria:

`ab_cde`, onde
- `a` - caractere alfanumérico que descreve origem da fonte. `I` para IMSLP e `E` para fontes extras
- `b` - conjunto de 6 caracteres numéricos que descrevem a identificação da fonte. É o mesmo valor usado no IMSLP
- `c` - conjunto de 2 caracteres numéricos opcionais que descrevem o número da música dentro da fonte. Nos casos em que a fonte tem uma única música, o valor padrão é `00`.
- `d` - caractere alfabético que indica o movimento dentro da música. Nos casos de movimento único, o valor padrão é `a`.
- `e`\- caractere `E` opcional, para os documentos com repetições formais expandidas.

**Comment by patrickandrews** [comment]
Devo então substituir estritamente para essa maneira e deletar a parte de baixo do arquivo?

https://docs.google.com/document/d/1nSecR_DbSAyrIQG94scwfBoKKlr6WWl14J0Wg3LxU3o/edit

**Comment by msampaio** [comment]
@patrickandrews, a versão que você fez no google docs ficou boa. Você pode inserir no [manual](http://genosmus.com/pesquisa/flauta-solo/manual/)? Eu criei um usuário para você editar o manual

**Comment by patrickandrews** [comment]
Posso sim. Qual usuário?

**Comment by msampaio** [comment]
Você deve receber senha e login por email.

**Comment by patrickandrews** [comment]
Eu devo inserir em tarefas? E qual título?
Por sinal, ao fazer isso, depois você terá que validar uma nova senha para Alisson uma vez em que ele ficará bloqueado.

**Comment by msampaio** [comment]
@patrickandrews, insira no final com o título "Código de identificação de arquivos".
Qual o problema com @AlissonGSilva? Eu criei um login patrick e cadastrei seu email para o envio eletrônico da senha.

**Comment by patrickandrews** [comment]
Quando vou em editar, aparece a seguinte mensagem: "This content is currently locked. If you take over, Alisson Silva will be blocked from continuing to edit."

**Comment by patrickandrews** [comment]
Devo prosseguir?

**Comment by msampaio** [comment]
Entendi agora. Aguarde alguns minutos. Só é possível ter uma pessoa editando as páginas de cada vez.

**Comment by AlissonGSilva** [comment]
Está livre agora @patrickandrews , terminei de editar a página.

**Comment by patrickandrews** [comment]
@msampaio Pode conferir? http://genosmus.com/pesquisa/flauta-solo/manual/

Eu adicionei o exemplo também. Porém, é necessário?

**Comment by msampaio** [comment]
Ficou muito bom, @patrickandrews. O exemplo era essencial. Insira apenas esse texto antes de apresentar o código:
"Os arquivos de fontes e partituras do projeto são codificados de acordo com este esquema:".
Fechando tarefa.

**Comment by patrickandrews** [comment]
@msampaio Por favor, veja se ficou certo.

**Comment by msampaio** [comment]
Sim

**Comment by msampaio** [comment]
@patrickandrews, @ZeRodriguez, @AlissonGSilva e @daniloabrahao, só podemos saber se o código funciona testando na prática. Verifiquei duas questões referentes ao nosso código:
1. Apenas os dois primeiros campos precisam ser obrigatório. Aparentemente o código `E00001` é suficiente para identificar a fonte das 12 fantasias de Telemann que usamos.
2. O código não estabelece diferença entre fonte e transcrição de nossa autoria. O único elemento que nos ajuda a diferenciar é o tipo de arquivo---pdf para as fontes. No entanto se precisarmos gerar pdf para as transcrições podemos ficar confusos.

Então proponho as seguintes alterações:
1. Inserção obrigatório de um caractere alfabético entre os campos `a` e `b` indicando se o código está identificando uma fonte (`F`) ou transcrição (`T`).
2. Obrigatoriedade apenas para esses 3 novos primeiros campos: Classificação de fonte, Fonte ou transcrição, Número de identificação.

Dessa forma nosso código passa a ser:

`abc_def-g`, onde:
- `a`: Caractere alfanumérico que identifica a origem da fonte. `I` para IMSLP e `E` para fontes extras.
- `b`: Caractere alfanumérico que identifica se o documento é uma fonte ou transcrição.
- `c`: Conjunto de 5 caracteres numéricos que descrevem a identificação da fonte. É o mesmo valor usado no IMSLP.
- `d`: Conjunto de 2 caracteres numéricos opcionais que descrevem o número da música dentro da fonte. Estes caracteres devem ser precedidos sempre pelo separador `_`.
- `e`: Caractere alfabético opcional que indica o movimento dentro da música.
- `f`: Caractere E opcional, para os documentos com repetições formais expandidas.
- `-`: Separador de código e sufixo
- `g`: Sufixo opcional, indicando nome do compositor, da peça e quaisquer outras informações geralmente fornecidas pelo IMSLP.

Vejam alguns exemplos de uso desse novo código:
- `EF00001` - Fonte das 12 Fantasias de Telemann
- `ET00001_01a` - Transcrição da Fantasia 1, mov. 1
- `ET00001_03d` - Transcrição da Fantasia 3, mov. 4
- `ET00001_01bE` - Versão expandida da transcrição da Fantasia 1, mov. 2
- `ET00001_12aE` - Versão expandida da transcrição da Fantasia 12, mov. 1

**Comment by ZeRodriguez** [comment]
@msampaio, começarei a renomear conforme seu comentário acima. Amanhã estará pronto!
