### ISSUE TITLE
Preparar apresentação das leituras sobre Musicologia Computacional

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#128]
O objetivo da tarefa é elaborar uma apresentação de 3 a 5 minutos sobre o levantamento bibliográfico sobre Musicologia Computacional. Para preparar a apresentação recomendo:
1. Definir Musicologia Computacional
2. Listar estudos que têm sido feitos nessa área e falar dos tipos de resultados
3. Mostrar como podemos nos apropriar dos conhecimentos dessa área em nosso projeto.

**Comment by SimeiFerreira** [comment]
@msampaio, será necessário preparar slides ou uma apresentação oral é o suficiente?

**Comment by msampaio** [comment]
Basta a apresentação oral.
