### ISSUE TITLE
Preparar apresentação do estudo de técnicas estatísticas

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#129]
O objetivo da tarefa é elaborar uma apresentação de 3 a 5 minutos sobre o estudo de técnicas estatísticas. Para preparar a apresentação recomendo:
1. Apresentar as ações já realizadas sobre essas técnicas (por exemplo, disciplina do IM)
2. Apresentar sucintamente técnicas preliminares que podem ser usadas e como elas podem ajudar a otimizar os dados da pesquisa.

**Comment by SaraFadigas** [comment]
Tarefa concluida. Devo compartilhar as apostilas da matéria MAT236 no copy, juntamente com o PDF da apresentacao?

**Comment by msampaio** [comment]
Eu já coloquei as apostilas no Mendeley. Pode colocar o PDF na pasta de produção.
