### ISSUE TITLE
Extrair os movimentos da música `EXTRA0001` - Fantasias de Telemann

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#13]
A tarefa consiste em salvar cada movimento da música `EXTRA0001-Telemann - Fantasies flute (with facsimile - Musica Rara)` em arquivos PDF separados. Por enquanto salve cada movimento como `EXTRA0001a`, `EXTRA0001b`, e assim por diante. Observe que o prefixo não entrará no código. Até que a tarefa #12 seja concluída, utilizaremos este sistema de codificação.
Peço agilidade nesta tarefa, pois dependemos de sua conclusão para atribuir as tarefas dos outros colaboradores.
Caso tenha dificuldade para separar os arquivos PDF avise por aqui mesmo.
@SimeiFerreira deverá acompanhar esta tarefa para documentá-la no manual.

**Comment by daniloabrahao** [comment]
Documentando a conversa com @msampaio do dia 12/08:

O arquivo `EXTRA0001-Telemann - Fantasies flute (with facsimile - Musica Rara)` é constituído por 3 partes:
1ª) Aparato crítico (p. 1-4);
2ª) Fac-simile da fonte original (p. 5-17);
3ª) Edição moderna.

As Fantasias de Telemann são um conjunto de 12 obras distintas e independentes entre si. Cada uma delas é dividida em pequenos movimentos. Logo, no arquivo, algumas páginas contém mais de um único movimento. E a partir disso, fragmentar o arquivo em seus movimentos se torna uma tarefa inviável.

Para explicar como realizarei esta tarefa, vou dar um exemplo:
A Fantasia Nº1 da edição moderna são duas páginas, sendo que a primeira contém a maior parte do 1º movimento e a segunda contém o fim do 1º e todo o 2º movimento.
Os arquivos referentes à Fantasia Nº1 ficarão nomeados, então, da seguinte maneira:
`EXTRA0001a`
`EXTRA0001b`
Sendo que o primeiro consistirá nas duas paginas enquanto o segundo consistirá apenas na 2ª.
O mesmo será feito com os demais movimentos com a seguinte lógica de nomenclatura de arquivos:
[EXTRA000+número da fantasia+nº do movimento(a,b,c,...)].

**Comment by msampaio** [comment]
Ótimo, @daniloabrahao. No entanto acho que você quis dizer "Os arquivos referentes aos movimentos 1 e 2 da Fantasia ficarão nomeados, então, da seguinte maneira".

@patrickandrews, leve essa questão levantada por Danilo para resolver a tarefa #12.

**Comment by daniloabrahao** [comment]
Obrigado pela correção @msampaio.
Ao chegar na fantasia Nº 5 vi que do início até a primeira barra dupla existem 4 indicações de andamento:
![image](https://f.cloud.github.com/assets/4681458/951152/76f8979c-039c-11e3-8eb1-4745f2c71995.png)

Cheguei a conclusão de que todos os movimentos são delimitados por barra dupla.Essa informação procede? E eu considerei as indicações de andamento como início de novos movimentos.

**Comment by msampaio** [comment]
@daniloabrahao, eu concordo com a delimitação da barra dupla. Os andamentos diferentes (presto, largo, presto, largo) segmentam o movimento em seções. De qualquer forma acho bom ter a confirmação de @robattolucas.

**Comment by daniloabrahao** [comment]
Feito.

**Comment by msampaio** [comment]
@daniloabrahao, acabei de perceber que o que chamamos de movimento 1 da Fantasia de Telemann n. 2 (tarefa #17) tem finalização na região tonal da dominante. Acredito que este movimento se funde ao que chamamos de movimento 2, que tem finalização na tônica. Você pode confirmar com @robattolucas a divisão de movimentos desta fantasia?

**Comment by daniloabrahao** [comment]
Confirmarei isso e a questão da tarefa de transcrição da Fantasia IX com
Lucas. Até hoje, esclarecerei isso.

**Comment by msampaio** [comment]
Deixarei a tarefa reaberta até termos essa informação.

**Comment by robattolucas** [comment]
Repito abaixo o que respondi ao Danilo:

Oi Danilo,

Boas perguntas:
1. A partir do barroco é relativamente frequente terminar um movimento na dominante, criando um efeito se suspensão e expectativa de resolução. A maioria das sonata da chiesa terrmina o 1o mov (lento) na dominante.
2. Aqui o Kuijken (ou o diagramador) "comeu mosca". Pode corrigir de acordo com o original.

**Comment by msampaio** [comment]
Fechando tarefa.

**Comment by daniloabrahao** [comment]
Pessoal, me atrapalhei para enviar o e-mail pra vocês e acabou caindo aqui. Favor chegar a caixa de entrada!
