### ISSUE TITLE
Implementar algoritmos de redução de contornos de Bor

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#132]
Implementar os algoritmos de Redução de Mustafa Bor (2009). Usar o próprio repositório do GitHub para guardar os arquivos.
A dissertação de Bor está disponível no Mendeley e diretório Bibliografia, no Copy.

**Comment by msampaio** [comment]
@azevedospider, qual o estado da tarefa? Ainda não vi commits no repositório do projeto.

**Comment by ghost** [comment]
desculpe prof, mas hoje eu faço o commit do codigo, demorei um pouco porque
eu não tenho dominio da linguagem python.

2013/11/24 Marcos da Silva Sampaio notifications@github.com

> @azevedospider https://github.com/azevedospider, qual o estado da
> tarefa? Ainda não vi commits no repositório do projeto.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/132#issuecomment-29156375
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by ghost** [comment]
as próximas implementações tentarei ser o mais objetivo possível!

Em 25 de novembro de 2013 09:33, Danilo Azevedo
azevedo.spider@gmail.comescreveu:

> desculpe prof, mas hoje eu faço o commit do codigo, demorei um pouco
> porque eu não tenho dominio da linguagem python.
> 
> 2013/11/24 Marcos da Silva Sampaio notifications@github.com
> 
> > @azevedospider https://github.com/azevedospider, qual o estado da
> > tarefa? Ainda não vi commits no repositório do projeto.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/132#issuecomment-29156375
> > .
> 
> ## 
> 
> Danilo Azevedo Santos
> Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
> Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
> TEL. (71) 33863619/ 82869358 /92802927
> E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
> Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
Ok, @azevedospider. Se precisar de suporte em Python é só avisar.

**Comment by ghost** [comment]
Professor Marcos, coloquei um dos códigos que estou fazendo no git, segue o
link;

https://github.com/azevedospider/AlgoritmoDeReducaoDoContorno

2013/11/25 Marcos da Silva Sampaio notifications@github.com

> Ok, @azevedospider https://github.com/azevedospider. Se precisar de
> suporte em Python é só avisar.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/132#issuecomment-29205612
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
@azevedospider, verei seu algoritmo e em breve entrarei em contato. Eu recomendo usar uma pasta deste repositório FlautaSolo para colocar o código. Assim poderemos nos referir aos arquivos e commit mais facilmente.

**Comment by ghost** [comment]
certo

Em 26 de novembro de 2013 19:13, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> @azevedospider https://github.com/azevedospider, verei seu algoritmo e
> em breve entrarei em contato. Eu recomendo usar uma pasta deste repositório
> FlautaSolo para colocar o código. Assim poderemos nos referir aos arquivos
> e commit mais facilmente.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/132#issuecomment-29340246
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
@azevedospider, estou no aguardo do commit com algoritmo neste repositório.

**Comment by ghost** [comment]
certo!

2013/11/29 Marcos da Silva Sampaio notifications@github.com

> @azevedospider https://github.com/azevedospider, estou no aguardo do
> commit com algoritmo neste repositório.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/132#issuecomment-29525333
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by ghost** [comment]
prof, acho que teve um problema com meu commit, depois do "push" sumiu os
commits feitos anteriormente lá no repositório flauta solo, o sr. tem
backups, estou tentando reverter!

Em 29 de novembro de 2013 22:00, Danilo Azevedo
azevedo.spider@gmail.comescreveu:

> certo!
> 
> 2013/11/29 Marcos da Silva Sampaio notifications@github.com
> 
> > @azevedospider https://github.com/azevedospider, estou no aguardo do
> > commit com algoritmo neste repositório.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/132#issuecomment-29525333
> > .
> 
> ## 
> 
> Danilo Azevedo Santos
> Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
> Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
> TEL. (71) 33863619/ 82869358 /92802927
> E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
> Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by ghost** [comment]
*sr. tem backups??

Em 3 de dezembro de 2013 20:51, Danilo Azevedo
azevedo.spider@gmail.comescreveu:

> prof, acho que teve um problema com meu commit, depois do "push" sumiu os
> commits feitos anteriormente lá no repositório flauta solo, o sr. tem
> backups, estou tentando reverter!
> 
> Em 29 de novembro de 2013 22:00, Danilo Azevedo azevedo.spider@gmail.comescreveu:
> 
> certo!
> 
> > 2013/11/29 Marcos da Silva Sampaio notifications@github.com
> > 
> > > @azevedospider https://github.com/azevedospider, estou no aguardo do
> > > commit com algoritmo neste repositório.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/132#issuecomment-29525333
> > > .
> > 
> > ## 
> > 
> > Danilo Azevedo Santos
> > Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
> >  Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
> > TEL. (71) 33863619/ 82869358 /92802927
> > E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
> > Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit
> 
> ## 
> 
> Danilo Azevedo Santos
> Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
> Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
> TEL. (71) 33863619/ 82869358 /92802927
> E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
> Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
@azevedospider, já fiz um merge dos seus commit com os meus. Agora está tudo ok. Por favor faça sempre `git pull` do repositório antes de fazer `push`.

**Comment by msampaio** [comment]
@azevedospider, abrirei uma outra tarefa para tratarmos do algoritmo de Morris.
Para finalizar essa tarefa eu preciso que você mova para este repo o algoritmo de Bor que você implementou.

**Comment by msampaio** [comment]
@azevedospider, eu implementei o algoritmo de Bor no commit a0251f24fa491f70a4cdf81ae22e7cc110f5d89f. Compare com sua implementação.

**Comment by ghost** [comment]
certo o farei, farei mais um commit hj com atualização de correção do
código que implementei...

2013/12/6 Marcos da Silva Sampaio notifications@github.com

> @azevedospider https://github.com/azevedospider, eu implementei o
> algoritmo de Bor no commit a0251f2https://github.com/GenosResearchGroup/FlautaSolo/commit/a0251f24fa491f70a4cdf81ae22e7cc110f5d89f.
> Compare com sua implementação.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/132#issuecomment-30008254
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
@azevedospider, por favor coloque o código do algoritmo que você fez em https://github.com/azevedospider/AlgoritmoDeReducaoDoContorno/blob/master/ReductionContorno.py no repositório da pesquisa, para que eu possa comentar.

**Comment by msampaio** [comment]
@azevedospider, estou no aguardo do código do algoritmo de Bor, conforme mensagem anterior.

**Comment by msampaio** [comment]
@azevedospider, algum problema para fechar essa tarefa? Conforme combinamos estou aguardando o fechamento até amanhá.

**Comment by ghost** [comment]
https://github.com/GenosResearchGroup/FlautaSolo/blob/newAlgorithms/reducaoContorno/danilo/reductBor/reductBor.py #132
