### ISSUE TITLE
Definir corpus de conceitos de forma

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#133]
O objetivo da tarefa é listar um corpus inicial de conceitos formais necessários ao estudo. Por exemplo, motivo, frase, segmento, período, movimento, etc.

**Comment by ZeRodriguez** [comment]
Em andamento! =D
Essa tarefa e  a  #134 dependem uma da outra!

**Comment by msampaio** [comment]
@ZeRodriguez, precisamos fechar esta tarefa para poder iniciar o trabalho com segmentações. O que falta para a conclusão?

**Comment by msampaio** [comment]
@ZeRodriguez estou no aguardo de sua resposta quanto à esta tarefa.

**Comment by ZeRodriguez** [comment]
@msampaio , desculpe a demora. Fessô, revirando as anotações que tenho, fiz umas traduções e ou resumos dos conceitos mais usados. Colocarei no `Copy` e peço que dê uma olhada para ver se estou correto.

**Comment by ZeRodriguez** [comment]
O arquivo já se encontra na pasta `Produção` no formato `pdf` salvo como `Conceitos sobre Forma`.

**Comment by msampaio** [comment]
@ZeRodriguez, você se antecipou a uma tarefa posterior, de definir cada conceito sobre forma.
Nesta tarefa o objetivo é definir que conceitos são esses. Você falou em frase, período, forma, divisão em partes. No entanto precisamos ter uma lista do que realmente é necessário definir: motivos? segmento? O resultado da tarefa deverá ser uma lista de estruturas. A busca pela definição de cada estrutura será feita em etapa posterior, dando continuidade ao que você já adiantou.

**Comment by msampaio** [comment]
Com a eliminação da segmentação manual, essa tarefa perdeu o sentido. fechando.
