### ISSUE TITLE
Segmentar ET00001_01aE de forma gráfica

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#134]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em segmentar a obra de forma gráfica. Os segmentos podem ser anotados em um arquivo pdf, por exemplo. Não é preciso definir a tipologia dos segmento.
O conteúdo deve ser salvo na pasta produção como 'Segmentação ET00001_01aE.pdf'.

**Comment by msampaio** [comment]
@ZeRodriguez, faça a segmentação desta fonte, mesmo sem os conceitos de forma definidos. Foque no nível das frases. Não precisa necessariamente indicar se é frase, se não é, se há períodos. O objetivo é apenas ter material para @SimeiFerreira seguir com a tarefa #135.

**Comment by msampaio** [comment]
@ZeRodriguez, qual o estado da tarefa? Preciso da conclusão para @SimeiFerreira seguir com a tarefa #135.

**Comment by ZeRodriguez** [comment]
Tarefa concluída! =D
O arquivo já se encontra na pasta.
