### ISSUE TITLE
Analisar contorno do segmento 1 de ET00001_01aE (parte 1)

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#135]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Esta tarefa depende da conclusão da tarefa #134.
A tarefa consiste em analisar o contorno melódico do segmento como forma de praticar os conteúdos da Teoria de Relações de Contornos Musicais.
1. Ler as seguintes seções de Sampaio 2012: 2, 2.1, 2.2, 2.4.1 a 2.4.5
2. Definir a representação do segmento de contorno, forma normal e classe de contornos equivalentes do segmento musical da obra de Telemann.

A análise deverá ser colocada na pasta Produção como 'Análise de contornos ET00001_01aE Segmento 1.txt'

**Referência**
Sampaio, Marcos da Silva. 2012. “A Teoria de Relações de Contornos Musicais: Inconsistências, Soluções e Ferramentas”. Universidade Federal da Bahia.

**Comment by msampaio** [comment]
@SimeiFerreira, qual o estado desta tarefa? @ZeRodriguez já fez a segmentação há uma semana.

**Comment by SimeiFerreira** [comment]
@msampaio, eu estou relendo o material para fixar melhor o conteúdo, quero compreender bem o assunto antes de concluir a tarefa.

**Comment by msampaio** [comment]
@SimeiFerreira, não adianta tentar compreender bem o assunto para concluir a tarefa. Você vai aprender o assunto **enquanto** faz a tarefa.

**Comment by SimeiFerreira** [comment]
@msampaio, a minha dificuldade está justamente em colocar os conceitos em prática a partir da segmentação formal, eu ainda estou meio perdido, por isso estou refazendo a leitura. Penso que encontrando o caminho ficará mais fácil nas próximas análises.

**Comment by msampaio** [comment]
@SimeiFerreira, leia as seções que indiquei já buscando as respostas para as questões: segmento de contorno, forma prima, etc.

**Comment by SimeiFerreira** [comment]
Estou fazendo isso @msampaio, a propósito, tomei a liberdade de refazer a leitura de sua tese do começo, o que esclareceu bastante as coisas pra mim. Ainda existem algumas dúvidas remanescentes que listarei aqui caso persistam ao final da releitura.

**Comment by SimeiFerreira** [comment]
@msampaio, a referida obra fora dividida em 7 segmentos, você quer que eu analize separadamente os contornos de cada um desses segmentos, certo?

**Comment by msampaio** [comment]
@SimeiFerreira, quero a análise do primeiro segmento

**Comment by SimeiFerreira** [comment]
@msampaio, Dúvida remanescente:

Se no espaço de contorno não existe repetições adjacentes de pontos de contorno, qual a finalidade das repetições não adjacentes nos segmentos de contorno? Na seção 2.4.2 você diz que essas repetições podem ser organizadas de maneira a gerar infinitos segmentos de contorno, mas ainda não ficou claro para mim o porque delas.

**Comment by msampaio** [comment]
O espaço de contorno é apenas o conjunto de todos os elementos do contorno. Por definição, não há repetição de elementos em um conjunto. No entanto, o segmento de contorno é uma organização ordenada dos elementos de contorno.
Em analogia ao uso de escalas, a escala maior tem apenas sete elementos (espaço das notas), no entanto você pode ter tantas notas quanto quiser em uma melodia (organização ordenada das notas).
Entendeu?

**Comment by SimeiFerreira** [comment]
Entendi, qual parâmetro devo utilizar na análise de contorno do segmento em questão? Pode ser altura?

**Comment by msampaio** [comment]
Sim, altura

On Tuesday, December 10, 2013, SimeiFerreira wrote:

> Entendi, qual parâmetro devo utilizar na análise de contorno do segmento
> em questão? Pode ser altura?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/135#issuecomment-30279688
> .

## 

Sent from my Mobile

**Comment by SimeiFerreira** [comment]
Qual a diferença entre cardinalidade e ordem? Ou são a mesma coisa?

**Comment by SimeiFerreira** [comment]
@msampaio, fiz a análise da segmentação de contorno e da forma normal, preciso do seu feedback. Ainda estou com algumas dúvidas em relação à classe de contornos equivalentes. Como saber quantas classes de contorno existem por cada cardinalidade, além de identificá-las?

**Comment by msampaio** [comment]
Ao meu entender, ordem e cardinalidade se referem à mesma coisa: número de elementos distintos de um dado conjunto. Sobre a identificação de classes de contornos, veja a seção 4.4 da tese. Sobre o número de possibilidades, veja o coeficiente binominal, na seção 2.3.3.

**Comment by msampaio** [comment]
No coeficiente binominal, o sinal `!` significa fatorial. Por exemplo, o fatorial de 4 é 4_3_2*1 = 24.

**Comment by msampaio** [comment]
@SimeiFerreira, o que falta para concluir esta tarefa?

**Comment by SimeiFerreira** [comment]
@msampaio, você poderia checar se a análise do segmento de contorno e forma normal estão corretas? Se estiver tudo ok, fica faltando somente a análise das classes de contornos equivalentes, no qual já estou trabalhando.

**Comment by msampaio** [comment]
@SimeiFerreira, o seu segmento de contorno está correto. Recomendo que faça as operações relacionadas a esse trecho mais curto da imagem abaixo para treinar. Continue registrando as dúvidas aqui.

![screen shot 2013-12-15 at 17 39 42](https://f.cloud.github.com/assets/1006488/1751083/5642c65a-65c9-11e3-94f9-db1c51ddb64d.png)

**Comment by SimeiFerreira** [comment]
@msampaio, você se refere a todas as operações ou às remanescentes?

**Comment by msampaio** [comment]
As operações indicadas na descrição da tarefa.

**Comment by SimeiFerreira** [comment]
@msampaio, depois de ler e reler por diversas vezes as seções que você me indicou aqui e as seções que você indica na tese dentro de outras seções eu imagino que tenha conseguido concluir a análise do trecho que você indicou, entretanto, eu exclui o último "lá" do trecho marcado, por um simples motivo... Analisando até o "mi" o segmento de contorno ficou com cardinalidade 4 cuja tabela de classes de contornos equivalentes está disponível para consulta na seção 2.4.4 da sua tese.

Eu explico: Ainda não ficou claro para mim como utilizar o coeficiente binominal para calcular o número de classes de contornos equivalentes de uma determinada cardinalidade, bem como encontrar quais segmentos de contornos ocupam cada uma dessas classes possíveis para essa cardinalidade, por conseguinte, não fui capaz de encontrar as classes de contornos equivalentes do segmento de contorno de cardinalidade 5 < 1 2 1 0 1 > referente ao trecho marcado acima.

As explicações detalhadas sobre a análise se encontram no mesmo arquivo de texto na pasta produção. Gostaria que você me desse um feedback por gentileza.

**Comment by msampaio** [comment]
@SimeiFerreira, a sua análise do contorno < 1 2 1 0 > está correta pela proposta de Marvin/Laprade, no entanto a eliminação do último valor pode levar a um perigo. Estamos trabalhando com uma situação abstrata, pois peguei um fragmento qualquer apenas para você treinar. No entanto, caso este fosse um motivo importante na música, a eliminação da última nota provavelmente te levaria a um erro de análise e invalidar seu estudo.

Não há grande diferença entre calcular a equivalência de contornos com repetição de 1 ou de mais elementos distintos. De qualquer modo recomendo ver a seção 4.4 para concluir a tarefa.

**Comment by SimeiFerreira** [comment]
@msampaio, eu já havia lido a seção 4.4 e sua proposta de representar as classes de contornos através da sua forma prima. A minha dificuldade não está em calcular a equivalência dos contornos a partir das matrizes de comparação, mas em como calcular quantas classes de contornos são possíveis para determinada cardinalidade e encontrar quais são esses contornos possíveis. Vou fazer novamente a partir da sua proposta.

**Comment by msampaio** [comment]
@SimeiFerreira, não precisa você fazer essa conta. Só a título de curiosidade, no caso desse contorno há 9 possibilidades: as 12 permutações, calculadas com o coeficiente binominal, 4! / (1! x 2! x 1!), menos as 3 possibilidades em que os valores 1 são adjacentes.
Na seção 4.4 da tese eu proponho não usar o número da permutação para representar a classe justamente por ele não acrescentar muita coisa.

**Comment by SimeiFerreira** [comment]
@msampaio, de fato a sua proposta simplifica um bocado na identificação da classe de contornos equivalentes. De por mim, a tarefa está concluída. Aguardo somente o seu feedback, se estiver correto podemos seguir adiante com o meu treinamento.
