### ISSUE TITLE
Fazer transcrição diplomática de EF00002-JSBach - Partita for Solo Flute anotada

### ISSUE THREAD

**Issue by ZeRodriguez** [msampaio/flauta-solo#136]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas
- A obra se encontra no arquivo `EF00002-JSBach - Partita for Solo Flute anotada`
- Fazer a transcrição da obra e salvá-la com o código `ET00002_01a`, `ET00002_01b` e assim por diante

**Comment by luanpiano** [comment]
Tarefa concluída.

**Comment by ZeRodriguez** [comment]
Valeu @luanpiano ! =D
