### ISSUE TITLE
Fazer transcrição diplomática de EF00003-CPEBach - Sonata in Aminor for Solo Flute anotada

### ISSUE THREAD

**Issue by ZeRodriguez** [msampaio/flauta-solo#137]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas
- A obra se encontra no arquivo `EF00003-CPEBach - Sonata in A minor anotada`
- Fazer a transcrição da obra e salvá-la com o código `ET00003_01a`, `ET00003_01b` e assim por diante

**Comment by ZeRodriguez** [comment]
@DaianaMaciel , qual o estado da tarefa?

**Comment by DaianaMaciel** [comment]
tarefa concluída, @ZeRodriguez ! :)

**Comment by ZeRodriguez** [comment]
Valeu @DaianaMaciel !
