### ISSUE TITLE
Verificar e documentar problemas de instalação do Copy

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#14]
Documentar os primeiros passos que um novo usuário do Copy deve seguir para ter acesso aos documentos da pesquisa. Documentar tanto o uso local quanto via web. Pedir ajuda (por aqui mesmo) a @ZeRodriguez e @SimeiFerreira.

**Comment by ZeRodriguez** [comment]
@drakoor, após o procedimento feito na reunião de hoje, se ainda houver dúvidas, por favor, as liste aqui.

**Comment by ZeRodriguez** [comment]
@msampaio, essa documentação será feita aqui mesmo? Como um comentário? Seria só texto ou é necessário inserção de imagens?

**Comment by msampaio** [comment]
A documentação será feita no manual. Criei um usuário para você na página do Genos para você poder editar o manual.

**Comment by ZeRodriguez** [comment]
Já vi @msampaio.

**Comment by msampaio** [comment]
@drakoor, por favor finalize essa tarefa. Estamos com um mês de atraso nela.

**Comment by drakoor** [comment]
@msampaio, já fiz a publicação a publicação na página do Genos.
