### ISSUE TITLE
Implementar algoritmo de redução de contornos de Morris 1993

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#140]
Implementar os algoritmos de Redução de Robert Morris (1993). Usar o próprio repositório do GitHub para guardar os arquivos.
O artigo de Morris está disponível no Mendeley e diretório Bibliografia, no Copy.

Ver módulo `reducaoContornos.morris_algoritmo_2_1`.

**Comment by msampaio** [comment]
@azevedospider, quando implementei o MusiContour eu criei alguns testes funcionais para ajudar na implementação dos algoritmos. Veja os testes que criei para o algoritmo de Morris em https://github.com/GenosResearchGroup/MusiContour/blob/master/tests/test_contour.py#L204-L211

**Comment by ghost** [comment]
certo

Em 4 de dezembro de 2013 10:51, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> @azevedospider https://github.com/azevedospider, quando implementei o
> MusiContour eu criei alguns testes funcionais para ajudar na implementação
> dos algoritmos. Veja os testes que criei para o algoritmo de Morris em
> https://github.com/GenosResearchGroup/MusiContour/blob/master/tests/test_contour.py#L204-L211
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/140#issuecomment-29805781
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
@azevedospider,
Gostei da sua implementação do algoritmo. Fiz alguns comentários pontuais em seu commit. Recomendo que insira a documentação que você fez no arquivo txt no próprio código. Recomendo também que use alguma [extensão da PEP8 para Eclipse](http://stackoverflow.com/questions/399956/how-to-integrate-pep8-py-in-eclipse) para ver o estilo do código.
Renomeei os seus arquivos e criei um branch `oldMorris` com os seus arquivos de versões do algoritmo (Vide [handbook do Genos](http://genosmus.com/handbook/git/) caso não esteja habituado com o Git branch).

**Comment by msampaio** [comment]
@azevedospider, outra dica. No final do nome do commit coloque algo como "solve part of #140". Isso irá registrar todos os commit ao issue aberto. Vide [github 2.0](https://github.com/blog/831-issues-2-0-the-next-generation)

**Comment by msampaio** [comment]
@azevedospider, estou no aguardo da sua resolução dos problemas indicados nos commit 109cf256f6690b79f256cf3fea45b3053f9b98b3 e 13f57a91db8328fb84d266ceb515fd8e0e482d23 para poder fechar essa tarefa.

**Comment by msampaio** [comment]
@azevedospider, eu criei testes funcionais para as etapas 1 e 2 do algoritmo que você implementou. Para rodá-los basta rodar `make` no diretório 'danilo'.

**Comment by ghost** [comment]
certo

Em 15 de dezembro de 2013 18:47, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> @azevedospider https://github.com/azevedospider, eu criei testes
> funcionais para as etapas 1 e 2 do algoritmo que você implementou. Para
> rodá-los basta rodar make no diretório 'danilo'.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/140#issuecomment-30622504
> .

## 

Danilo Azevedo Santos
Técnico em Automação e Controle e Industrial, Instituto Federal da Bahia.
Bacharelado em Ciência da Computação, Universidade Federal da Bahia.
TEL. (71) 33863619/ 82869358 /92802927
E-mail: azevedospider@dcc.ufba.br \ nhasese@hotmail.com
Meu_Currículohttps://docs.google.com/document/d/1lReYzq1hg1Kg9e6_gHsfrUZMkwAzGjB2_NOcXcNEoxU/edit

**Comment by msampaio** [comment]
@azevedospider, estou no aguardo das correções que indiquei no commit 109cf256f6690b79f256cf3fea45b3053f9b98b3 para finalizar esta tarefa.

**Comment by msampaio** [comment]
@azevedospider, algum problema para fechar essa tarefa? Conforme combinamos estou aguardando o fechamento até amanhá.
