### ISSUE TITLE
Elaborar resumo com conceitos e metodologia de análise de agrupamentos

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#141]
A tarefa consiste em ver a literatura de análise de agrupamentos e coletar conceitos e metodologia para aplicarmos ao estudo de flauta solo.
Guardar resumo no Copy, em Produção

**Comment by SaraFadigas** [comment]
Coloquei na pasta Bibliografia o livro de estatística básica e alguns artigos que citei no resumo. O resumo ainda não está terminado, mas ficará pronto até o fim do dia.

**Comment by msampaio** [comment]
@SaraFadigas, você colocou o resumo na pasta Produção?

**Comment by SaraFadigas** [comment]
Estive sem internet aqui em feira, mas já foi regularizado.
Já está na pasta.
