### ISSUE TITLE
Indicar próximas fontes a transcrever

### ISSUE THREAD

**Issue by ZeRodriguez** [msampaio/flauta-solo#142]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste na preparação das obras definidas para serem transcritas.
- Escolher a fonte que será utilizada de cada uma das obras
- Baixar o `pdf`  da fonte escolhida na pasta `Fontes`, no Copy
- Anotar o `pdf` indicando o código de cada obra e ou movimento, ex.:

`Obra 1 Movimento 1`
![sem ttulo](https://f.cloud.github.com/assets/4490953/1681946/e1927e4a-5d9e-11e3-9521-b283dbd2330d.png)

`Obra 1 Movimento 2`
![sem ttulo1](https://f.cloud.github.com/assets/4490953/1681949/f5d9b92c-5d9e-11e3-93ac-c9810c75cb27.png)

`Obra 35, Obra 36, Obra 37`
![sem ttulo2](https://f.cloud.github.com/assets/4490953/1681955/1181d9e8-5d9f-11e3-9689-dbbab5765707.png)
### Importante

Após concluir as anotações, salvar os arquivos acrescentando `versão anotada` dentro da pasta `Processadas` que se encontra na pasta `Fontes`

**Comment by MarinaMonroy** [comment]
Ok @ZeRodriguez. Vou começar agora.

**Comment by MarinaMonroy** [comment]
Já fiz os passos 1 e 2 de:

24 Country Dances for the Year 1803 (Various)
204 Favourite Country Dances (Various)
24 Favorite Country Dances, Hornpipes and Reels (Various)
A Select Collection of Airs, Jigs, Marches and Reels (Various)
A Selection of Scotch, English, Irish and Foreign Airs (Aird, James)

**Comment by msampaio** [comment]
Ótimo. @luanpiano poderá ajudar a fazer o passo 2 do que você precisar. Basta dividir com ele.

**Comment by MarinaMonroy** [comment]
24 Favorite Country Dances, Hornpipes and Reels (Various) devidamente anotada e salva com o nome IMSLP254884-PMLP413073-Bland_Weller24_1803 anotada

Vale observar que as obras estão situadas 2 por página em divisão vertical. A ordem nas páginas no documento não representa a ordem original do livro, logo minha marcação não coincide com o n. da obra indicado pelo autor. O arquivo está faltando os ns. 9,10,11 e 12, logo são 20 e não 24 obras sinalizadas no arquivo.

@msampaio essa tarefa está sob controle, a priori não necessito de auxílio, obrigada @luanpiano

**Comment by MarinaMonroy** [comment]
A Select Collection of Airs, Jigs, Marches and Reels (Various) devidamente salva com o nome IMSLP98166-PMLP201811-select_collection_jiggs_marches_1784 anotada

Vale observar que são 117 obras e nem sempre coloquei a anotação no mesmo lugar pois acabaria cobrindo alguma parte da partitura. Algumas páginas contém falhas na tinta de impressão mas é possível discernir o conteúdo. 
Problema de leitura na O29 e possível dificuldade na O40, O86,O87,O96 por conta de cortes no escaneamento.

**Comment by luanpiano** [comment]
Ok @MarinaMonroy, precisando estou por aqui.

**Comment by msampaio** [comment]
@ZeRodriguez, pode começar a delegar essas obras dos pdf já anotados.

**Comment by ZeRodriguez** [comment]
@msampaio , começarei pelo `IMSLP254884-PMLP413073-Bland_Weller24_1803 anotada`, que possui apenas 10 pequenas obras. Mas antes de delegar as transcrições, gostaria de saber como ficaria o código para salvar os arquivos, para que eu possa colocar nas instruções.
Usaríamos apenas a numeração que segue IMSLP? Ficando `IF254884_01` e assim por diante?

**Comment by msampaio** [comment]
Exato.

**Comment by MarinaMonroy** [comment]
São 20 obras @ZeRodriguez !

**Comment by ZeRodriguez** [comment]
Verdade! =D

**Comment by msampaio** [comment]
@MarinaMonroy e @ZeRodriguez, esta tarefa já foi concluída?

**Comment by ZeRodriguez** [comment]
@msampaio , temos obras suficientes para trabalharmos até o fim de janeiro. Mas pensei que essa tarefa devesse ficar em aberto, para que @MarinaMonroy me apontasse mais obras assim que as atuais fossem concluídas.

**Comment by msampaio** [comment]
Ótimo, @ZeRodriguez. Prefiro que tenhamos tarefas menores e específicas. Quando tiver que definir uma nova leva de partituras você abre uma nova tarefa.

**Comment by msampaio** [comment]
@MarinaMonroy, pode definir as obras a serem transcritas até o final da pesquisa. Foque em obras de compositores, como as 12 fantasias de Telemann. Se houver coleções ou métodos, deixe-os para o fim. Assim que tiver a lista ordenada de todas as obras a serem transcritas, pode fechar essa tarefa.

**Comment by MarinaMonroy** [comment]
Ok! Colocarei a ordem de prioridade na tarefa
