### ISSUE TITLE
Fazer transcrição diplomática de EXTRA0001a - Fantasia de Telemann n.1 mov.1

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#15]
Fazer transcrição diplomática da partitura "Fantasia in A for solo flute No.1", mov.1, de Telemann, registrada no sistema no documento `EXTRA0001a`, na pasta `Fontes`.
Verificar instruções sobre pastas no [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/).
Em caso de dúvidas perguntar por aqui mesmo.

**Comment by ZeRodriguez** [comment]
@DaianaMaciel, alguma dificuldade com a tarefa. Qualquer dúvida pode me procurar tanto na escola, quanto por aqui mesmo.
