### ISSUE TITLE
Escrever Resenha de Beran et al 1999

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#157]
Elaborar a resenha do artigo abaixo. Coletar informações para seguir com o trabalho de estatística na análise musical

Beran, Jan, and Guerino Mazzola. 1999. “Analyzing Musical Structure and Performance — A Statistical Approach.” Statistical Science 14 (1): 47–79. http://projecteuclid.org/euclid.ss/1009211806.

**Comment by msampaio** [comment]
@SaraFadigas, essa tarefa está concluída?

**Comment by SaraFadigas** [comment]
tarefa concluida. vou postar o arquivo no copy.
Sara

**Comment by SaraFadigas** [comment]
o arquivo já está no copy
