### ISSUE TITLE
Fazer transcrição diplomática de EXTRA0001a - Fantasia de Telemann n.1 mov.2

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#16]
Fazer transcrição diplomática da partitura "Fantasia in A for solo flute No.1", mov. 2, de Telemann, registrada no sistema no documento `EXTRA0001b`, na pasta `Fontes`.
Verificar instruções sobre pastas no [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/).
Em caso de dúvidas perguntar por aqui mesmo.

**Comment by ZeRodriguez** [comment]
@Hugo11, alguma dificuldade com a tarefa? Qualquer espécie de dúvida, pode me procurar tanto por aqui quanto lá na escola. Abraço!

**Comment by msampaio** [comment]
@Hugo11, qual o estado desta tarefa? Dependo da conclusão dela para fechar a tarefa #43.

**Comment by msampaio** [comment]
Atenção ao novo código de identificação. Vide tarefas #12 e #50.

**Comment by msampaio** [comment]
Atribuindo tarefa a @menahemhein.

**Comment by menahemhein** [comment]
Professor, vi o novo código de identificação, mas não acho as partituras na fonte, será que estou procurando errado?

**Comment by msampaio** [comment]
@menahemhein, procure por O1M2 na versāo anotada da fonte.

**Comment by menahemhein** [comment]
De partitura na fonte só vejo uma que tá bem difícil de enxergar, pode ser nela ? já fui no imslp pra ver se tinha aquelas partituras que tinha no copy mas só acho a mesma que está no copy que é a EF00001.

**Comment by ZeRodriguez** [comment]
@menahemhein, esse é o arquivo fonte:

`EF00001-Telemann - Fantasies flute (with facsimile - Musica Rara) anotada`

Este arquivo contem todas as 12 fantasias. Primeiro, tem os facsimilares de uma fonte única. Se você for descendo as páginas do `.pdf`, verá que a partir da página 18, como mostra a figura, começa as versões usadas nas transcrições.
![sem ttulo](https://f.cloud.github.com/assets/4490953/1041913/d0b9a0ca-0fde-11e3-858c-4f848171d0be.png)

**Comment by menahemhein** [comment]
Concluída !

**Comment by ZeRodriguez** [comment]
Valeu @menahemhein
