### ISSUE TITLE
Verificar fórmula de compasso em IF111786_133

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#162]
O fragmento IF111786_133 (transcrito na tarefa #131) não tem fórmula de compasso e por isso não pode ser processado pelo MusiAnalysis. Verificar se há fórmula de compasso na fonte original. Caso tenha, pedir para @DaianaMaciel corrigir. Caso contrário, perguntar a @robattolucas se podemos inserir a fórmula de compasso. Ela é necessária para o processamento do software.

**Comment by robattolucas** [comment]
Se o softer necesita da formula de compasso, não vejo problema em inserir.
O importante é lembrarmos depois (no processamento das informações) que
esta formula de compasso  na verdade "não existe".

**Comment by msampaio** [comment]
@DaianaMaciel, por favor insira a fórmula de compasso no arquivo.

**Comment by ZeRodriguez** [comment]
@msampaio , o arquivo em questão, como mostra a imagem, possui fórmulas de compassos diferentes. O problema já foi resolvido?
![sem ttulo1](https://f.cloud.github.com/assets/4490953/2256395/78cdb098-9e06-11e3-8f0a-1ec358e26954.png)

**Comment by msampaio** [comment]
@ZeRodriguez, O problema é com o primeiro compasso.

**Comment by DaianaMaciel** [comment]
ok, vou corrigir.No arquivo, a fórmula de compasso só aparece no 2º . Algum problema colocar no primeiro?

**Comment by msampaio** [comment]
@DaianaMaciel, A fórmula do primeiro compasso parece ser algo como 7/4. Certamente não é 9/16. Acho bom perguntar a @robattolucas.

**Comment by robattolucas** [comment]
Por favor, me envie o exemplo musical para eu poder avaliar.

Em 25 de fevereiro de 2014 14:52, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

**Comment by robattolucas** [comment]
Desculpem, é o exemplo 133 , certo? O início ("1er Trait - sem fórmula de
compasso) é um 6/4 com anacruze de colcheia.

Em 26 de fevereiro de 2014 10:35, Lucas Robatto
robattolucas@gmail.comescreveu:

**Comment by DaianaMaciel** [comment]
ok.
