### ISSUE TITLE
Cadastrar referências de estatística no Mendeley

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#163]
Cadastrar as entradas seguintes no Mendeley. Ver o pdf na pasta bibliografia, no Copy e fazer busca na internet para encontrar os dados das referências. O worldcat.org é um bom serviço para encontrar livros. Renomear os arquivos na pasta do Copy para manter padrão (autor - ano - título)

Atenção aos detalhes para fazer o trabalho uma vez só.
- Clustering analysis of SAGE data using a Poisson approach
- Cluster analysis and display of genome-wide expression patterns
- STATE OF THE ART REPORT AUDIO- BASED MUSIC STRUCTURE ANALYSIS
- Separation of Mixed Audio Sources by Independent Subspace Analysis
- Baumgartner2000-comparison_of_two_exploratory_data_analysis_methods_for_fMRI_fuzzy_clustering_vs._principal_component_an
- Kiang2001-Extending_the_Kohonen_self-organizing_map_networks_for_clustering_analysis

**Comment by menahemhein** [comment]
Feito !
Tive um pouco dificuldade no tipo de texto que era cada um, mas acredito que fiz certo.
