### ISSUE TITLE
Escrever resenha de Beran 2004

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#164]
Focar nas contribuições que o texto pode trazer à pesquisa, especialmente o capítulo sobre agrupamentos. Disponível no Copy/Bibliografia.

Beran, Jan. 2004. Statistics in Musicology. Boca Raton, FL: Chapman & Hall/CRC.

**Comment by SaraFadigas** [comment]
ok

Date: Mon, 3 Mar 2014 02:38:30 -0800

**Comment by SaraFadigas** [comment]
O senhor quer que eu faça uma resenha pra cada capitulo em separado? começo pelo capitulo que fala sobre agrupamentos?

**Comment by msampaio** [comment]
Pode fazer um texto geral e um comentário para cada capítulo. Lembre-se de tentar relacionar cada capítulo com nosso trabalho na pesquisa.

**Comment by msampaio** [comment]
@SaraFadigas, essa tarefa está concluída?

**Comment by SaraFadigas** [comment]
está. vou colocar o arquivo no copy.

**Comment by SaraFadigas** [comment]
alias, essa ainda falta terminar. a que está concluida é a do beran 1999 do artigo.
