### ISSUE TITLE
Redução de contornos na análise musical

### ISSUE THREAD

**Issue by ZeRodriguez** [msampaio/flauta-solo#170]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas
- Levantar como a operação de redução de contornos foi utilizada na análise musical
- Ver Morris, Schultz e Bor.

**Comment by SimeiFerreira** [comment]
@msampaio, eu passei o olho na sua tese para ter uma melhor ideia da redução de contornos e pelo que pude compreender, a redução de contornos de Bor difere das de Morris e Schultz por trabalhar com janelas de três e cinco elementos ao invés de retornar contornos primos. Me corrija se eu estiver errado, mas me parece que a redução de Bor não apresenta as inconsistências que você encontrou nas reduções de Morris e Schultz, daí o pedido para dar maior enfoque na redução de Bor, é por aí?

**Comment by msampaio** [comment]
@SimeiFerreira, não é por aí.
O objetivo da tarefa é mapear o uso de redução de contornos na análise musical. Quem, além de mim, usou as operações de redução de Morris, Schultz e Bor para analisar música? Como exatamente essas operações foram utilizadas? Alguém falou em vantagem ou desvantagem de usar redução de contornos para analisar música?
Para realizar o trabalho você precisa:
1. listar todos os trabalhos que citaram os textos em que Morris, Schultz e Bor publicaram as operações. (começar vendo Google Scholar)
2. ver quais desses trabalhos envolvem análise musical. 
3. verificar os possíveis ganhos do uso de redução de contornos em análise.
