### ISSUE TITLE
Fazer transcrição diplomática de IF92186 O1M1 à IF92186 O3M5

### ISSUE THREAD

**Issue by MarinaMonroy** [msampaio/flauta-solo#178]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas
- As obras se encontram no arquivo `IMSLP92186-PMLP189888-gs01-47m_tromlitz_6_fl_son_anotada.pdf` na pasta `Fontes - Processadas`
- Fazer a transcrição da obra e salvá-la com o código `IF92186_01a`, `IF93068_01b` e assim por diante

**Comment by DaianaMaciel** [comment]
@MarinaMonroy  , @msampaio  Tarefa concluída!
