### ISSUE TITLE
Inserir partitura de fantasias de Telemann no IMSLP

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#181]
@MarinaMonroy, preciso que você insira as partituras das fantasias de Telemann que usamos na base de dados do IMSLP.
Para isso é necessário criar uma conta e seguir as instruções para inclusão de material.

**Comment by MarinaMonroy** [comment]
ok!

**Comment by msampaio** [comment]
@MarinaMonroy, cole aqui o link para a entrada que você criou no IMSLP.

**Comment by MarinaMonroy** [comment]
Ainda não está disponível.  Eu passei por quarentena anti-span para postar e agora to aguardando liberarem o material que postei

Enviado por Samsung Mobile

-------- Mensagem original --------
De : Marcos da Silva Sampaio notifications@github.com 
Data: 21/04/2014  21h49  (GMT-03:00) 
Para: GenosResearchGroup/FlautaSolo FlautaSolo@noreply.github.com 
Cc: MarinaMonroy mamacostapenna@hotmail.com 
Assunto: Re: [FlautaSolo] Inserir partitura de fantasias de Telemann no IMSLP (#181) 

@MarinaMonroy, cole aqui o link para a entrada que você criou no IMSLP.

**Comment by msampaio** [comment]
Disponível em:
http://imslp.org/wiki/12_Fantasias_for_Flute_without_Bass,_TWV_40:2-13_(Telemann,_Georg_Philipp)
http://imslp.org/wiki/Special:ImagefromIndex/322698
