### ISSUE TITLE
Fazer transcrição diplomática de IF166083

### ISSUE THREAD

**Issue by MarinaMonroy** [msampaio/flauta-solo#183]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas
- As obras se encontram no arquivo `IMSLP166083-PMLP296187-Berbiguier_-_6_Grandes_solos_Fl_IArch_anotada.pdf`, na pasta `Fontes-Processadas`
- Fazer a transcrição da obra e salvá-la com o código `IF166083_1`, `IF166083_2` e assim por diante

**Comment by DaianaMaciel** [comment]
@MarinaMonroy , @msampaio   desculpa o atraso da tarefa....houve um probleminha com meu notbook, mas hj ainda termino a tarefa e faço o upload.

**Comment by MarinaMonroy** [comment]
Ok! Tudo bem

Enviado por Samsung Mobile

-------- Mensagem original --------
De : Daiana Maciel notifications@github.com 
Data: 05/05/2014  1h01  (GMT-03:00) 
Para: GenosResearchGroup/FlautaSolo FlautaSolo@noreply.github.com 
Cc: MarinaMonroy mamacostapenna@hotmail.com 
Assunto: Re: [FlautaSolo] Fazer transcrição diplomática de IF166083 (#183) 

@MarinaMonroy , @msampaio   desculpa o atraso da tarefa....houve um probleminha com meu notbook, mas hj ainda termino a tarefa e faço o upload.

**Comment by DaianaMaciel** [comment]
Tarefa concluída.
