### ISSUE TITLE
Inserir ornamentos em IF139886 O3 e IF13886 O4 

### ISSUE THREAD

**Issue by MarinaMonroy** [msampaio/flauta-solo#193]
Essa tarefa é ligada à tarefa #185. @SaraFadigas  realizou as transcrições em Sibelius e estas encontram-se salvas em .xml. 
A tarefa consiste em comparar as transcrições com os originais e inserir no Finale os ornamentos que faltam.

**Comment by DaianaMaciel** [comment]
@MarinaMonroy , Tarefa concluída! 
Obs.: precisei fazer um arquivo finale das respectivas tarefas , para após a inclusão dos ornamentos, salvar em XML .
