### ISSUE TITLE
Cadastrar entradas bibliográficas no Mendeley

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#2]
Cadastrar todas as entradas bibliográficas presentes nos subprojetos da pesquisa no Mendeley.
1. Instalar a versão Desktop do Mendeley no computador
2. Cadastrar individualmente as entradas (file/Add Entry Manually)
3. Verificar se todos os campos necessários estão preenchidos
4. Arrastar para a pasta Solo Flute (vide círculo na imagem)
5. Sincronizar com servidor (vide círculo na imagem)

Caso tenha dificuldade de encontrar informações sobre os livros, busque pelo título no [WorldCat](http://www.worldcat.org/)

![screen shot 2013-08-05 at 07 42 11](https://f.cloud.github.com/assets/1006488/909363/a5450bac-fdbc-11e2-91d0-8a1d7a889b95.png)
### Bibliografia para cadastrar

BLUME. F. Renaissance and Baroque Music. Londres: Faber & Faber, 1967

MEYER, L. B. Style and Music. Chicago: University of Chicago Press, 1996.

RÓNAI, Laura. Em busca de um mundo perdido: métodos de flauta do Barroco ao Século XX. Rio de Janeiro: Topbooks, 2008.

ROSEN, Charles. The Classical Style: Haydn, Mozart, Beethoven. New York: W. W. Norton & Company, 1972.

TOFF, Nancy. The Flute Book. New York: Oxford University Press, 1996.

Bertissolo, Guilherme. 2013. Composição e Capoeira: dinâmicas do compor entre música e movimento. Tese de doutorado, Universidade Federal da Bahia, Salvador.

Farnell, Andy. 2010. Designing sound. Cambridge, MA/London: The MIT Press.

Lima, Paulo C. 1999. Ernst Widmer e o ensino de composição musical na Bahia. Salvador: COPENE Cultura e Arte Especial.

_____. 2012. Teoria e prática do compor I: diálogos de invenção e ensino. Salvador: EDUFBA.

Reynolds, Roger. 2002. Form and method: composing music. New York/London: Routledge. Editado por Stephen McAdams.

Traldi, César A. 2009. Percussão e Interatividade PRISMA: Um Modelo de Espaço Instrumento Auto-Organizado. Tese de doutorado, Universidade de Campinas, Campinas.

Winkler, Todd. 2001. Composing interactive music: techniques and ideas using Max. Cambridge/London: The MIT Press.

**Comment by menahemhein** [comment]
Professor acho os livros que você me passou pelo worldcat porém os dados dos livros estão diferentes destes que o Sr. me passou, você acha melhor eu colocar os daqui, ou os do worldcat?

**Comment by msampaio** [comment]
@menahemhein, no caso dessa lista acho melhor usar os dados que estão aqui.
PS: agora que temos três professores, quando quiser se referir a mim use esse código: `@msampaio`, como faço para me referir a você no início desse comentário.

**Comment by msampaio** [comment]
@menahemhein, vi que você inseriu algumas entradas no Mendeley. Observe na figura abaixo que você não deve usar pontos no final do título ou vírgulas demais no nome do autor.

![screen shot 2013-08-12 at 19 11 28](https://f.cloud.github.com/assets/1006488/951144/49e58e40-039c-11e3-8cfd-6dd0b48022e3.png)

**Comment by msampaio** [comment]
@menahemhein, o deadline desta tarefa é hoje. Ela está concluída?

**Comment by menahemhein** [comment]
Ok ! tirarei os pontos e vírgulas quanto o resto, tá terminado !

**Comment by msampaio** [comment]
@menahemhein, corrija os autores que estāo com os nomes em maiúsculas, como
ROSEN e BLUME. Procure sempre o nome completo do autor e nunca abrevie os
nomes, como F. Blume ou L. B. Meyer. Procure os nomes do meio desses autores.

**Comment by menahemhein** [comment]
Corrigido !

Grande abraço !

**Comment by menahemhein** [comment]
Corigido 

grande abraço !

**Comment by msampaio** [comment]
@menahemhein, ainda estou vendo nomes de autor em maiúsculas e abreviações de primeiro nome (vide imagem abaixo). Por favor faça uma verificação criteriosa de cada item. Coloque o nome do meio nos autores que você puder. Por exemplo, não há razão para abreviar Paulo Costa Lima como Paulo C. Lima.
![screen shot 2013-08-14 at 11 08 37](https://f.cloud.github.com/assets/1006488/962177/3eb46f00-04eb-11e3-93d8-82e90fcfbaac.png)

**Comment by menahemhein** [comment]
Professor eu atualizei esses nomes aqui, será que não é delay do mendeley? Falta só eu achar o nome de Leornad B meyer e Rosen Kenneth H, o resto tá tudo corrigido ! deve ser problema de atualização ou algo do tipo!

Grande abraço !

**Comment by msampaio** [comment]
Você clicou em Sync? O mendeley não tem delay.

![screen shot 2013-08-14 at 11 48 33](https://f.cloud.github.com/assets/1006488/962492/af345e2a-04f0-11e3-95ec-03749944e491.png)

**Comment by msampaio** [comment]
Bom trabalho, @menahemhein. Agora está funcionando ;-)
Vou fechar a tarefa. Deu para entender o processo de inserir bibliografia no Mendeley?

**Comment by menahemhein** [comment]
Com certeza, desculpa pelos pequenos erros, mas agora já tá tudo entendido
!

Grande abraço !
