### ISSUE TITLE
Inserir texto de Grier na pasta Bibliografia, no Copy

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#25]
Lucas, @menahemhein está organizando toda a bibliografia da pesquisa. Você pode inserir o texto do Grier na pasta Bibliografia, no Copy? Eu fiz um tutorial de como enviar documentos para o Copy e coloquei no link abaixo. Se tiver qualquer dúvida basta responder essa mensagem.

https://copy.com/I3gjaiv8i8RCPc1y

**Comment by msampaio** [comment]
@daniloabrahao, por favor ajude @robattolucas com esta tarefa.

**Comment by daniloabrahao** [comment]
@msampaio , desculpe a demora, eu só vi agora que você mencionou meu nome aqui e na outra tarefa. Este texto do Grier é um arquivo para ser inserido no Copy? 

@robattolucas, se você quiser me mandar mandar esse arquivo por e-mail eu posso fazer isso. 
De qualquer forma, descrevendo passo-a-passo, fica assim:

1º Fazer Log In no site do Copy;
2º Clicar em "Browse" no canto superior direito da tela;
3º Clicar em "Copy Folder";
4º À direita clicar na pasta compartilhada "Flauta Solo";
5º À direita, novamente, clicar com o botão direito sobre a pasta "Bibliografia" e selecionar a opção "Upload to 'Bibliografia'";
6º Selecionar o arquivo no seu computador e enviar;
7º Pronto. Dependendo do tamanho do arquivo, ele pode demorar um pouco para ser inserido.

**Comment by msampaio** [comment]
@daniloabrahao e @robattolucas, conforme informei na descrição desta tarefa, fiz um pequeno vídeo tutorial explicando como inserir o arquivo.

**Comment by msampaio** [comment]
@robattolucas, você pode enviar o arquivo do Grier para o @daniloabrahao inserir na pasta Bibliografia?

**Comment by daniloabrahao** [comment]
Na pasta `Bibliografia` existe o arquivo `Grier 1996 The Critical Editing of Music`. Não é o mesmo em questão aqui?

**Comment by robattolucas** [comment]
Aparentemente consegui colocar o arquivo Grier no Copy.

2013/9/1 Marcos da Silva Sampaio notifications@github.com
