### ISSUE TITLE
Elaborar ata da reunião de 08/08/2013

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#26]
Criar a ata da reunião de 08/08/2013.
@SimeiFerreira, por favor ajude Sara a colocar a ata na página correta.

**Comment by SaraFadigas** [comment]
@SimeiFerreira onde encontro o modelo de ata?

**Comment by msampaio** [comment]
@SaraFadigas, siga o modelo da ata de [25/07/2013](http://genosmus.com/2013/07/ata-da-reuniao-de-25072013/). Criei um usuário na página do Genos para você poder criar a ata.

**Comment by SimeiFerreira** [comment]
@SaraFadigas, coloquei na pasta "Tutoriais" do copy um vídeo que o Marcos havia me enviado que ensina passo a passo como fazer a ata e onde salvar.

**Comment by SaraFadigas** [comment]
Modificações concluidas.
