### ISSUE TITLE
Definir informações musicológicas das obras que devem ser guardadas

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#28]
@robattolucas, preciso que você e @daniloabrahao definam quais informações musicológicas deverāo ser salvas no software de análise. Por exemplo, nome do compositor , título da obra, nome do editor, número e nome do movimento, etc. Listem todos os dados já pensando em subcategorias como informações sobre o compositor, sobre a obra e sobre a ediçāo.
Preciso desses dados para seguir com a tarefa #27 e ter material para a apresentaçāo do protótipo do Projeto Total.
@daniloabrahao pode salvar essas informações na pasta Produçāo, no Copy.

**Comment by msampaio** [comment]
@robattolucas e @daniloabrahao, eu criei o arquivo 'Modelagem-Musicologia.txt' para inserir as informações levantadas nesta tarefa.

**Comment by robattolucas** [comment]
A definição destas informações vai ter qual impacto no softer?

É importante saber isto para decidir o que colocar.

A princípio, sugiro as seguintes informações:
- compositor
- datas de nascimento e morte do compositor
- nome da obra - título, subtítulo, nr. opus, outra classificação de
  coleção (BWV. KV, etc.)
- ano de composição ou publicação (edição/cópia da obra). Não havendo ano
  de composição, vai o ano da publicação
- fonte da obra (manuscrito, edição, cópia - detalhando a origem)
- número de movimentos (aqui será exigida eventualmente uma decisão
  "editorial" do grupo para decidir divisões "polêmicas")
- título de cada movimento - título/subtítulo (por ex. Menuetto/alllegro) -
  aqui é importante poder depois isolar o subtítulo (penso em uma busca por
  minuetos, por exemplo)

O que mais é importante inserir? Tonalidade? Nr de compassos? código do
IMSLP?

**Comment by msampaio** [comment]
@robattolucas, poderemos usar essas informações no futuro para filtrar dados. Por exemplo, comparar todas as obras de compositores nascidos em uma determinada cidade, ou todos os movimentos lentos de obras.
O software poderá extrair número de compassos e outras informações musicais diretamente da partitura de forma automática.
Veja se concorda com a definição que fiz no [arquivo](https://www.copy.com/browse/company-11103/Flauta%20Solo/Produ%C3%A7%C3%A3o/Modelagem-Musicologia.txt) do Copy.

**Comment by robattolucas** [comment]
ótimos tópicos! porém ainda vamos ter que refletir sobre a questão das
obras didáticas e coleções "anônimas" de obras. Para estas teríamos que
pensar em outras categorias, mas ainda não estou seguro sobre quais.
Acredito que estas questões somente surgirão com um caso concreto, e
gostria que decidissemos conjuntamente (uma reunião?).

Talvez devamos pensar neste momento somente nas obras "de concerto" , para
as quais os tópicos estão bastante adequados.

**Comment by msampaio** [comment]
@robattolucas, eu quero fazer uma modelagem de dados que também sirva às obras didáticas e coleções anônimas. Eu acho que seria bom definirmos um conjunto de fontes que envolva problemas diversos. Assim poderemos fazer essa modelagem já prevendo os problemas que podem ocorrer.
Para isso temos que:
1. Definir um conjunto de fontes
2. Transcrever essas fontes
3. Levantar as informações musicológicas sobre cada fonte, suas particularidades e tudo mais.

O que você acha?

**Comment by daniloabrahao** [comment]
Vou listar todos os dados que podem ser extraídos para que possamos definir quais informações utilizaremos.

**Comment by msampaio** [comment]
Ótimo, @daniloabrahao. Por favor faça isso no  [arquivo](https://www.copy.com/browse/company-11103/Flauta%20Solo/Produ%C3%A7%C3%A3o/Modelagem-Musicologia.txt) do Copy que mencionei em um dos comentários.

**Comment by daniloabrahao** [comment]
> Nome do compositor;
> Data de Nascimento do compositor;
> Data de morte do compositor;
> Nacionalidade do compositor;
> Instrumento principal do compositor [1];
> Tipo de obra mais composta pelo compositor [2];
> Título da obra;
> Subtítulo da obra;
> Estrutura da obra (sonata, partita, fantasia,...) [3];
> Número de opus;
> Código de classificação;
> Ano da composição;
> Ano da 1ª publicação;
> Ano da publicação da fonte;
> Fonte da Obra;
> Número dos movimentos;
> Título e subtítulos dos movimentos;
> Andamento principal do movimento
> Mudança de andamento por movimento (quais);
> Tonalidade principal [4];
> Modulações por movimento (quais) [4]; 
> Número de modulações por movimento [4].

@msampaio e @robattolucas , aqui estão as informações que podem ser extraídos. Eu adicionei alguns dados, mas acredito que possa estar faltando algum que seja importante (vou atualizando esse comentário assim que surgirem outros dados importantes). Abaixo, descrevo o motivo pelo qual adicionei certos dados:

[1] O fato de um compositor tocar um determinado instrumento pode ter alguma influência na obra;
[2] O fato de um compositor compor, por exemplo, muitas óperas pode fazer com que a obra, em questão, tenha absorvido algumas características operística;
[3] Fiz questão de separar o título da estrutura para evitar problemas em relação a obras que possuem título "artístico";
[4] Considero as questões da tonalidade e modulação importantes pelo fato de que o período compreendido entre 1710 a 1810 foi um período no qual a flauta era muito diferente da flauta moderna. Fato esse que influenciou diretamente na produção do repertório de flauta solo. Por exemplo, descobri hoje que, as tonalidades B maior, C menor, F menor e F# maior não foram utilizadas nas 12 Fantasia de Telemann por serem inviáveis na flauta de uma chave da época.

**Comment by daniloabrahao** [comment]
@msampaio, não sei como inserir essas informações no arquivo `Modelagem-Musicologia.txt`, por conta dos códigos que não sei usar. É só copiar e colar lá?

**Comment by msampaio** [comment]
@daniloabrahao, esqueça as linhas iniciais que têm códigos. Insira esses itens nas categorias que já coloquei lá.
Tire apenas uma dúvida. Você vê este arquivo como eu vejo (vide figura) ou você vê as linhas bagunçadas?

![screen shot 2013-08-23 at 11 36 52](https://f.cloud.github.com/assets/1006488/1016776/9d07baa4-0c01-11e3-9827-e2aa8c61405f.png)

**Comment by daniloabrahao** [comment]
@msampaio, eu só vejo isso:

![image](https://f.cloud.github.com/assets/4681458/1018561/5a3ba4f8-0c2c-11e3-90ad-2a123b943468.png)

**Comment by msampaio** [comment]
@daniloabrahao, por favor veja se agora o arquivo está correto.
Só um lembrete para mim mesmo: ver [EOF](http://ergoemacs.org/emacs/emacs_line_ending_char.html) no Emacs

**Comment by daniloabrahao** [comment]
Está correto, agora. Inserindo informações.

**Comment by daniloabrahao** [comment]
Informações inseridas, @msampaio.
O que é `opc`?

**Comment by msampaio** [comment]
Campos opcionais para preenchimento. Sāo os campos que poderemos deixar em branco se nāo encontrarmos a informaçāo. Por hora fecharei esta tarefa, mas dependemos de um entendimento maior de obras anônimas e métodos de estudo.
