### ISSUE TITLE
Documentar edição de vídeo

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#29]
Documentar no manual os procedimentos de edição de vídeos da pesquisa.
Informar que é preciso inserir informações como título, autor, grupo de pesquisa e link no vídeo e na descrição do vídeo, no Youtube. Ver comentários adicionais na tarefa #8.

**Comment by SaraFadigas** [comment]
Essa documentação eu faço também como Posto na página do Genos?

**Comment by msampaio** [comment]
Basta editar a página do [manual](http://genosmus.com/pesquisa/flauta-solo/manual/) e inserir as informações lá. Eu criei um usuário para você administrar a página do Genos. Basta entrar em http://genosmus.com/admin.

**Comment by SaraFadigas** [comment]
Coloco como um link dentro de Tarefas?

**Comment by msampaio** [comment]
@SaraFadigas, ao invés de fazer um link em Tarefas, coloque o texto da documentação diretamente lá, para termos uma página única de documentação.

**Comment by SaraFadigas** [comment]
A documentação já foi disponibilizada. O senhor pode conferir, @msampaio se existe alguma incoerência, ou algo que queira adicionar ou retirar.

**Comment by msampaio** [comment]
Ficou ótimo, @SaraFadigas. Eu apenas mudei o texto de lugar no [manual](http://genosmus.com/pesquisa/flauta-solo/manual/).
