### ISSUE TITLE
Escrever resenha de Oliveira 2001

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#3]
Escrever resenha de:

Oliveira, Alda de Jesus. 2001. “Música Na Escola Brasileira. Frequência de Elementos Musicais Em Canções Vernáculas Da Bahia Utilizando Análise Manual e Por Computador: Sugestões Para Aplicação Na Educação Musical.” Teses Na Educação Musical (2).

O objetivo da resenha é elaborar um texto enxuto com os objetivos, resultados, metodologia e possíveis aspectos interessantes da pesquisa.

Ver [exemplo de resenha](http://genosmus.com/2011/11/the-intersection-of-computational-analysis-and-music-manuscripts-a-new-model-for-bach-source-studies-of-the-21st-century-niitsuma-et-al-2009/) e registrar resenha como post. Apenas crie o post da resenha no site do Genos e avise para que eu organize uma categoria para ele. O texto de Alda está disponível em papel no GenosLab.

Documentar elaboração de resumos no manual.

**Comment by SimeiFerreira** [comment]
@msampaio, duas dúvidas sobre a tarefa:

1º Quando posso pegar esse texto em papel no GenosLab?
2º "Documentar elaboração de resumos no manual." Seria para fazer uma espécie de tutorial ensinando a elaborar resumos?

**Comment by msampaio** [comment]
@SimeiFerreira, respondendo às suas perguntas:
1. eu te entregarei o texto amanhã na reunião.
2. a documentação é apenas sobre onde escrever, onde salvar e as minhas dicas: texto enxuto com os objetivos, resultados, metodologia e possíveis aspectos interessantes da pesquisa.

**Comment by SimeiFerreira** [comment]
@msampaio, o resumo está pronto e publicado, aguardando apenas você atribuir uma categoria para ele. Busquei ser o mais sucinto possível. Onde encontro o manual para documentar a elaboração do resumo? Revirei a pasta do projeto no copy e o blog, mas fiquei meio perdido nessa parte.

Eis o link da postagem do resumo:

http://genosmus.com/?p=2727

**Comment by msampaio** [comment]
@SimeiFerreira, há um [template](http://genosmus.com/pesquisa/flauta-solo/manual/#Uso_de_templates) para tarefas gerais na pasta `Templates`, no Copy. Coloque sua resenha na pasta `Produção` usando o template `NovaTarefa.txt`.

**Comment by SimeiFerreira** [comment]
@msampaio, tive problemas para nomear a resenha como entendi que o template estava pedindo como mostra a imagem:

![resenha](https://f.cloud.github.com/assets/3719195/973182/a7f26356-061b-11e3-9f89-271f063e0d23.jpg)

Por conseguinte, coloquei um nome alternativo para o arquivo e disponibilizei na pasta "produção" do Copy, gostaria que você desse uma olhada e veja se eu fiz corretamente o preenchimento do modelo com os dados da tarefa.

**Comment by msampaio** [comment]
Bom trabalho, @SimeiFerreira. Você pode usar um nome como Resenha-TeseAldaOliveira.txt. Por favor renomeie o arquivo, remova o post que inseriu no site do genos com a resenha, e reinsira os comentários em código que tirou do texto. Esses códigos`#+` têm uma funçāo especial.

```
# -*- mode: org -*-
# Local IspellDict: brasileiro

#+title: Título da anotação
#+author: Nome do autor
#+keywords: Palavras-chave da tarefa. Por exemplo, musicologia
#+tags: Número da tarefa no GitHub, caso haja
```

**Comment by msampaio** [comment]
Bom texto, @SimeiFerreira. Você pegou o espírito da coisa.

**Comment by msampaio** [comment]
Apenas mais uma coisa. No título coloque "resenha do texto......., de Alda....". No autor coloque seu nome, pois essa resenha é sua.

**Comment by SimeiFerreira** [comment]
Obrigado @msampaio, já removi o post com a resenha do site do genos e fiz as modificações solicitadas no arquivo .txt, além de reenviá-lo à pasta "produção" do copy. Por gentileza, veja se está tudo de ok agora.

**Comment by msampaio** [comment]
Ficou ótimo! Fechando tarefa.
