### ISSUE TITLE
Documentar tarefa de expansão de uma partitura

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#30]
A tarefa é explicar no [manual](http://genosmus.com/pesquisa/flauta-solo/manual/) como uma partitura deve ser expandida. Ver procedimentos utilizados no [manual do projeto Um a Zero](http://genosmus.com/pesquisa/contornos/choro/guia/).
Por enquanto coloque algum sufixo no nome do arquivo para identificar a expansão.

**Comment by AlissonGSilva** [comment]
Pode ser "EXP"? Exemplo: `EXTRA0006aEXP` .

**Comment by msampaio** [comment]
Pode ser. A gente provavelmente vai mudar depois da conclusão da tarefa #12.

**Comment by AlissonGSilva** [comment]
Estou confuso com essa tarefa; sei o que explicar no manual, mas não sei onde devo postar precisamente, tem muita informação, não sei onde encaixar na pagina do Manual essa explicação. No manual da pesquisa dos choros tem lá "Processamento das canções" listadas, já no de Flauta solo não tem.
@SimeiFerreira você já fez isso?Pode me ajudar?

**Comment by msampaio** [comment]
@AlissonGSilva, insira a documentação [aqui](http://genosmus.com/pesquisa/flauta-solo/manual/#Expans%C3%A3o_de_repeti%C3%A7%C3%B5es)

**Comment by AlissonGSilva** [comment]
Marcos dê uma olhada lá.

**Comment by msampaio** [comment]
@AlissonGSilva, duas observações:
1. mencione que a extensão diz respeito a qualquer sinal de repetição além do ritornello, como _Dal segno_ e coda.
2. Nas instruções você misturou lista enumerada com lista não ordenada. Use apenas a enumerada.

**Comment by AlissonGSilva** [comment]
Pronto @msampaio, mais alguma observação?

**Comment by msampaio** [comment]
Está ótimo ;-)
