### ISSUE TITLE
Enumerar peças e movimentos de EXTRA0001 - Fantasias de Telemann

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#35]
@daniloabrahao, na tarefa #13 nós separamos os movimentos em arquivos diferentes e vimos que causou muita confusão. Conforme conversamos na [reunião de 20/08](http://genosmus.com/2013/08/ata-de-reuniao-de-20082013/), iremos usar apenas o arquivo com a fonte original e iremos identificar os movimentos diretamente no PDF. Identifiquei os movimentos das obras 1 e 2 de Telemann (vide figuras abaixo). Usei `O` para me referir à obra (fantasia 1, 2, 3, etc), e `M` para me referir ao movimento. Assim, gerei `O1M1`, `O1M2`, etc.
Salvei esta versão anotada do PDF como "EXTRA0001-Telemann - Fantasies flute (with facsimile - Musica Rara) anotada.pdf".

![screen shot 2013-08-23 at 10 32 42](https://f.cloud.github.com/assets/1006488/1016372/8bcf2816-0bf8-11e3-94c2-2fe90fa9c68c.png)

![screen shot 2013-08-23 at 10 32 55](https://f.cloud.github.com/assets/1006488/1016374/92dcfcdc-0bf8-11e3-862f-359005385382.png)

**Comment by msampaio** [comment]
@daniloabrahao, após concluir essa tarefa pode remover todos os arquivos que você criou na tarefa #13.

**Comment by daniloabrahao** [comment]
@ZeRodriguez, você sabe como escrever no arquivo `.pdf`?

**Comment by msampaio** [comment]
@daniloabrahao, tente um desses softwares:
http://www.foxitsoftware.com/Secure_PDF_Reader/
http://www.hongkiat.com/blog/free-pdf-annotation-tools/

**Comment by ZeRodriguez** [comment]
Editar o arquivo `.pdf`? Rapaz, sei não.

**Comment by daniloabrahao** [comment]
Descobri que o Adobe Reader 11.0 possui essa opção de anotação, já estou atualizando aqui.

**Comment by daniloabrahao** [comment]
@msampaio, percebi, depois da sua identificação, que nem todas as barras duplas da 12ª fantasia delimitam o fim de um movimento. Todavia, na página [http://en.wikipedia.org/wiki/12_Fantasias_for_Solo_Flute_(Telemann)], a Wikipédia considera todas as mudanças de andamento como movimentos. 

Outra coisa que notei foi que em algumas fantasias há uma mudança de andamento depois da barra do ritornello (exemplo abaixo). Considerei isso como uma mudança de movimento, mas agora não estou seguro disso.

![image](https://f.cloud.github.com/assets/4681458/1021001/dd624124-0cd7-11e3-8fc9-5a561ed19b3b.png)

Vou checar se há alguma dessas informações no aparato crítico.

Tarefa concluída.

**Comment by ZeRodriguez** [comment]
@danilo, a FANTASIA No. 12 foi editada por @AlissonGSilva na tarefa #38 . Nessa tarefa está listada todas as dúvidas e foi acordado que ela possui apenas 2 movimentos. A contagem dos compassos nos ajuda a chegar a essa conclusão. Seguindo por esse pensamento, a FANTASIA No. 6 que você colocou na imagem acima, está dividida corretamente. Valeu, bom trabalho! Estou fechando a tarefa!

**Comment by daniloabrahao** [comment]
Entendi, mas de qualquer forma acho que é válido checar o aparato crítico.

**Comment by msampaio** [comment]
@daniloabrahao, nesse caso dessa fonte específica das fantasias de Telemann eu observei que o novo movimento é acompanhado de reinício da contagem dos compassos. No entanto é bom checar isso no aparato crítico. Ficamos no aguardo.
