### ISSUE TITLE
Estudar e programar itens 1 e 3 do Tutorial de Python

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#44]
A tarefa consiste em:
1. Ler o texto [Whetting Your Appetite](http://docs.python.org/2/tutorial/appetite.html) para ter um estímulo para o estudo de Python
2. Ler e programar todos os códigos da [introdução ao Python](http://docs.python.org/2/tutorial/introduction.html) para ganhar prática na linguagem.

Criar um arquivo alisson02.py na pasta Code para salvar os códigos do item 2.

**Comment by AlissonGSilva** [comment]
Tudo certo Marcos, fiz tudo ali, bem simples esses exercícios, e já testei e ta rodando as funções. 

Tem uma linha só que já escrevi e reescrevi e ta quebrando o processo no meio; escrevi ela como uma "string" só pra você ver lá no arquivo.

```
preco = 99.50
tax = 14.67 / 100
print preco * tax
" print preco + _ 
round (_, 2)"
```

Essa linha que ta quebrando
`print preco + _`

**Comment by msampaio** [comment]
@AlissonGSilva, você precisa colar o texto da mensagem de erro aqui para que eu identifique o problema.
De qualquer forma insira a linha abaixo no início do arquivo para liberar os acentos:

```
# -*- coding: utf-8 -*-
```

Na linha que você inseriu há uma string (iniciada com aspas), mas você nāo faz nada com ela. Nāo guarda em variável, nāo imprime na tela...

Que esculhambaçāo é essa? :-)

```
baitol = 'danilo' + 'pepito'
```

**Comment by AlissonGSilva** [comment]
Ok Marcos, inseri o código pra liberar os acentos. Eu não usei acentos justamente pra ter não problemas, só "café" que deu errado, tinha esquecido.Já sabia desse problema desde o curso que fiz com você.

Eu pus as aspas depois, por que era essa linha que tava dando erro, ae deixei ela com aspas  pra o programa rodar até o final. Eu sei que essa função usa o ultimo resultado nesse `_` , mas não estou conseguindo ver onde está o problema na linha, deve ser algo bem besta.
O erro é esse:

```
Traceback (most recent call last):
  File "D:\Python27\alisson02.py", line 64, in <module>
    print preco + _
NameError: name '_' is not defined
```

Era uma brincadeira, tava programando e conversando com os caras, mas tirei para não gerar problemas. =)

```
 amiz = 'da + 'pe'
```

O resto ta tudo funcionando muito bem.

**Comment by msampaio** [comment]
@AlissonGSilva, vamos aproveitar esse problema para ver algumas coisas:
1. Conforme o [tutorial do python](http://docs.python.org/2/tutorial/introduction.html#numbers), o sinal `_` funciona no modo interativo: "In interactive mode, the last printed expression is assigned to the variable _". Remova então esse sinal do arquivo.
2. Há duas informações essenciais na mensagem de erro: o número da linha e o erro em si: `NameError: name '_' is not defined`. A primeira coisa que procurei foi o uso do sinal `_`.
3. As brincadeiras fazem parte :-)

Sinta-se à vontade para fazer funções e pequenos programas com essas informações que você já viu. Na próxima reunião irei atribuir um novo passo no estudo de Python.

**Comment by AlissonGSilva** [comment]
@msampaio  como você faz pra deixar o IDLE com o fundo preto? To me batendo com isso aqui, já mudei um monte de coisa e não funcionou pra mudar a cor pra preto; esse branco demais fica cansando a minha vista. =)

Só pra eu lembrar:
Digite o seguinte no interpretador:

```
>>> import math

>>> math.sqrt(16)
4.0
>>> math.exp(4)
54.598150033144236
>>> math.pow(5,3)
125.0
```

Fazendo isso você estará carregando o módulo de funções matemáticas de Python. Com isso estarão disponíveis diversas funções matemáticas pra você testar:

http://docs.python.org/2/library/math.html

http://www.joinville.udesc.br/portal/professores/alexandre/materiais/c3_minicurso.pdf

**Comment by msampaio** [comment]
@AlissonGSilva, não se preocupe em configurar o IDLE por enquanto. Em breve vamos usar uma IDE melhor

**Comment by msampaio** [comment]
@AlissonGSilva, você pode inserir esses lembretes diretamente no arquivo que está usando para estudar. Basta inserir como comentário ;-)
