### ISSUE TITLE
Definir duas obras (método e obra anônima) para preparar modelagem de dados

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#45]
@robattolucas, conforme conversamos ontem, preciso que você defina uma obra anônima e um método para flauta para podermos preparar a modelagem de dados e melhorar a codificação das fontes e transcrições (tarefa #12).
O objetivo é termos uma amostra variada dos tipos de material que podemos encontrar: composições com informação de autor (Fantasias de Telemann, por ex.), composições anônimas, estudos, métodos, etc.
Esta tarefa é pré-requisito para a conclusão da tarefa #28.

**Comment by robattolucas** [comment]
Oi Marcos,

Como exemplos de método, sugiro o Monzani (1801), o Tromilitz (1791) ou Op.
7 _L'art de Préluder_ (1719).

Para anônimo poderia ser o Elegant Extracts for the Flute or Violin (1794) .

Vamos ter alguns problemas interessantes aqui…
