### ISSUE TITLE
Modelar dados musicológicos

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#46]
Modelar os dados musicológicos para programar a estrutura mínima do programa (tarefa #27). Esta tarefa depende da conclusão das tarefas #12 e #28 e é pré-requisito para a preparação da amostra do "Projeto Total", a ser apresentado no início do semestre letivo 2013.2.
Realizar a tarefa no [arquivo](https://www.copy.com/browse/company-11103/Flauta%20Solo/Produ%C3%A7%C3%A3o/Modelagem-Musicologia.txt) do Copy

**Comment by msampaio** [comment]
Esta tarefa depende também do subprojeto IMSLP 34491 Monzani 1801 1, iniciado com a tarefa #48. A partir da realização deste subprojeto teremos insights de como organizar os dados musicológicos de métodos para instrumento.

**Comment by daniloabrahao** [comment]
Registrando o que conversei com @msampaio. Acho que talvez seja interessante adicionar duas categorias de informações a serem extraídas de cada peça trabalhada:
1. Para que tipo de flauta a peça foi composta? (Considerando que este foi um período no qual muitos tipos de flauta coexistiam, diversos números de chaves, materias, ...)
2. É uma peça original para flauta ou apenas uma transcrição ou arranjo para flauta?

Acredito serem dados muito relevantes, porém, é bem possível que não encontremos esse tipo de informação para a maioria das obras trabalhadas na pesquisa.

**Comment by msampaio** [comment]
@robattolucas, a informação sobre instrumento para o qual uma peça foi composta é um atributo de uma fonte ou de uma obra? Pensei que uma obra pode ser composta para um instrumento, mas ter uma fonte com uma transcrição para outro. @daniloabrahao propôs inserir este dado na modelagem de dados, mas não sei em que classe inserir (fonte ou obra).

**Comment by robattolucas** [comment]
A informação sobre o instrumento vai vir de fontes diversas, pois aqui
contamos com determinação do compositor, que pode ser mais ou menos
específica. No caso de determinações menos específicas é necessário um
estudo do contexto histórico específico para determinação do(s)
instrumento(s) específico(s).

**Comment by msampaio** [comment]
Entendo. Você acha viável incluirmos essa informação?

**Comment by robattolucas** [comment]
Se for possivel um "campo aberto" podemos incluir. Isto porque em certos
casos conseguiremos determinar facilmente o instrumento (indicações na
partitura, tessitura), em outros as músicas são destinadas a múltiplos
instrumentos através de indicações na partitura (flauta, ou oboé, ou flauta
doce, ou violino, por ex.), e em outros não há indicações na partitura
suficientes para determinar o instrumento. Estou chamando estes casos de
dúvida de "campo aberto".

**Comment by msampaio** [comment]
Ótimo. Essa é uma informação referente à obra ou à fonte?

**Comment by robattolucas** [comment]
A informação é referente a obra, pois a fonte pode ou não indicar
claramente o instrumento.

**Comment by msampaio** [comment]
Beleza, @robattolucas. Já implementei o instrumento como um atributo opcional de uma obra ;-)

**Comment by msampaio** [comment]
@robattolucas, @daniloabrahao e @ZeRodriguez, com base no que vocês viram no Monzani, vocês acham que é necessário inserir mais alguma informaçāo além das presentes no arquivo [Modelagem-musicologia.txt](https://www.copy.com/browse/company-11103/Flauta%20Solo/Produ%C3%A7%C3%A3o/Modelagem-Musicologia.txt), na pasta Produçāo, no Copy? Dependo apenas dessa informaçāo para fechar esta tarefa.

**Comment by robattolucas** [comment]
Eu acho que temos que simular algumas perguntas, e ai teremos como avaliar
o quanto as informações dão conta das respostas. Para isto acho que seria
interessante uma sessão "brain storm" . O que acham?

**Comment by msampaio** [comment]
Boa ideia, @robattolucas. Podemos iniciar pela internet? Criei o arquivo [QuestoesProjeto.txt](https://www.copy.com/browse/company-11103/Flauta%20Solo/Produ%C3%A7%C3%A3o/QuestoesProjeto.txt) na pasta Produção, no Copy para colocarmos nossas sugestões de perguntas. Criei a tarefa #78 para @SimeiFerreira ir organizando esse brainstorm.

**Comment by robattolucas** [comment]
Consegui ler o arquivo, mas não consegui acrescentar nada online, só
baixando.

**Comment by msampaio** [comment]
@robattolucas, então coloque suas questões aqui mesmo. Depois movemos para lá.

**Comment by robattolucas** [comment]
Ai vai uma 1a série de questões e outras idéias:
- Determinar se a "origem" do compositor e o "gênero" da obra influenciam
  parâmetros específicos das obras.

Para isto podemos dividir os autores pelos seguintes critérios:
a) origem geográfica (país/região)
b) foi flautista?
c) período de atuação
d) região (regiões) de atuação (Haendel era alemão, mas atuava na
Inglaterra, por ex.)
etc.

Parâmetros a serem investigados nas obras;
a) ambito utilizado
b) registro predominante (grave, médio ou agudo, ou o equilíbrio entre
estes)
c) tonalidades predominantes
d) formulas de compasso predominantes
e) andamentos predominantes
f) padrões ritmicos predominantes: fluxo uniforme de figuras do mesmo
valor, alternância simples (par) de valores (colcheia e 2 semicolcheias,
por ex.) , alternância complexa (impar - ritmos pontuados, por ex.)
etc.

"Gêneros"
a) obras maiores (em extensão)  com finalidade explicitamente didáticas
(acho difícil conseguirmos isolar obras "puramente" artísticas, é mais
fácil o contrário)
b) danças (declaradas nos títulos)
c) arias, canções, etc (obras de "inspiração" declaradamente vocal)
d) fragmentos didáticos
etc.

Poderíamos também tentar estabelecer alguns padrões ritmicos
característicos de danças (ou outros "tópicos", como marchas, etc) , e
buscar em obras "sem declaração" se estão presentes (nas Fantasias de
Telemann geralmente os últimos movs. são danças, mas o autor não declara
que dança é esta, por ex.).

Na verdade estou falando aqui de uma questão muito importante para a
musicologia que trata deste período, que é a questão "topical", levantada
por Leornard Ratner, que diz que no séc. XVIII havia uma compreensão de que
música era uma comunicação linguística (retórica), e que compositores
apresentavam "tópicos' ( ritmos de danças, tonalidades, instrumentos) que
eram compreendidos pelos ouvintes. Por ex., Bach quando musica o texto
"Deus é o Senhor Poderoso"(aria Grosser Herr da cantata de natal), utiliza
um trompete solo, tocando padrões de marcha (colheia e 2 semicolcheias), e
uma tonalidade "divina" (ré maior).

Esta questão topical foi a base de um trabalho que poderia servir de base
para boa parte de nossas perguntas:
Rhythmic Gesture in Mozart: Le Nozze di Figaro and Don Giovanni by Wye
Jamison Allanbrook

Não consegui ainda este livro (o qual estudei no doutorado), mas tenho
algum material desta autora. O que ela diz é que Mozart se utilizava de
ritmos de danças que seus ouvintes conheciam, Porém, Mozart criava
significados novos ao apresentar ritmos conhecidos em novos contextos (um
nobre cantando com ritmos de danças "baixas" -  uma afronta! por ex.).

Se acharem interessante, podemos partir de uma idéia como esta. Mais sobre
a autora:  http://en.wikipedia.org/wiki/Wye_Jamison_Allanbrook

**Comment by msampaio** [comment]
@SimeiFerreira, por favor mova os comentários de @robattolucas para o arquivo indicado, conforme tarefa #78.

**Comment by ZeRodriguez** [comment]
Acredito que as questões levantadas por Lucas são fundamentais. Em relação ao Monzani, a única coisa que me intriga é a forma de escrita, tudo em um compasso só.

**Comment by SimeiFerreira** [comment]
Feito, comentários movidos na íntegra.

**Comment by msampaio** [comment]
@robattolucas, eu tenho uma dúvida. O que devemos chamar de fonte? Um documento completo do IMSLP, como as Fantasias de Telemann, ou cada composição individualmente? Eu estou modelando o sistema conforme o desenho abaixo. Estou admitindo que a partitura referente a uma obra é uma fonte, independente de fazer parte de uma coleção maior. Estou correto?

![sketchclass-diagram](https://f.cloud.github.com/assets/1006488/1372703/5173e508-3a56-11e3-8462-2bd24d61b700.png)

Nesta modelagem:
1. Um compositor pode criar várias composições.
2. Estas composições podem existir em diferentes fontes.
3. Essas fontes podem pertencer a diferentes documentos IMSLP.
4. Estes documentos podem ser coleções de fontes.
5. A fonte pode conter múltiplos movimentos.

**Comment by robattolucas** [comment]
Oi Marcos, tradicionalmente fonte é o documento físico (suporte) em que uma
determinada informação nos é transmitida. Geralmente é um documento de
arquivo ou publicação que possui algum tipo de integridade física (papeis
encadernados, costurados ou reunidos em algum invólucro). Geralmente são
livros, cadernos, folhas de papel costuradas ou agrupadas em maços (como lá
no Arquivo Público do Estado), etc. O importante é nomear (classificar) o
objeto (suporte) que contem a informação, para que se possa localizar
primeiramente o objeto, e depois as informações que  ele contem.

Neste sentido, cada documento do IMSLP é uma fonte, e cada fonte pode
conter várias obras diferentes (as fantasias de Telemann estão em uma fonte
única). Lá uma grade de uma sinfonia é uma fonte, e cada parte cavada outra
fonte. A rigor, a relação direta do compositor com a fonte não é
necessária, quer dizer, uma fonte pode conter obras de diversos
compositores, e uma obra pode estar "repartida" em diversas fontes (cada
movimento de uma sinfonia em uma fonte diferente, em arquivos diferentes,
ou uma obra camerística sem grade, por ex.).

Vale reforçar que este classificação "tradicional" tem por objetivo
principal propiciar a localização física da informação (que
arquivo/biblioteca, e em que documento lá), e - a depender da finalidade
pretendida - pode-se adotar outro tipo de código de localização.

Vc criou um "sub-sistema" de localização de informações quando trabalhamos
com o TSJB. A partir de um código de fonte já pré-estabelecido pelo APE
(cada maço), fragmentamos esta unidade de informação em "documentos"
(unidades administrativas separadas por data e autoria). Porem, o código
que vc desenvolveu retinha ainda a localização de cada fonte "maior"
(partia de cada maço do APE), e detalhava mais ainda a localização de cada
unidade de informação "dentro"da fonte que a contem (nr da folha, da
página, frente, verso, etc), além de descrever a natureza da fonte "maior"
(livro caixa, folhas soltas, caderno de folhas costuradas, etc).

O importante é definir qual a nossa necessidade de recuperação da
informação. Necessitamos da integridade da obra, do suporte que a contem,
da relação com compositor? O que?

**Comment by msampaio** [comment]
@robattolucas,
Pelas suas informações acredito que estou pensando corretamente. Eu refiz o esquema para poder tirar minhas dúvidas.

![sketchclass-diagram](https://f.cloud.github.com/assets/1006488/1384100/ee449cc2-3b48-11e3-922d-cd2b22dc7012.png)
1. Quero saber se o pensamento seguinte está correto. O objeto X é a obra que encontramos dentro de uma fonte (partitura, caderno de partituras, etc.). O objeto Composição é apenas uma abstração. É o objeto para o qual todas as fontes de uma obra convergem. Por exemplo, o IMSLP é organizado em composições, e em alguns casos, uma composição dispõe de diversas fontes. Neste modelo, o objeto X irá conter todas as informações musicais (a partitura em si), e relacionadas à fonte (informações sobre editora, editor). O objeto Composição irá conter todas as informações sobre aquela obra (compositor, ano da composição, etc.)
2. Caso o pensamento esteja correto, qual nome posso dar ao objeto X?

**Comment by robattolucas** [comment]
Acho importante definirmos antes as nossas necessidades, que ainda não
entendi direito, para depois pensarmos no estabelecimento de procedimentos.
Mas, pelo que entendi, vc necessita de algumas unidades de informação
(“objetos”) distintas:

*
*

_X.   *_Arquivo IMSLP*: cada arquivo pdf disponibilizado pelo IMSLP com
código próprio – este arquivo pode conter uma obra completa com vários
movimentos, uma coleção de diversas obras (de um mesmo ou de variados
compositores), ou uma parte de uma obra (um movimento, por exemplo)

_Y.Obra:_  composição (texto musical) com um ou mais movimentos,
constituído de um ou mais _X. Arquivo IMSLP_, e com “unidade” autoral
(normalmente um compositor agregando vários movimentos sob um só título ou
nr de opus, em oposição a uma coleção com várias obras autônomas de um ou
mais compositores)

_Z.__Movimento_ (segmento de obra) – necessariamente uma segmentação de _Y.
Obra_ - um _X. Arquivos IMSLP_ ou parte dele – temos que pensar bem se esta
segmentação deve/pode ser complementada por “sub-segmentações” (seções
formais, motivos, etc)

Destas unidades retiramos as seguintes informações  - ou agregamos
informações a elas:

a._Informações IMSLP *(retiradas): disponíveis em cada *X. Arquivo IMSLP_  -
o texto musical, eventuais textos anexos às músicas (como no caso dos
métodos), dados editoriais das composições impressas ou de produção
(anotações) das manuscritas, ou outras informações que identifiquemos

*
*

_b.__Informações Obra_ (agregadas): informações não constantes em _X.
Arquivo IMSLP_  - Fico em dúvida se as informações advindas das análises
que operaremos (duração, forma, contornos, etc) devem vir aqui, ou merecem
outro “nicho”

Bom, para voltar a falar em “fonte”, este conceito vai ser móvel:
- ```
    - Uma *Y. Obra* pode estar contida em uma ou mais fontes
  ```
  
  (entendendo aqui por isto _X. Arquivo IMSLP_).
- ```
   -  Uma mesma *Y. Obra* pode ser apresentada em diferentes “versões”
  ```
  
  por diferentes fontes (entendendo aqui por isto _X. Arquivo IMSLP_) – um
  manuscrito e uma 1a edição, por exemplo.
- ```
    - Um *X. Arquivo IMSLP* será a fonte das *a.* *Informações IMSLP*
  ```
- ```
    - Uma *Y. Obra* será a fonte de informação de parâmetros musicais
  ```
  
  (forma, tonalidade, contorno, etc)
- ```
    - As fontes paras as *b.Informações Obra* serão fontes
  ```
  
  bibliográficas ou arquivais, diferentes das _a._ _Informações IMSLP_.

O que além disto vc necessita?

**Comment by msampaio** [comment]
@robattolucas, estou registrando aqui o resultado da nossa conversa de ontem. Caso encontre algum erro, por favor avise.

No gráfico abaixo, as letras significam:
- A. Fonte. O documento do IMSLP, que pode ser uma partitura de uma única obra, um caderno de partituras de várias obras ou mesmo uma partitura de um fragmento de obra (por exemplo, um movimento da obra)
- B. Segmento da fonte ou lição. Tem duas interpretações possíveis:
  *\* Do ponto de vista da fonte, trata-se de cada obra contida na fonte. Em um caderno de partituras, cada partitura de obra é considerada um segmento de fonte.
  *\* Do ponto de vista da obra, trata-se de uma lição, uma "versão da obra"
- C. Subsegmento da fonte. Trata-se de cada movimento do item B
- D. Obra. É uma abstração do conjunto de lições que a compõe.
- E. Compositor

![diagram1](https://f.cloud.github.com/assets/1006488/1411086/2ae9c642-3db1-11e3-9a59-f34b92c3676c.png)

No gráfico abaixo há um exemplo de uma obra X que consta em dois cadernos de partituras. Os itens a, b, c, d, e são segmentos dessas fontes. Do ponto de vista da obra X, os itens b e d são lições.
![diagram2](https://f.cloud.github.com/assets/1006488/1411098/6bc880fe-3db1-11e3-92dd-7bc7f651feab.png)

**Comment by robattolucas** [comment]
Marcos, Perfeito! Só observando que muito frequentemente nas obras da nossa
pesquisa A e B do 1o gráfico vão ser ma mesma coisa (fonte única IMSLP para
uma obra).

Em 25 de outubro de 2013 17:11, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

**Comment by msampaio** [comment]
@robattolucas, estou implementando a estrutura que definimos no comentário https://github.com/GenosResearchGroup/FlautaSolo/issues/46#issuecomment-27121980. Por uma questão de praticidade na implementação do código do MusiAnalysis, pensei em chamar a fonte (letra A) de _source_, o segmento de fonte (letra B) de _score_, e o subsegmento de fonte (letra C) de _movement_. Esta terminologia ficará restrita ao programa.
Você problema nesses termos?

**Comment by robattolucas** [comment]
Esta terminologia é boa, e dará conta da maior parte dos casos.

Em 15 de janeiro de 2014 12:43, Marcos da Silva Sampaio <
notifications@github.com> escreveu:
