### ISSUE TITLE
Baixar fontes de obra anônima e método

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#47]
Conforme decisāo na tarefa #45, baixar os arquivos com as fontes das seguintes obras:
1. Monzani (1801)
2. Tromilitz (1791)
3. Op. 7 _L'art de Préluder_ (1719)
4. Elegant Extracts for the Flute or Violin (1794) .

Caso haja mais que uma fonte para cada obra, perguntar a @robattolucas qual escolher.

**Comment by daniloabrahao** [comment]
@robattolucas, esse métodos são muito legais!!!

1) Monzani (1801):
`IMSLP34491-PMLP77807-monzanis-instructions-for-the-german-flute_1`
`IMSLP34492-PMLP77807-monzanis-instructions-for-the-german-flute_2`
`IMSLP34493-PMLP77807-monzanis-instructions-for-the-german-flute_3`
2) Tromilitz (1791):
`IMSLP75105-PMLP150692-TromlitzAusfhrlicherUndGrndlicherUnterrichtDieFlteZuSpielen1791`
3) Op. 7 L'art de Préluder (1719) [1]:
`IMSLP111786-PMLP228362-lart_de_preluder_hotteterre`
`IMSLP279418-PMLP228362-lart_de_preluder2_hotteterre`
4) Elegant Extracts for the Flute or Violin (1794) [2]:
`IMSLP70132-PMLP141087-elegant_extracts_flute_violin_1794`
`IMSLP70133-PMLP141087-elegant_extracts_flute_violin_3rd_book_1798` 

[1] O conteúdo dos arquivos é o mesmo, mas o 1 primeiro está colorido e o segundo em preto e branco.
[2] O IMSLP possui o primeiro e o terceiro livros Elegant Extracts. Você especificou só o de 1794, mas resolvi já deixar o outro baixado o de 1798.

Tarefa concluída.
