### ISSUE TITLE
Definir subdivisões IMSLP34491 Monzani 1801 1

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#48]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas
1. Definir subdivisões do Monzani 1801 n.1 (IMSLP34491) para transcrever. Fazer tarefa com o auxílio de @robattolucas. Iremos transcrever escalas, exercícios de intervalos ou apenas os exercícios que se aproximam mais de uma composição?
2. Criar uma cópia do arquivo pdf com o sufixo "anotada" com todos os números das partes que iremos transcrever, como se fossem movimentos: "M1", "M2", "M3"

**Comment by msampaio** [comment]
@daniloabrahao, conforme falamos na reunião, acho que os passos para realizar essa tarefa são:
1. Listar todas as categorias de partituras que ocorrem: escalas, pequenos exercícios (por ex., intervalos), pequenas composições.
2. Decidir junto a @robattolucas quais dessas categorias serão transcritas. O objetivo do projeto será crucial para esta decisão.
3. Indicar os números das partes.

**Comment by daniloabrahao** [comment]
@msampaio, estou fazendo a lista de categorias de partituras do Mozani num bloco de notas. Posso salvar na pasta `Produção`?

**Comment by msampaio** [comment]
Sim, @daniloabrahao. Pode salvar na pasta Produção em formato txt.

**Comment by daniloabrahao** [comment]
@msampaio e @robattolucas, eu fiz uma lista (vide `Mozani-ListaDeConteúdo.txt` na pasta `Produções`) que lista todas as categorias de partituras que ocorrem na parte 1 do Método de Mozani. Devo inserir alguma informação além das que se encontram, como por exemplo o nº de compassos de cada exercício.?
Marquei com `*` os itens que julgo terem valor musical além do seu objetivo técnico.

Outra coisa, é que a parte `TIPPING AND SLURRING` contém 34 exercício musicais. Os 32 primeiros são de 2 a 3 compassos e os dois últimos são grandes e possuem até indicação de andamento.

Vou continuar esse trabalho com as outras partes.

**Comment by msampaio** [comment]
@daniloabrahao e @robattolucas, apenas renomeei o arquivo para [TiposDeDocumento-MetodoFlautaMozani.txt](https://www.copy.com/browse/company-11103/Flauta%20Solo/Produ%C3%A7%C3%A3o/TiposDeDocumento-MetodoFlautaMozani.txt).

**Comment by daniloabrahao** [comment]
A parte 2 do método de Mozani contém 36 duos musicais em ordem progressiva de dificuldade. Mozani chama os 22 primeiros de `Easy Progressive Lessons` e os demais de `Progressive Pieces`.

A parte 3 contém, em especial, os `Preludes`, as `Cadenze` e o `Capriccio Modulato`, que parecem ser musicalmente bem ricos.

1º passo da tarefa concluído.

**Comment by msampaio** [comment]
@daniloabrahao, preciso de uma lista apenas com os tipos de conteúdo das partituras do volume 1. Há exercícios de escalas, de padrões de intervalos, pequenas composições? Acredito que podemos definir o que transcrever a partir dos tipos de conteúdos.
@robattolucas, o que você acha de decidirmos desde já o que transcrever? A princípio não acho necessário transcrever exercícios de escalas ou padrões de intervalos.

**Comment by daniloabrahao** [comment]
@msampaio, eu não entendi o que você disse. Eu listei todas as partituras encontradas no método e deixei uma breve descrição de seu conteúdo. Tudo isso no arquivo `TiposDeDocumento-MetodoFlautaMozani.txt`. Tem mais alguma coisa que devo fazer nessa lista?

**Comment by robattolucas** [comment]
Isto mesmo. Podemos deixar as escalas, arpejos, etc. de fora. Existem
vários exemplos bem curtos de fragmentos - isto é bem comum em métodos do
seç. XVIII. Vamos transcreve-los todos ou somente aqueles maiores que um
determinado número de compassos (há exemplos de até 1 compasso!)?

**Comment by msampaio** [comment]
@daniloabrahao, como @robattolucas já decidiu o que fica de fora, não precisa mais fazer o que pedi e você não entendeu ;-)
@robattolucas, eu não gosto da ideia de definir arbitrariamente o número de compassos. O que você acha de saber via software se esses compassos únicos têm influência em composições ou outros métodos? Se achar relevante, é melhor transcrever mesmo os fragmentos de compasso único.

**Comment by robattolucas** [comment]
Acho que é o habito de trabalhar com universos de dados reduzidos, que faz
a gente buscar critérios que "facilitem a nossa vida". Como não vai ser o
caso nesta pesquisa, vamos sim aceitar até mesmo fragmentos de compassos.
Examinando o Quantz, ele dá exemplos sistemáticos de ornamentações, e uma
analise computacional pode "inverter o caminho" e buscar sistematicamente
aqueles padrões de ornamentação (que são apresentados nos métodos na forma
de fragmento de compasso) em obras, ou então encontrar situações em obras
sem ornamento em que estes ornamentos podem ser aplicados.

Isto entre 1000 outras coisas...

**Comment by msampaio** [comment]
Ótimo, @robattolucas. Então podemos seguir em frente com esta fonte.
@daniloabrahao, pode seguir em frente com a segunda parte desta tarefa, de criação de versão anotada do PDF com a indicação das "obras" a serem transcritas. Indique apenas aquilo que iremos transcrever.

**Comment by daniloabrahao** [comment]
Ok!

**Comment by msampaio** [comment]
@daniloabrahao, qual o estado desta tarefa? Tenho certa pressa, pois dependo dela para delegar as tarefas de transcrição para o resto da equipe.

**Comment by daniloabrahao** [comment]
A tarefa ainda está parada por causa da enorme diversidade de partituras encontradas no método.

Exemplo de partituras que devem ser transcritas:
![sem ttulo](https://f.cloud.github.com/assets/4681458/1088590/cefc647c-1635-11e3-9711-be12de0febde.png)

---

Exemplo de partituras que não devem ser transcritas:
![image](https://f.cloud.github.com/assets/4681458/1088622/551f4920-1636-11e3-9a80-c1d7a0f498ec.png)

---

Porém existem alguns tipos diferentes de partituras em que eu não sei se devem ser transcritas ou não:
![image](https://f.cloud.github.com/assets/4681458/1088636/96c89dcc-1636-11e3-8f3e-d795516096d7.png)

> Este exemplo se encontra bem no início da parte 1 e apesar de ter uma melodia, Mozani apresentou esta pauta apenas com o intuito de exemplificar o uso dos valores de duração no pentagrama. Possui interesse musical.

![image](https://f.cloud.github.com/assets/4681458/1088668/1f58c892-1637-11e3-83ce-944ff64af1f4.png)

> Estes são exemplos de uso de ornamentações que possuem interesse musical.

![image](https://f.cloud.github.com/assets/4681458/1088720/da3cf156-1637-11e3-9d00-6a7314a4fdea.png)

> Este é um exemplo de trinado que usa uma chave específica da flauta da época. É relativamente grande e possui interesse musical.

![image](https://f.cloud.github.com/assets/4681458/1088747/3632ca08-1638-11e3-8411-25194a6e1450.png)

> A parte "Tipping and Slurring" possui 32 exercícios como estes, curtos mas com certo interesse também.

Por hora, isto é uma amostra do tipo de coisa que ocorre na parte 1. Exemplos como os acima são recorrentes e existem outros diferentes na parte 3. Não sei também como proceder com a parte 2, considerando que é formada apenas por Duos de Flauta.

[Lembrando que a lista `TiposDeDocumento-MetodoFlautaMozani` possui uma descrição de cada tipo de partitura que ocorre no método]

**Comment by msampaio** [comment]
@robattolucas e @daniloabrahao, eu estou entre duas posições em relação à decisão do que iremos descartar:
1. Admitimos apenas obras como a do exemplo 33 (o primeiro do comentário) e descartamos todas as demais.
2. Descartamos apenas os exercícios de escala, como o segundo exemplo do comentário.

Com a primeira opção, podemos deixar de lado fontes de dados importantes. Com a segunda, podemos gastar muito tempo definindo o que é interessante ou não. Existe uma continuidade entre os trabalhos que temos certeza que iremos transcrever e os que temos certeza que não iremos. Por isso acho complicado estabelecer um parâmetro que defina o que iremos descartar.
Minha recomendação é tentar seguir a segunda opção por uns dias, mas se complicar muito, partir para a opção 1.

O que acham?

**Comment by daniloabrahao** [comment]
@msampaio, sou a favor da opção 1, mas tive a seguinte ideia:

Eu poderia utilizar 2 códigos nas anotações da fonte. Um para obras como o exercício 33 e 34 e o outro para os pequenos trechos que possuem interesse musical. A partir daí, partiríamos para sua opção 1. Transcrevendo assim, o conteúdo mais próximo de um repertório "de concerto".

Tendo a marcação desses pequenos trechos musicais já concluída no arquivo, podemos trabalhá-los posteriormente*. Isto é, se  julgarmos isso conveniente no futuro.

Dessa maneira, a equipe não ficaria muito tempo parada e teremos mais tempo para resolver a questão desses fragmentos.

*Pensei em trabalhar os fragmentos musicais de Mozani junto com fragmentos de outros métodos, porém isolados do material que é mais próximo do repertório "de concerto".

**Comment by msampaio** [comment]
@daniloabrahao, podemos registrar o código em todos os exemplos, exceto escalas. Assim já poderemos atribuir as tarefas de transcriçāo. Depois decidimos se iremos transcrever os exemplos polêmicos. O que você acha?
Você pode usar o código O1, O2, etc para as partituras. Se houver movimentos podemos chamar O1M1, O1M2, etc.

**Comment by daniloabrahao** [comment]
Acho ótimo!

**Comment by msampaio** [comment]
Māos à obra entāo. Por favor informe aqui quais os códigos das transcrições prioritárias.

**Comment by daniloabrahao** [comment]
@msampaio, no caso:
![image](https://f.cloud.github.com/assets/4681458/1095699/bdb41d64-16ed-11e3-8338-e570e7fe304f.png)
Eu devo usar um código para cada pauta? Ou um único para as 5?

Estou com um problema para anotar no arquivo do Mozani, pois o Adobe só permite fontes com tamanho até 24 e esse tamanho é muito pequeno. Isso acontece, acredito eu, pelo fato de cada página do método ser uma imagem muito grande e com alta resolução. Diferente do arquivo das Fantasias de Telemann, em que 24 foi um tamanho relativamente grande. O programa que você usa para anotar no .pdf permite uma fonte de tamanho maior?

**Comment by robattolucas** [comment]
Concordo com a solução de não descartar os fragmentos pequenos, e acho
muito boa a idéia de destacá-los através de um código diferente, destinado
a "fragmentos", que - a proncípio - não visa ou não se adequam bem á
tradição de apresentações públicas. Pensando sobre estes "fragmentos",
podemos também pensar em utilizar o termo "fragmentos musicais sem a
preocupação de integridade de obra". Explico: muito provavelmente nem os
estudos melódicos, e nem mesmo as "obras"(fantasias de Telemann por ex.)
eram destinadas à apresentação pública. É consenso hoje que este tipo de
música era considerado na época como "privada" (por isto "música de
câmara", música do quarto, da casa, provavelmente sem público além dos
executantes), em oposição ao público (missas, opera, etc).

**Comment by daniloabrahao** [comment]
Então, como vai ser? Códigos diferentes ou códigos semelhantes?

**Comment by msampaio** [comment]
@daniloabrahao e @robattolucas, recomendo usar um código único, como `O1`, `O2`, `O3M1`, `O3M2`, etc. Podemos "etiquetar" esses fragmentos posteriormente nos metadados.

@daniloabrahao, acho melhor criar um código para cada pauta no exemplo da imagem que você mostrou.
Sobre o tamanho da fonte da indicação, uma cor contrastante resolve o problema? Caso não resolva, você pode fazer duas coisas para resolver esse problema:
1. Testar outro programa para anotar arquivos pdf
2. "Imprimir" a partitura em um formato A4.

Provavelmente o melhor a fazer é seguir a solução 2.

**Comment by robattolucas** [comment]
Sugiro um código para cada exemplo, definido por barra dupla, palavra
'etc." e início de pentagrama.

**Comment by daniloabrahao** [comment]
@msampaio e @robattolucas , a parte 2 do método possui, da página 12 até o seu fim, um conjunto de duos que são iniciados, cada um, por pequenos prelúdios (3 a 4 compassos) executados em uma única flauta. Como proceder com isso? Considerando que são apenas fragmentos de obras que são Duos, na verdade.

![image](https://f.cloud.github.com/assets/4681458/1101274/df2ff752-17b9-11e3-84e5-954eddb003f6.png)

**Comment by daniloabrahao** [comment]
Outra questão é a primeira seção da Parte 3. Chama-se "Various Ways of Fingering" e vai até a página 15 apresentado pequenas passagens difíceis para a flauta da época:

![image](https://f.cloud.github.com/assets/4681458/1101279/522f4b40-17ba-11e3-9af5-18ff8b85f7e2.png)

Não são apenas exercícios como escalas e arpejos. Mas não sei se devo marcá-los ou não, pois são muito curtos e não possuem muito interesse musical.

**Comment by daniloabrahao** [comment]
Na parte 3 comecei a numerar a partir da página 16. Se for necessário eu corrijo isso depois. Logo:
- Transcrições prioritárias:
  - Parte 1: `O47` e `O48`
  - Parte 2: nenhuma
  - Parte 3: `O25`

**Comment by msampaio** [comment]
@daniloabrahao, você já concluiu a anotação do pdf de Monzani com as subdivisões das "obras"?

**Comment by daniloabrahao** [comment]
Já! Mas apresentei umas dúvidas (ver comentários anteriores).

**Comment by msampaio** [comment]
Ok. Vou fechar a tarefa então.
