### ISSUE TITLE
Documentar criação de anacruse no meio do compasso no Finale

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#49]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Documentar a criação de anacruse no meio do compasso no Finale no [handbook do Genos](http://genosmus.com/handbook/)

**Comment by msampaio** [comment]
@AlissonGSilva, qual o estado desta tarefa? Lembre-se que o deadline é hoje.

**Comment by ZeRodriguez** [comment]
@msampaio, Alisson pediu para avisar que devido aos problemas com a internet, a tarefa ainda não foi concluída.

**Comment by AlissonGSilva** [comment]
Pronto Marcos, documentação concluida, inclusive ja tem uma publicação de Kroger sobre isto.
Eu redirecionei o post para aparecer na pagina do Finale no Genos.
