### ISSUE TITLE
Renomear partituras para novo código de identificação

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#50]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Renomear todos os arquivos da pasta Partituras usando o novo [código de identificação de arquivos](http://genosmus.com/pesquisa/flauta-solo/manual/codigo-de-identificacao-de-arquivo/) resultante da tarefa #12. Seguir estritamente as diretrizes do código.

Todos os arquivos desta pasta são derivados da fonte `EF00001` e por essa razão terão esse prefixo.

**Comment by ZeRodriguez** [comment]
@msampaio, editei o enunciado da tarefa. Se entendi direito, a fonte seria `EF00001` e não `E00001` como você tinha colocado. Verifique se estou correto por favor.

**Comment by msampaio** [comment]
Está correto. Obrigado

**Comment by ZeRodriguez** [comment]
@msampaio, os arquivos: 

`ET00001_10a` 
`ET00001_10b`
`ET00001_10c`
Foram editados por mim na tarefa #36 . 
Os arquivos: 
`ET00001_12a`
`ET00001_12b` foram editados por Alisson na tarefa #38 . 
Apesar de não ter sido pedido, ambos fizemos as respectivas expansões, e já se encontram na pasta.

**Comment by ZeRodriguez** [comment]
Os arquivos:

`ET00001_09a`
`ET00001_09b`
`ET00001_09c`
`ET00001_09d`
`ET00001_11a`
`ET00001_11b`
`ET00001_11c`
`ET00001_11d`
São os únicos que faltam ser expandidos. Ambos editados por Luã em uma versão do Finale não compatível com a minha.

**Comment by ZeRodriguez** [comment]
Os arquivos:

`ET00001_08a`
`ET00001_08b`
`ET00001_08c`
Foram editados por Menahem. E apesar de ele não ter se pronunciado na tarefa #34 , as expansões já se encontram na pasta. Já tentei entrar em contato com ele para saber se posso dar a tarefa como concluída. No entanto, houve problemas de nomenclatura nesses arquivos. Como havia mais de um arquivo `.XML` para um mesmo arquivo `.mus`, fui obrigado a abri-los. Vi que algumas peças estavam com o movimento trocado quando comparado com a fonte. Ex.: movimento 1 chamado de B e movimento 2 chamado de A. Dessa forma, os nomeei corretamente e, para evitar confusão, deleteis os respectivos `.XML` e os gerei novamente. Não houve problemas no processo de expansão, apenas os equívocos de nomenclatura.

**Comment by ZeRodriguez** [comment]
Os arquivos:

`ET00001_07a`
`ET00001_07b`
`ET00001_07aE`
`ET00001_07bE`
Foram editados no Sibelius. Assim, todos ficam com o sufixo `.sib` em seu nome, não podendo ser alterado. Dessa forma, não mexi nesses arquivos e espero um posição sua, @msampaio. Com todas as anotações devidas, tarefa concluída!

**Comment by msampaio** [comment]
Ótimo trabalho, @ZeRodriguez. Fechando tarefa.

**Comment by ZeRodriguez** [comment]
Alterei os nomes das que foram editadas no Sibelius.
