### ISSUE TITLE
Revisar dados sobre novas entradas bibliográficas

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#52]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Revisar dados sobre novas entradas bibliográficas:
- Mouton
- Temperley
- Pardo

**Comment by menahemhein** [comment]
Está tudo correto, eu acrescentei algumas coisas a mais como número de páginas e issue, mas no Mouton eu queria acrescentar esses 2 a mais IJCAI(Joint Conferences on Artificial Intelligence)   Vol. 95, mas não sei onde coloco ! tem algum problema de eu não colocar esses 2?

**Comment by msampaio** [comment]
@menahemhein, é essencial colocar "Proceedings of the Workshop on Artificial Intelligence and Music", mas não a conferência em si. É importante você saber as diferenças entre os tipos de entradas bibliográficas: http://en.wikipedia.org/wiki/BibTeX#Entry_types

**Comment by msampaio** [comment]
@menahemhein, observe que o livro do Farnell está duplicado.

**Comment by msampaio** [comment]
@menahemhein, ainda sobre sua tarefa, olhe todos os itens do tipo "Conference Proceedings" e "Journal Article". Caso não haja os campos "Proc. Title" ou "Journal", procure no Google acadêmico e preencha os dados corretamente. Há vários itens incompletos.

**Comment by menahemhein** [comment]
Feito ! Professor eu andei olhando alguns dados no Mendeley e vi que alguns dados de arquivos que já estavam lá continham erros, eu posso dar uma revisada em todos os arquivos e preencher o máximo possível de todos os arquivos ?

**Comment by msampaio** [comment]
Sim! :-D
Embora eu esteja colocando aqui, esta é uma tarefa permanente. Preciso que você garanta que os dados estão sempre corretos. O Mendeley informa quando alguém faz alterações nos dados. Você pode rastrear o que olhar por aí: http://www.mendeley.com/groups/3494461/solo-flute/
