### ISSUE TITLE
Elaborar página da pesquisa em inglês

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#54]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Elaborar uma página da pesquisa de flauta solo em [inglês](http://genosmus.com/pesquisa/flauta-solo/english/), conforme sugestão de @gbertis na tarefa #6. Inserir as informações da [página principal](http://genosmus.com/pesquisa/flauta-solo/) da pesquisa.

**Comment by patrickandrews** [comment]
Confira se está tudo ok.

**Comment by msampaio** [comment]
Tá beleza.
