### ISSUE TITLE
Escrever resenha de Mason (Beatles)

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#55]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Escrever resenha de "Mason, Douglas J. “The Beatles Genome Project : Cluster Analysis and Visualization of Popular Music.”"

O objetivo da resenha é elaborar um texto enxuto com os objetivos, resultados, metodologia e possíveis aspectos interessantes da pesquisa.

Ver [exemplo de resenha](http://genosmus.com/2011/11/the-intersection-of-computational-analysis-and-music-manuscripts-a-new-model-for-bach-source-studies-of-the-21st-century-niitsuma-et-al-2009/) e registrar texto na pasta Produção, no Copy.

**Comment by SaraFadigas** [comment]
Onde vou arquivar a resenha? em pdf dentro de Publicacoes, ou vou escrever como ata e salvar lá?

**Comment by msampaio** [comment]
Na pasta Produção, no Copy. Veja o modelo de outras resenhas que estão lá.

**Comment by SaraFadigas** [comment]
Tarefa concluida
