### ISSUE TITLE
Listar itens bibliográficos sobre análises com Musicologia Computacional

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#56]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em procurar referências de artigos, livros, capítulos de livros e teses que abordem análises musicais com uso de ferramentas de Musicologia Computacional. É comum encontrar termos como "análise assistida por computador".

O blog de [Tiago Quadros](http://tiagodequadros.wordpress.com/category/bases-de-dados/) tem uma ótima categoria "banco de dados" com diversos sites de busca de documentos. Além de olhar no Google Scholar, verificar todos os itens sugeridos por Tiago.

Guardar a lista resultante desta tarefa em um documento na pasta Produção, no Copy.

**Comment by SimeiFerreira** [comment]
@msampaio, está bem complicado encontrar bibliografias que tratem de análise musical assistida por computador, as pesquisas sempre retornam resultados ligados à computação musical (visão geral), educação musical com auxílio do computador (o que inclui o desenvolvimento de softwares para auxiliar nas aulas de música) e composição musical assistida pelo computador (música eletroacústica, redes neurais, etc.)

Devo adicionar essas bibliografias ou deixar as poucas que encontrei falando sobre análise?

**Comment by msampaio** [comment]
Coloque aqui alguns exemplos desses itens referentes a composiçāo e educaçāo e todos os itens referentes a análise.

**Comment by msampaio** [comment]
@SimeiFerreira, qual o estado desta tarefa? O deadline foi ontem.

**Comment by SimeiFerreira** [comment]
@msampaio, eu encontrei apenas três bibliografias que fazem alguma relação de análise envolvendo música com o auxílio de computador. Coloquei as três na pasta produção do copy com o nome "ItensBibliograficos-AnáliseMusicologiaComputacional". Eis as bibliografias que encontrei:

MILETTO, Evandro Manara et al. Introdução à computação musical. In: IV Congresso Brasileiro de Computação. 2004.

BLEICHER, Lucas et al. Análise e simulação de ondas sonoras assistidas por computador. Revista Brasileira de Ensino de Física, v. 24, n. 2, p. 129-133, 2002.

DORIA, LUIZ EDUARDO FANK. Análise de frases musicais monofônicas em testes de avaliação para corais. Trabalho de conclusão de curso. Novo Hamburgo, 2010.

Mais tarde colocarei exemplos de bibliografias que me deixaram em dúvida sobre sua relevância com o solicitado.

**Comment by msampaio** [comment]
@SimeiFerreira, duas perguntas:
1. Você tem esses textos em pdf?
2. Você procurou apenas textos em português?

**Comment by SimeiFerreira** [comment]
Respondendo:

1 - Não cheguei a baixar, li rapidamente online na segunda-feira quando estava pesquisando.
2 - Procurei apenas textos em português, entretanto, no meio da pesquisa vieram uns dois ou três textos em línguas como espanhol e francês.

Pesquisei pelos cinco sites de busca que o Tiago recomenda, baixei também o Guia da internet 2013 que tem inúmeros outros sites para busca, mas como são muitos sites, não cheguei a pesquisar por eles ainda.

Utilizei termos como "análise assistida por computador, análise musical assistida por computador, musicologia computacional, análise musical com auxílio de computador e computação musical". Cada texto apresentado nas pesquisas eu lia rapidamente de um por um para entender o contexto e ver se havia relação com o que você solicitou.

Vou procurar os três textos que coloquei na lista e disponibilizá-los no copy, ponho na pasta produção mesmo?

**Comment by msampaio** [comment]
@SimeiFerreira, por favor edite o comentário para colocar o link para os textos. Não precisa baixar os textos. Quero vê-los primeiro.

Sobre a língua, 99,999...% do que podemos encontrar sobre Musicologia Computacional está em inglês. Até bem pouco tempo atrás o único texto com essa expressão que aparecia na busca nessas bases era o que escrevemos sobre os corais de Bach.

**Comment by msampaio** [comment]
@SimeiFerreira, qual o estado desta tarefa? Estou aguardando o fechamento para poder seguir com a revisão de bibliografia.

**Comment by msampaio** [comment]
@SimeiFerreira, precisamos concluir essa tarefa para seguir em frente. Estou no aguardo da conclusão para poder delegar as outras tarefas da revisão sobre Musicologia Computacional.

**Comment by SimeiFerreira** [comment]
@msampaio, vou procurar termos em inglês para aprimorar a busca por um maior número de bibliografias. Tentarei concluir a tarefa até amanhã.

**Comment by SimeiFerreira** [comment]
Resultados mais relevantes nas buscas pelo termo "computação musical":

http://gsd.ime.usp.br/sbcm/2005/papers/tech-12452.pdf

http://www-usr.inf.ufsm.br/~dflores/elc1020/t1/artigo.pdf

http://www.evandromanara.net/files/UFRGS/Mini-cursoIntrodCM_CBC2004.pdf

http://www.lume.ufrgs.br/handle/10183/3222

http://tconline.feevale.br/tc/files/0001_2225.doc

http://www.scientificcircle.com/pt/41778/analise-simulacao-ondas-sonoras-assistidas-computador/

**Comment by SimeiFerreira** [comment]
Resultados mais relevantes nas buscas pelo termo "computer musicology"

http://web.mit.edu/music21/papers/Cuthbert_Ariza_ISMIR_2010.pdf

http://www.jstor.org/discover/10.2307/3680415?uid=2&uid=4&sid=21102670708897

http://ccm.uc.edu/music/cmt/events/computermusic.html

http://www.lim.dico.unimi.it/events/ctama/baggi.htm

http://link.springer.com/article/10.1007%2FBF01830711

**Comment by SimeiFerreira** [comment]
Resultados mais relevantes nas buscas pelo termo "computer assisted musical analysis"

http://musiccog.ohio-state.edu/Humdrum/Kornstaedt/jring.pdf

http://dl.acm.org/citation.cfm?id=244139

http://link.springer.com/article/10.1007%2FBF02393450?LI=true#page-1

http://complex.ccsr.uiuc.edu/web/Techreports/1990-94/CCSR-91-20.pdf

http://gsd.ime.usp.br/sbcm/2005/papers/tech-12361.pdf

http://www.jstor.org/discover/10.2307/3680238?uid=2&uid=4&sid=21102670708897

http://www.musiccog.ohio-state.edu/Humdrum/Kornstaedt/jring.pdf

http://www.jstor.org/discover/10.2307/30199321?uid=2129&uid=2&uid=70&uid=4&sid=21102737689567

http://sunzi.lib.hku.hk/ER/detail/hkul/3016490

http://joebennett.net/2013/07/04/popmac-day-2-computer-assisted-analysis-of-the-music-of-elton-john-popmac/ (Post de um blog que trata do assunto)

https://www.areditions.com/cmdas/DAS23/cmdas023.html

http://www.amazon.com/Set-Theory-Objects-Abstractions-Computer-Aided/dp/3631478976

http://mitpress.mit.edu/books/computer-models-musical-creativity

http://www.amazon.com/Music-Mind-Machine-Intelligence-Kennistechnologie/dp/9051701497

http://www.worldcat.org/title/set-of-computer-programs-to-aid-in-music-analysis/oclc/2516009

http://www.amazon.com/Computer-applications-Music-Research-Concepts-Methodology/dp/3631390327

http://www.amazon.com/Utilizing-OpenMusic-Analysis-Lutoslawskis-Chain2/dp/3848436507

http://www.tandfonline.com/doi/abs/10.1080/09298210801969145?journalCode=nnmr20#preview

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.149.7958&rep=rep1&type=pdf

http://www.jstor.org/discover/10.2307/3680080?uid=2129&uid=2&uid=70&uid=4&sid=21102737689567

http://www.csl.sony.fr/downloads/papers/2000/pachet00f.pdf

http://link.springer.com/article/10.1007%2FBF02393461?LI=true#page-1

http://www.tandfonline.com/doi/abs/10.1080/00207160213939?journalCode=gcom20#preview

http://jrm.sagepub.com/content/33/3/159.short

http://link.springer.com/article/10.1007%2FBF02395372?LI=true#page-1

http://www.tandfonline.com/doi/abs/10.1080/09298210802259595#preview

http://dl.acm.org/citation.cfm?id=1290156

http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=5194170

http://link.springer.com/article/10.1007%2Fs00500-004-0384-5

http://www.mitpressjournals.org/doi/abs/10.1162/comj.2006.30.3.53

http://smcnetwork.org/files/proceedings/2005/intro-analysis-final-phr.pdf

http://www.tandfonline.com/doi/abs/10.1080/09298210802259595#preview

http://musiccog.ohio-state.edu/Humdrum/Kornstaedt/jring.pdf

http://link.springer.com/article/10.1007%2FBF02393450

http://eprints.gla.ac.uk/43553/

http://quod.lib.umich.edu/cgi/t/text/text-idx?c=icmc;view=toc;idno=bbp2372.1986.067

http://quod.lib.umich.edu/i/icmc/bbp2372.2000.185/1/--musical-analysis-of-a-computer-music-project?rgn=id;view=image;q1=bbp2372.2000.185

http://quod.lib.umich.edu/i/icmc/bbp2372.1999.403/1/--computer-assisted-music-analysis-system-daphne?rgn=id;view=image;q1=bbp2372.1999.403

https://dspace.library.uvic.ca:8443//handle/1828/1081

http://eprints.qut.edu.au/6807/1/6807.pdf

http://link.springer.com/article/10.1007%2FBF02402318

**Comment by msampaio** [comment]
@SimeiFerreira, há boas referências na sua lista, mas ainda há bastante o que encontrar. Procurei por 'computational musicology' em algumas das bases sugeridas por Tiago e encontrei:
1. http://link.springer.com/article/10.1007%2FBF01830711
2. Towards a Distributed Research Environment for Music Informatics and Computational Musicology
3. Computational Musicology in Italy
4. Researchers at University of Ulster Have Published New Data on Language and Communication Science
5. A computer-aided analysis of Anglo-Canadian folktunes
6. Empirical Musicology: Aims, Methods, Prospects.(Statistics in Musicolog)(Book review)
7. Analysing Emotions in Schubert's Erlkönig: a Computational Approach
8. http://onlinelibrary.wiley.com/doi/10.1002/aris.1440370108/abstract
9. Modeling and Searching Music Collections
10. http://onlinelibrary.wiley.com/doi/10.1002/9780470050118.ecse722/abstract

**Comment by SimeiFerreira** [comment]
@msampaio, alguns dos resultados citados acima apareceram nas minhas buscas também, mas eu estou lendo um pouco de cada um dos resultados buscando relação com a pesquisa, então estava deixando de fora os que eu não conseguia ler porque no site só mostra o título do livro. Devo passar a me basear somente nos títulos ao invés de procurar relevância no texto?

**Comment by msampaio** [comment]
@SimeiFerreira, só elimine os textos após a leitura. É possível ter acesso a muitos desses textos pagos usando os computadores da UFBA.

**Comment by SimeiFerreira** [comment]
Tranquilo @msampaio, devo passar para o copy os resultados aqui apresentados assim mesmo em link?

**Comment by msampaio** [comment]
Por hora vá colocando os links aqui mesmo.

**Comment by SimeiFerreira** [comment]
Mais resultados para o termo "Computational musicology":

http://onlinelibrary.wiley.com/doi/10.1002/asi.4630330107/full

http://www.tandfonline.com/doi/pdf/10.1300/J105v03n01_07

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.153.9434&rep=rep1&type=pdf

http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=4145929

https://kb.osu.edu/dspace/handle/1811/21901

http://www.nici.kun.nl/mmm/papers/honing-2004f.pdf

http://www.researchgate.net/publication/46694356_Towards_Integration_of_MIR_and_Folk_Song_Research/file/60b7d51483ef392f81.pdf

http://books.google.com.br/books?hl=pt-BR&lr=&id=OHp3sRnZD-oC&oi=fnd&pg=PA369&dq=Computational+musicology&ots=oDRJtKdAb1&sig=OZEkqOYOs1BRqkWDDYwqoZjJ8ws

http://calcium.dcs.kcl.ac.uk/1125/

http://www-users.cs.umn.edu/~gaurav/papers/tansen.pdf

http://www.jstor.org/discover/10.2307/30200278?uid=2&uid=4&sid=21102736341507

http://promethee.philo.ulg.ac.be/RISSHpdf/Annee1993/Articles/LCamilleri.pdf

http://www.academia.edu/3009477/Real-time_prediction_of_melodies_Continuous_predictability_judgements_and_dynamic_models

http://www.academia.edu/1175219/Mathematics_and_Computation_in_Music

http://www.academia.edu/1176869/Lanalyse_musicale_differentielle_principes_representation_et_application_a_la_structuration_des_entites_musicales_pour_la_musique_electroacoustique

http://www.academia.edu/1071258/On_Computational_Models_of_the_Evolution_of_Music_From_the_Origins_of_Musical_Taste_to_the_Emergence_of_Grammars

http://www.academia.edu/159307/A_Framework_for_Automated_Schenkerian_Analysis

http://www.academia.edu/167776/The_Music_of_CSIRAC

http://www.academia.edu/243059/Modeling_Beats_Accents_Beams_and_Time_Signatures_Hierarchically_with_music21_Meter_Objects

http://www.academia.edu/243060/Tipping_the_Iceberg_Missing_Italian_Polyphony_from_the_Age_of_Schism

http://www.academia.edu/744379/Generalized_Set_Analysis_and_Sub-Saharan_African_Rhythm_Evaluating_and_Expanding_the_Theories_of_Willie_Anku

http://www.academia.edu/710465/Towards_melodic_extension_using_genetic_algorithms

http://www.academia.edu/547567/An_Imagined_Drama_of_Competitive_Opposition_in_Carters_Scrivo_in_Vento_with_Notes_on_Narrative_Symmetry_Quantitative_Flux_and_Heraclitus

http://www.academia.edu/368452/Temporal_Dynamic_Form_in_Music_Atonal_Tonal_and_Other

http://www.academia.edu/462611/MIDI_toolbox_Matlab_tools_for_music_research

http://www.academia.edu/2504531/Timbre_and_affect_dimensions_Evidence_from_affect_and_similarity_ratings_and_acoustic_correlates_of_isolated_instrument_sounds

http://www.academia.edu/3773841/The_consort_fantasias_of_William_Byrd_The_application_of_a_new_quantitative_technique_to_describe_fuga_subject_deformation

http://www.academia.edu/3312720/A_Computational_Method_for_the_Analysis_of_Musical_Improvisations_by_Young_Children_and_Psychiatric_Patients_with_No_Musical_Background

http://www.academia.edu/4168650/A_COMPUTATIONAL_METHOD_FOR_EXPLORING_MUSICAL_CREATIVITY_DEVELOPMENT

http://www.academia.edu/3009477/Real-time_prediction_of_melodies_Continuous_predictability_judgements_and_dynamic_models

http://www.staff.science.uu.nl/~fleis102/CompMus_Volketal.pdf

http://www.tandfonline.com/doi/abs/10.1080/09298215.2010.545241#.UlQ0jRCAano

http://www.sciencedirect.com/science/article/pii/036013159290023X

http://link.springer.com/article/10.1007%2FBF02402495

http://www.springerlink.com/index/v70504845372911v.pdf

https://openlibrary.org/works/OL16369164W/Musicology_and_the_computer_musicology_1966-2000

https://openlibrary.org/works/OL2624381W/Musicology_and_the_computer_Musicology_1966-2000_A_practical_program

https://openlibrary.org/works/OL16007702W/Music_gestalt_and_computing

https://openlibrary.org/works/OL3751988W/Musician%27s_Guide_to_Desktop_Computing_with_the_Macintosh

https://openlibrary.org/works/OL2153150W/Formalised_composition_on_the_spectral_and_fractal_trails

http://www.tandfonline.com/doi/abs/10.1080/17459737.2010.520455#preview

**Comment by SimeiFerreira** [comment]
@msampaio, encontrei até o presente momento 93 itens bibliográficos (se não contei errado) entre os termos pesquisados. Todos eles estão listados acima, qual o próximo passo?

**Comment by msampaio** [comment]
Excelente! Salve essa lista em algo como
BibliografiaMusicologiaComputacional.txt. O próximo passo é obter essas
referências.

On Wednesday, October 9, 2013, SimeiFerreira wrote:

> @msampaio https://github.com/msampaio, encontrei até o presente momento
> 93 itens bibliográficos (se não contei errado) entre os termos pesquisados.
> Todos eles estão listados acima, qual o próximo passo?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/56#issuecomment-25945420
> .

## 

Sent from my Mobile

**Comment by SimeiFerreira** [comment]
Feito! Para obter as referências será aberta uma nova tarefa ou devo postar as dúvidas aqui mesmo?

**Comment by msampaio** [comment]
Abrirei outra tarefa para obter as referências.
