### ISSUE TITLE
Escrever resenha do capítulo 2 do Grier1996

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#58]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Escrever uma resenha sobre o capítulo 2 do Grier1996, "The nature of musical source". Focar nas relações entre o texto e os problemas da pesquisa de flauta solo e as fontes do IMSLP.
Salvar a resenha na pasta Produção, no Copy.

Grier, James. 1996. The Critical Editing of Music: History, Method, and Practice. New York, NY: Cambridge University Press.

**Comment by ZeRodriguez** [comment]
@msampaio, a tarefa já está sendo feita! =D

**Comment by ZeRodriguez** [comment]
@msampaio, tarefa concluída.
