### ISSUE TITLE
Estudar e programar itens 1 e 3 do Tutorial de Python

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#59]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em:
1. Ler o texto [Whetting Your Appetite](http://docs.python.org/2/tutorial/appetite.html) para ter um estímulo para o estudo de Python
2. Ler e programar todos os códigos da [introdução ao Python](http://docs.python.org/2/tutorial/introduction.html) para ganhar prática na linguagem.

Criar um arquivo diogo02.py na pasta Code para salvar os códigos do item 2.

**Comment by msampaio** [comment]
@drakoor, eu olhei seus arquivos no Copy. A ideia é essa, ir programando o que tem no tutorial. No entanto, o seu arquivo não pode ser chamado em um terminal. Veja esse [comentário](https://github.com/GenosResearchGroup/FlautaSolo/issues/5#issuecomment-22595042), reveja esta seção do [tutorial](http://docs.python.org/2/tutorial/interpreter.html#executable-python-scripts) e veja os arquivos de @AlissonGSilva no Copy. Você está copiando o resultado do interpretador, e não criando scripts python executáveis.

**Comment by msampaio** [comment]
@drakoor, estou aguardando seu comentário aqui para poder seguir em frente com as tarefas.

**Comment by drakoor** [comment]
Estou refazendo professor, transformei em comentario as linhas que tinham o
prompt mas não executou, estou juntando todo o conteudo dos arquivos em um
único arquivo.

2013/10/16 Marcos da Silva Sampaio notifications@github.com

**Comment by msampaio** [comment]
@drakoor, informe aqui a mensagem de erro para que eu possa te ajudar.

**Comment by drakoor** [comment]
professor eu já tinha começado a refazer a programação inteira, e como
re-iniciei de uma forma mais organizada achei por bem seguir até o final,
já testei e agora ela está rodando perfeitamente e já postei na pasta do
copy também e aproveitei deletei os arquivos fragmentados que postei

2013/10/16 Marcos da Silva Sampaio notifications@github.com

**Comment by msampaio** [comment]
Ok, @drakoor. Agora está correto. Fechando tarefa.
