### ISSUE TITLE
Criar conta para acesso ao API do IMSLP

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#6]
De acordo com a [documentação](http://imslp.org/wiki/IMSLP:API_accounts), é possível criar uma conta para uso da API do IMSLP. Há uma opção de criar uma conta API para fins não comerciais. É necessário escrever para o [Edward W. Guo](http://imslp.org/wiki/User:Feldmahler), criador e líder do IMSLP (feldmahler {at} imslp.org), e solicitar a abertura desta conta. Será necessário informar:
1. the nature of your project
2. a detailed description of your project
3. the royalty you are willing to pay (if applicable)
4. the timeframe within which your project will go live.

**Comment by msampaio** [comment]
Enviei a solicitação hoje. Aguardando resposta de Edward Guo.

**Comment by msampaio** [comment]
Até hoje não tive resposta de Edward Guo sobre a conta de acesso API ao IMSLP. Reenviei a mensagem e permaneço no aguardo.

**Comment by msampaio** [comment]
Edward Guo respondeu a mensagem e perguntou que metadados exatamente precisamos. Ele quer saber se o IMSLP tem as informações que queremos para poder gerar a conta de acesso. Darei a ele os dados listados na tarefa #28.

**Comment by msampaio** [comment]
Pedi ao Edward Guo os dados seguintes já disponíveis na página do IMSLP:
1. Composition:
   - Year
   - Genre
   - Catalogue number
   - Opus number
   - Key
   - Movements
2. Composer:
   - Complete name
   - Born/death dates
   - Available works in IMSLP
3. Source:
   - Editor
   - Publisher info

**Comment by msampaio** [comment]
@robattolucas e @gbertis,
O administrador do IMSLP perguntou se estamos dispostos a compartilhar os nossos dados processados e resultados das análises com eles.
Eu sou a favor de compartilhar os arquivos xml desde já e os resultados após publicarmos. O que acham de perdirmos que eles insiram um link para nosso projeto em todas as páginas de músicas com as quais contribuirmos?

**Comment by gbertis** [comment]
Marcos,
A idéia é muito boa. Para que tenhamos mais alcance, seria conveniente termos uma versão da página da pesquisa em inglês.
Abraços e bom final de semana.
Guilherme

**Comment by robattolucas** [comment]
Uau!

Mal começamos e já estamos em âmbito mundial!

Sim, acho que devemos participar, mas devemos pensar direito o que postar
lá, pois é um site muito popular, e podemos ser "atropelados" por algum
"aventureiro de plantão". O ideal é postar quando tivermos algo que garanta
inegavelmente o nosso direito à autoria do projeto.

Alguém tem alguma idéia de como fazer isto?

Abs,

Lucas

**Comment by msampaio** [comment]
Eu pensei em dois tipos de contribuições que podemos fazer:
1. **Transcrições em formato XML**. À medida que fomos transcrevendo as obras, podemos disponibilizar os arquivos em formato XML com a nossa assinatura visível (na página da partitura) e invisível (no código da partitura). Quem quiser pode importar para usar no Finale, Sibelius e outros.
2. **Dados sobre as obras para flauta solo**, como frequência de intervalos, contornos, etc. Podemos fornecer esses dados apenas quando o projeto estiver maduro e após publicarmos os resultados em algum periódico (em inglês).

O que acham?

**Comment by msampaio** [comment]
@robattolucas e @gbertis, o que vocês acham da proposta acima? Estou dependendo apenas disso para entrar em contato com o Edward Guo.

**Comment by gbertis** [comment]
Sim, gosto muito da proposta @msampaio. Talvez futuramente possamos vislumbrar outras possibilidades, mas agora esse é o caminho.

**Comment by msampaio** [comment]
Ótimo, @gbertis. Enviei hoje essa proposta ao Edward Guo. Fiquemos no aguardo da resposta.

**Comment by msampaio** [comment]
Após duas semanas sem resposta, reenviei hoje a proposta ao Edward Guo.

**Comment by msampaio** [comment]
Edward Guo respondeu ontem e disse que irá abrir minha conta para a API do IMSLP até o fim de semana.

**Comment by msampaio** [comment]
Acesso à API do IMSLP concedida!
