### ISSUE TITLE
Delegar as tarefas de transcrição do IMSLP34491 Monzani 1801 1

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#60]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em delegar as transcrições das obras indicadas na tarefa #48 para cada um dos colaboradores da pesquisa criando novos **_issues**_ aqui no GitHub.
Para realizar esta tarefa seguir estas recomendações:
1. O colaborador já deverá ter cumprido suas tarefas anteriores. Não delegar tarefa a quem tem trabalho atrasado.
2. Priorizar os colaboradores que têm tarefas de transcrição em seus planos de trabalho.
3. Inserir na descrição da tarefa o código da fonte, código interno do pdf definido por @daniloabrahao, e o código da transcrição que deverá ser usado para salvar na pasta do Copy
4. Inserir o cabeçalho padrão de instruções gerais e específicas (copie o desta tarefa)
5. Definir como milestone o dia 17/09/2013
6. Usar o label 'Edição e segmentação'.

**Comment by ZeRodriguez** [comment]
@msampaio, pelo que vi na pasta, somente o arquivo: 

`IMSLP34491-PMLP77807-monzanis-instructions-for-the-german-flute_1 anotada`
`IMSLP34493-PMLP77807-monzanis-instructions-for-the-german-flute_3 anotada`

Possuem as definições feitas por Danilo, como mostra a imagem.
![sem ttulo](https://f.cloud.github.com/assets/4490953/1102319/2b277b38-1811-11e3-9ce5-4e4b23bd9f6a.png)

Eu devo delegar as transcrições dos dois arquivos, ou somente do primeiro até ser finalizado?
E assim fazendo, qual o critério que eu uso para a quantidade a ser delegada?
Por exemplo, no primeiro arquivo, há `48` obras selecionadas para serem transcritas. Algumas pequenos compassos, e as últimas peças inteiras. Mando 10 obras para um aluno, 15 para outro? Como faço isso?

**Comment by msampaio** [comment]
@ZeRodriguez, comece delegando as obras maiores. Agrupe os fragmentos pequenos de modo a delegar aproximadamente uma pagina de partitura para cada pessoa.
Essa tarefa estará concluída após você delegar todas as transcrições referentes ao Monzani.

**Comment by ZeRodriguez** [comment]
@msampaio, os únicos que não possuem nenhuma tarefa em aberto são Daiana, Luã e Menahem. É para delegar transcrições apenas a eles? Outra coisa, como é que crio uma tarefa?

**Comment by msampaio** [comment]
@ZeRodriguez, comece atribuindo as tarefas a eles, Hugo, Simei e você mesmo. A maioria das tarefas abertas vencem no dia 10, quando você poderá atribuir tarefas aos demais.
Para criar uma tarefa clique em New Issue. Se nāo me engano há um vídeo tutorial na pasta do Copy.

**Comment by daniloabrahao** [comment]
- Transcrições prioritárias:
  - Parte 1: `O47` e `O48`
  - Parte 2: nenhuma
  - Parte 3: `O25`

@ZeRodriguez, a parte 2 do metodo de mozani é composta apenas por duos. Por isso não têm marcações.

**Comment by msampaio** [comment]
@ZeRodriguez, por favor delegue as tarefas o quanto antes para que possamos manter o deadline no dia 17. Inicie com a 'O13', da parte 3, conforme sugestão de @daniloabrahao na tarefa #61.

**Comment by ZeRodriguez** [comment]
@msampaio, tenho só mais uma dúvida. Como me refiro à obra no título da tarefa? Eu escrevo "Fazer Transcrição Diplomática de `O13` do arquivo `IMSLP34493-PMLP77807-monzanis-instructions-for-the-german-flute_3 anotada`?

**Comment by ZeRodriguez** [comment]
E o final dessa `O13` é complicado. Não há barras de compasso como mostra a figura. Certamente o encarregado irá comentar a tarefa com dúvida.
![sem ttulo](https://f.cloud.github.com/assets/4490953/1110728/2969ba3e-1999-11e3-836c-af805b605128.png)

**Comment by msampaio** [comment]
Título da tarefa: Transcrever IF34493 O13
No corpo da tarefa coloque o arquivo que será usado para salvar: IT34493_13.xml.
Preciso testar exatamente este trecho circulado com o Music21.

**Comment by ZeRodriguez** [comment]
@msampaio, já fiz uma. Deleguei `O13` à Luã. Dê uma olhadinha lá pra ver se tá tudo certo pra eu poder continuar.

**Comment by ZeRodriguez** [comment]
@msampaio, uma das peças, a `IF34491_48` eu deleguei à Alisson. Eu sei do problema dele com a internet, mas tivemos juntos hoje no Genos e ele disse que era para eu atribuir uma tarefa pra ele. Ele salvou o pdf no pendrive, assim poderá fazer sem problemas em casa. =D

**Comment by ZeRodriguez** [comment]
Professor, a obra `34493_25` pensei em atribuir para Simei. Mas observando a peça fiquei com dúvida. São caprichos que vão modulando. Com uma olhada rápida, me pareceu que é para ser transcrito as 3 páginas da peça. É isso mesmo? Pode dá uma olhada lá por favor? Abraço.

**Comment by msampaio** [comment]
@ZeRodriguez, renomeei os arquivos fonte do IMSLP para o padrão do nosso código.
Sobre IF34493_25, recomendo que confirme com @daniloabrahao como deverá ser feito. Ao que me parece, cada mudança de andamento e tonalidade representa um movimento diferente.

**Comment by ZeRodriguez** [comment]
@daniloabrahao, você pode confirmar onde é o final da peça `IF34493_25`? A O25 da parte 3.

**Comment by daniloabrahao** [comment]
Eu acredito que o Capriccio Modulato termina aqui:
![image](https://f.cloud.github.com/assets/4681458/1114000/0384ae5e-1a0d-11e3-9fc5-b4a312a88d67.png)

Não sei se cada uma dessas pautas representam um novo movimento não. Mas eu acredito que as 3 paginas são uma obra única que deve ser transcriita na íntegra em um único arquivo.

**Comment by ZeRodriguez** [comment]
Valeu @daniloabrahao.

**Comment by ZeRodriguez** [comment]
@msampaio, as transcrições referentes ao arquivo `IF34491` já foram todas delegadas. Se a tarefa for referente só a esse arquivo, a tarefa está concluída. Mas algumas obras do arquivo `IF34493` também foram delegadas.

**Comment by msampaio** [comment]
Pode fechar essa tarefa
Em 16/09/2013 13:17, "ZeRodriguez" notifications@github.com escreveu:
