### ISSUE TITLE
Testar parseamento de cadenzas

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#61]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Testar o parseamento de trechos de **cadenza** de arquivos xml. Verificar que tipo de informaçāo musical é possível extrair desses trechos.
### Pré-requisitos
1. @daniloabrahao: recomendar um exemplo pequeno de cadenza presente no Monzani.
2. @ZeRodriguez: Priorizar o exemplo a ser indicado por @daniloabrahao ao realizar a tarefa #60.

**Comment by daniloabrahao** [comment]
@msampaio, você tem algum critério para escolha desse exemplo de cadenza? Lembrando que o método possui dois grupos de 6 cadenzas cada (páginas 17 e 18 da parte 3 do método). Se for uma cadenza qualquer, pode ser a primeira: `O13`.

**Comment by msampaio** [comment]
Pode ser qualquer obra curta sem o ritmo muito definido. O objetivo é
testar como o music21 lida com essas situações
Em 08/09/2013 11:10, "daniloabrahao" notifications@github.com escreveu:

**Comment by daniloabrahao** [comment]
Então pode ser a `O13` da parte 3.

**Comment by msampaio** [comment]
Ver Ariza, Cuthbert 2010:
 "The time signature, in cadenzas or in many modern scores, may reflect a multimeasure group or a duration greater or less than that implied by the notes in the bar. A complete software model of meter must account for this diversity.".

Ariza, Christopher, and MS Cuthbert. 2010. “Modeling Beats, Accents, Beams, and Time Signatures Hierarchically with Music21 Meter Objects.” In Proceedings of International Computer Music Conference, 216–223. San Francisco.

**Comment by msampaio** [comment]
Aparentemente o Music21 lida bem com _cadenza_. Extraí apenas o compasso 19 de IF34493_13 sem maiores problemas (vide código abaixo). Abri no Finale Notepad:
![screen shot 2013-10-16 at 19 36 33](https://f.cloud.github.com/assets/1006488/1347648/c9b37728-36b3-11e3-8e1f-0d999305f8a8.png)

O MuseScore não formatou bem, mas abriu sem problemas:
![screen shot 2013-10-16 at 19 35 33](https://f.cloud.github.com/assets/1006488/1347644/be938022-36b3-11e3-8aab-0eeb005528ce.png)

Código do Music21:

```
{48.0} <music21.stream.Measure 19 offset=48.0>
    {0.0} <music21.layout.SystemLayout>
    {0.0} <music21.note.Note F#>
    {0.25} <music21.note.Note G>
    {0.5} <music21.note.Note A>
    {0.75} <music21.note.Note G>
    {1.0} <music21.note.Note F#>
    {1.25} <music21.note.Note E>
    {1.5} <music21.note.Note D>
    {1.75} <music21.note.Note C>
    {2.0} <music21.note.Note B>
    {2.25} <music21.note.Note C>
    {2.5} <music21.note.Note D>
    {2.75} <music21.note.Note C>
    {3.0} <music21.note.Note B>
    {3.25} <music21.note.Note A>
    {3.5} <music21.note.Note G>
    {3.75} <music21.note.Note F#>
    {4.0} <music21.note.Note G>
    {6.0} <music21.note.Note B>
    {6.25} <music21.note.Note A>
    {6.5} <music21.note.Note G>
    {7.0} <music21.note.Note D>
    {7.25} <music21.note.Note C>
    {7.5} <music21.note.Note B>
    {8.0} <music21.note.Note F#>
    {8.25} <music21.note.Note E>
    {8.5} <music21.note.Note D>
    {9.0} <music21.note.Note B>
    {9.25} <music21.note.Note A>
    {9.5} <music21.note.Note G>
    {10.0} <music21.note.Note D>
    {10.25} <music21.note.Note C>
    {10.5} <music21.note.Note B>
    {11.0} <music21.note.Note F>
    {11.25} <music21.note.Note E>
    {11.5} <music21.note.Note D>
    {11.75} <music21.note.Note C>
    {12.0} <music21.note.Note B>
    {12.25} <music21.note.Note A>
    {12.5} <music21.note.Note G>
    {12.75} <music21.note.Note F#>
    {13.0} <music21.note.Note G>
    {13.25} <music21.note.Note G#>
    {13.5} <music21.note.Note B>
    {13.75} <music21.note.Note A>
    {14.0} <music21.note.Note G>
    {14.25} <music21.note.Note F#>
    {14.5} <music21.note.Note E>
    {14.75} <music21.note.Note D>
    {15.0} <music21.note.Note F#>
    {15.25} <music21.note.Note E>
    {15.5} <music21.note.Note G>
    {15.75} <music21.note.Note F#>
    {16.0} <music21.note.Note A>
    {16.25} <music21.note.Note G>
    {16.5} <music21.note.Note B>
    {16.75} <music21.note.Note A>
    {17.0} <music21.note.Note G>
    {17.25} <music21.note.Note F#>
    {17.5} <music21.note.Note E>
    {17.75} <music21.note.Note G>
    {18.0} <music21.note.Note F#>
    {18.25} <music21.note.Note D>
    {18.5} <music21.note.Note C>
    {18.75} <music21.note.Note B>
    {19.0} <music21.note.Note D>
    {19.25} <music21.note.Note C>
    {19.5} <music21.note.Note B>
    {21.5} <music21.note.Note C>
    {22.5} <music21.note.Note C#>
    {23.5} <music21.note.Note D>
    {24.5} <music21.note.Note D#>
    {25.5} <music21.note.Note E>
    {26.25} <music21.note.Note F>
    {26.5} <music21.expressions.TextExpression "D.C. al ">
    {26.5} <music21.bar.Barline style=final>
```

**Comment by msampaio** [comment]
Em função dos testes realizados, acredito que não teremos problemas para com 'IF34493_24'. Fechando tarefa. Após conclusão da tarefa #89, caso haja algum problema no parseamento de _cadenza_, reabrirei esta tarefa.
