### ISSUE TITLE
Definir fonte para transcrição das fantasias de Telemann

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#7]
@robattolucas, preciso que você defina qual exatamente será a fonte que usaremos para transcrever as fantasias de Telemann. Basta inserir o link do IMSLP no comentário desta tarefa.

**Comment by robattolucas** [comment]
A fonte será a edição Musica Rara de Barthold Kujken (1987), que contem o fac-simile da fonte única original, edição moderna e aparato crítico. Esta edição está digitalizada em formato pdf

**Comment by msampaio** [comment]
@robattolucas, esta fonte está disponível no IMSLP? Não encontrei lá. Caso não esteja no IMSLP, você tem cópia em PDF? Caso tenha cópia, pode inserir na pasta `IMSLP` do Copy?
Basta fazer login em [Copy](https://www.copy.com/browse/company-11103/Flauta%20Solo/IMSLP), ir em browse, selecionar a pasta 'shared with me/flauta solo', e depois fazer o upload em IMSLP. Veja a figura abaixo.

![screen shot 2013-08-10 at 19 01 28](https://f.cloud.github.com/assets/1006488/943311/35e74c1a-0209-11e3-9d1e-786db33ed53a.png)

**Comment by msampaio** [comment]
@robattolucas, eu inseri o arquivo que você me enviou por email na pasta IMSLP usando este nome: `EXTRA0001-Telemann - Fantasies flute (with facsimile - Musica Rara)`. Estou fechando esta tarefa.
