### ISSUE TITLE
Compilar ideias de direção para a pesquisa

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#70]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa é compilar todas as ideias referentes à pesquisa em um único lugar, para consulta posterior. Estas ideias estão espalhadas na [lista de email](https://groups.google.com/forum/#!forum/genos-contour) e nos comentários das tarefas.
Um exemplo de ideia pode ser visto [nesta mensagem](https://groups.google.com/forum/#!topic/genos-contour/aKWFJcJ9c2c), onde @robattolucas sugere procurar padrões rítmicos semelhantes em um grupo de danças, ou verificar como o compositor classificou grupos de músicas com padrões rítmicos semelhantes.
O resultado da tarefa deverá salvo na pasta 'Produção', em um arquivo 'Ideias-pesquisa.txt'.

**Comment by daniloabrahao** [comment]
@msampaio, ao compilar as ideias, estou deixando a data, onde a ideia foi encontrada (GoogleGroups ou GitHub) e quem teve a ideia. Mas não sei se devo registrar esta última informação. O que acha?

**Comment by daniloabrahao** [comment]
@msampaio, no GoogleGroups do Genos, a única ideia que encontrei e que achei que devesse ser compilada foi esta que Lucas escreveu. 
No caso, por exemplo, da mensagem: https://groups.google.com/forum/#!topic/genos-contour/tSmhekgXgz0. Devo compilar a ideia do nome para sistema de análise também?

Vou partir para a procura de ideias nos comentários das tarefas.

**Comment by msampaio** [comment]
@daniloabrahao, não precisa colocar o nome do sistema de análise ;-)

**Comment by daniloabrahao** [comment]
Me atrapalhei ao procurar as ideias nos comentários do GitHub. Fiz uma lista em .txt com todas as tarefas para organizar esse volume de informações.

**Comment by msampaio** [comment]
@daniloabrahao, eu renomeei o arquivo para IdeiasProjeto.txt. Veja como está o modelo para poder seguir em frente.

**Comment by daniloabrahao** [comment]
O.K.!

**Comment by daniloabrahao** [comment]
@msampaio, as fiz uma lista das tarefas que possuem ideias que eu acho que devem estar no arquivo. 
                                              [São elas: #6, #11, #12, #28, #38, #46 e #48]

Todavia, algumas dessas ideias já foram documentadas no Manual de Procedimentos no site do Genos. Como é o caso de #11. Neste caso eu devo compilá-las no arquivo `.txt` também?

**Comment by daniloabrahao** [comment]
O código identificador de arquivo tbm deve estar no `IdeiasProjeto.txt`?

**Comment by msampaio** [comment]
@daniloabrahao, você está no caminho certo. Busque focar no que ainda não implementamos, como relação entre danças e padrões rítmicos. Não precisa incluir decisões que tomamos e já implementamos, como código identificador ou critério de escolha de fontes.

**Comment by daniloabrahao** [comment]
@msampaio, já verifiquei todas as tarefas do GitHub e emails do Google Groups e compilei no arquivo as ideias encontrei. Se quiser posso remover do arquivo essas ideias já implementadas, caso contrário a tarefa está concluída.

**Comment by msampaio** [comment]
Bom trabalho, @daniloabrahao. Remova essas ideias implementadas para fecharmos a tarefa ;-)

**Comment by daniloabrahao** [comment]
Concluído.
