### ISSUE TITLE
Delegar as tarefas de transcrição do IMSLP34493 Monzani 1801 

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#74]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em delegar as transcrições das obras indicadas na tarefa #48 para cada um dos colaboradores da pesquisa criando novos **_issues**_ aqui no GitHub.
Para realizar esta tarefa seguir estas recomendações:
1. O colaborador já deverá ter cumprido suas tarefas anteriores. Não delegar tarefa a quem tem trabalho atrasado.
2. Priorizar os colaboradores que têm tarefas de transcrição em seus planos de trabalho.
3. Inserir na descrição da tarefa o código da fonte, código interno do pdf definido por @daniloabrahao, e o código da transcrição que deverá ser usado para salvar na pasta do Copy
4. Inserir o cabeçalho padrão de instruções gerais e específicas (copie o desta tarefa)
5. Definir como milestone o dia 24/09/2013.
6. Usar o label 'Edição e segmentação'.

**Comment by ZeRodriguez** [comment]
@msampaio, não seria os arquivos `IF34492` e `IF34493` ao invés de `IF34491 2` e `IF34491 3`? E quanto ao número 2, não há numeração das obras editadas no `pdf`. @daniloabrahao, havia dito que não as numerou por serem duos de flauta.

**Comment by msampaio** [comment]
@ZeRodriguez, você pode corrigir essas coisas na descrição da tarefa? ;-)

**Comment by ZeRodriguez** [comment]
Posso sim Marcos. Mas então seria só a `IF34493` mesmo? Já que a `IF34492` não está numerada.

**Comment by msampaio** [comment]
Isso

**Comment by msampaio** [comment]
@ZeRodriguez, qual o estado desta tarefa?

**Comment by ZeRodriguez** [comment]
@msampaio, está andando. Mais da metade do livro foi feito. Algumas tarefas demoraram para serem cumpridas, por isso o livro ainda não está concluído. Tenho mais de uma versão do Finale, e a que permite esse tipo de escrita está com problema, por isso não deleguei obras do livro 3 pra mim, redirecionei as tarefas antigas. =D

**Comment by ZeRodriguez** [comment]
@msampaio, todas as transcrições já foram delegadas e de todas as tarefas, restam apenas 3 peças, todas dentro do prazo. Fechando a tarefa! =D

**Comment by msampaio** [comment]
Excelente!
