### ISSUE TITLE
Documentar criação de cadenza no Finale

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#77]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em documentar o procedimento de criação de _cadenza_ no Finale no [handbook](http://genosmus.com/handbook/finale/) do Genos. A criação desta documentação depende da conclusão da tarefa #61. Observe os comentários das tarefas #62 e #76 para saber as dúvidas comuns.

**Comment by msampaio** [comment]
@AlissonGSilva, qual o estado desta tarefa?

**Comment by AlissonGSilva** [comment]
Concluída!
