### ISSUE TITLE
Organizar questões sobre o repertório para flauta solo

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#78]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Na tarefa #46, @robattolucas sugeriu fazermos um brainstorm de questionamentos sobre o repertório para flauta solo. Eu criei o arquivo [QuestoesProjeto.txt](https://www.copy.com/browse/company-11103/Flauta%20Solo/Produ%C3%A7%C3%A3o/QuestoesProjeto.txt) para compilar essas questões. Todos os participantes da pesquisa poderão/deverão colocar questões que têm interesse em saber. Um exemplo de questão seria "o padrão rítmico colcheia pontuada semicolcheia é realmente característico da música francesa para flauta solo?". É fundamental **não** se preocupar com o que é possível fazer com a tecnologia que dispomos. O objetivo deste brainstorm é levantar toda e qualquer questão acerca deste repertório.

A tarefa aqui é organizar a lista de questões à medida que elas forem sendo colocadas. A tarefa só será iniciada após algum volume de questões postadas.

**Comment by SimeiFerreira** [comment]
@msampaio, comentários do @robattolucas já foram movidos na íntegra para o arquivo "QuestoesProjeto.txt" no Copy.

**Comment by msampaio** [comment]
@SimeiFerreira, como esta tarefa se desdobra em várias semanas, precisarei de um comentário semanal atualizando o seu estado.

**Comment by SimeiFerreira** [comment]
@msampaio, as dúvidas como essa #102 deverão ser colocadas no arquivo? Até o presente momento, não observei questões sobre o repertório nas mensagens postadas que o github mandou para o meu email. Devo colocar as questões sobre as próximas obras a transcrever que resultaram na tarefa #107?

**Comment by msampaio** [comment]
@SimeiFerreira, não coloque as dúvidas dos processos de transcrição, expansão e segmentação. Nosso objetivo é formular questões para que, em um passo seguinte, modelemos no software de análise. A ideia é ter perguntas na direção do que David Huron fez e você filtrou na tarefa #92. Essa é nossa contribuição ao esforço interdisciplinar que Volk et alli propõem em seu texto:

Volk, Anja, Frans Wiering, and Peter Van Kranenburg. 2011. “Unfolding the Potential of Computational Musicology.” Proceedings of The13th International Conference on Informatics and Semiotics in Organisations (ICISO): 137–144.

**Comment by SimeiFerreira** [comment]
Certo, não tenho observado perguntas nesse sentido nas postagens da pesquisa aqui no github por enquanto.

**Comment by msampaio** [comment]
@SimeiFerreira, vou fechar a tarefa. Você pode ficar responsável por registrar essas questões sempre que as vir nas mensagens?

**Comment by SimeiFerreira** [comment]
Claro, posso sim.
