### ISSUE TITLE
Definir sintaxe de estrutura formal de obras

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#79]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Definir sintaxe de estrutura formal das obras para flauta solo com base na sintaxe usada na pesquisa sobre [choros](http://genosmus.com/pesquisa/contornos/choro/guia/#Segmentação_formal_das_canções).
A proposta inicial é definir partes, períodos, frases e "não-frases". Para isso é possível aproveitar a sintaxe da pesquisa de choros, com pequenas alterações.
1. Indicação de partes: `# part` no início da parte.
2. Indicação de período: `# period` no início do período.
3. Indicação de frases: `p i f`, onde `i` é o número do evento onde a frase inicia, e `f`, o número do evento onde a frase é finalizada.
4. indicação de "não frases": `n i f`, de forma similar à indicação de frases.

Exemplo da sintaxe:

```
# part
# period
p 1 10
n 10 13
p 13 23

# period
p 23 33
n 33 35
p 35 45
```

Com esta sintaxe definimos uma parte composta de dois períodos, cada um com duas frases separadas por um fragmento "não frase". Este fragmento pode ser, por exemplo, um link, uma extensão, uma introdução, ou qualquer outra estrutura que não seja uma frase.

Todos os eventos da música (notas e pausas) serão enumerados e a análise manual consistirá apenas em registrar os números dos eventos das estruturas. Em caráter ilustrativo, a música da figura abaixo tem a sua análise adiante.

![9be56e64-85a1-11e2-84b5-131438415ca5](https://f.cloud.github.com/assets/1006488/1187610/0f46037e-238a-11e3-8287-7f6d68fb5a78.png)

```
# part
# period
p 3 36
p 38 75

# part
# period
p 78 135
p 137 189

# part
# period
p 192 225
p 227 264

# part
# period
p 266 304
p 306 328

# part
# period
p 331 364
p 366 407
```

Para a conclusão desta tarefa é preciso que @robattolucas e @gbertis concordem com as estruturas registradas nesta proposta de sintaxe. Esta definição irá possibilitar a criação de filtros das estruturas aqui definidas. Por essa razão, tem ligação com a tarefa #78.
Sugestões dos alunos envolvidos no projeto de choros são bem vindas, pois tiveram a experiência de codificar a forma de mais de 200 canções.

**Comment by msampaio** [comment]
@robattolucas e @gbertis, o que vocês acham de registrar as estruturas formais mencionadas nesta tarefa: partes, períodos, frases e "não-frases"?

**Comment by robattolucas** [comment]
Acho que devemos então tentar encontrar uma definição mínima comum para
estes termos. Definições que possam ser facilmente aplicáveis.

Alguma sugestão?

**Comment by msampaio** [comment]
Boa ideia, @robattolucas. Eu recomendo usar essas definições para frase e período.
1. **Frase**: "A phrase is the shortest passage of music which, having reached a point of relative repose, has expressed a more or less complete musical thought." P. 7. 
   Green, Douglass M. 1979. Form in tonal music: An introduction to analysis. Holt Rinehart and Winston.
2. **Período**: "A period normally consists of two phrases, an antecedent and a consequent. Three- and four phrase periods are expansions of an essentially binary structure. The antecedent phrase (Ant. Phr.), often compared to a question, is complete in itself. It needs, however the fulfillment provided by the complementing or answering consequent phrase (Cons. Phr.). If the question and answer are to be coherent, valid, and mutually necessary, they must deal with a single subject or idea; and the answer must provide a satisfactory solution to the problem posed in the question." p. 55.
   Kohs, Ellis B. 1976. Studies in analysis and synthesis. Boston: Houghton Mifflin.

Ainda não tenho certeza se devemos usar o termo **parte** ou seção. Estamos nos referindo às pequenas formas das composições. Certamente não é o conceito definido por William Drabkin no Grove (Part III), que assume como parte uma divisão equivalente ao dos atos das peças de teatro.

Green (p. 71) diz que uma parte pode ser composta por uma ou várias frases, um ou vários períodos. Acho que não precisamos distinguir períodos de cadeias ou grupos de frases. Por isso acho suficiente essa proposta inicial de subdivisões formais.

**Comment by SimeiFerreira** [comment]
@msampaio, devo colocar as questões aqui abordadas no arquivo "QuestoesProjeto.txt" no Copy?

**Comment by msampaio** [comment]
Sim.

On Wednesday, October 9, 2013, SimeiFerreira wrote:

> @msampaio https://github.com/msampaio, devo colocar as questões aqui
> abordadas no arquivo "QuestoesProjeto.txt" no Copy?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/79#issuecomment-25946575
> .

## 

Sent from my Mobile

**Comment by SimeiFerreira** [comment]
@msampaio, coloquei apenas as questões, vide: 
- @robattolucas e @gbertis, o que vocês acham de registrar as estruturas formais mencionadas nesta tarefa: partes,
  períodos, frases e "não-frases"?
- @robattolucas commented: Acho que devemos então tentar encontrar uma definição mínima comum para estes termos.
  Definições que possam ser facilmente aplicáveis. Alguma sugestão?

As respostas às mesmas que definiram as diretrizes relativas à forma eu não coloquei no arquivo, deveria ter colocado?

**Comment by msampaio** [comment]
@SimeiFerreira, eu respondi pelo celular e acabei não vendo o conteúdo dos comentários desta tarefa. Estas perguntas não entram em QuestoesProjeto.txt. A ideia é usar esse arquivo para colocarmos as questões que temos em relação às músicas. Por exemplo, se um compositor usa um padrão rítmico. Eu removi as perguntas do arquivo.

**Comment by SimeiFerreira** [comment]
Entendi, tranquilo então =)

---

 De: Marcos da Silva Sampaio notifications@github.com
Para: GenosResearchGroup/FlautaSolo FlautaSolo@noreply.github.com 
Cc: SimeiFerreira soulluz@yahoo.com.br 
Enviadas: Quarta-feira, 9 de Outubro de 2013 17:48
Assunto: Re: [FlautaSolo] Definir sintaxe de estrutura formal de obras (#79)

@SimeiFerreira, eu respondi pelo celular e acabei não vendo o conteúdo dos comentários desta tarefa. Estas perguntas não entram em QuestoesProjeto.txt. A ideia é usar esse arquivo para colocarmos as questões que temos em relação às músicas. Por exemplo, se um compositor usa um padrão rítmico. Eu removi as perguntas do arquivo.

**Comment by msampaio** [comment]
Esta tarefa depende de uma escolha de conceitos sobre os elementos formais da composição. @ZeRodriguez está responsável pelo levantamento de conceitos e iniciou este trabalho na tarefa #91.
