### ISSUE TITLE
Editar vídeo da palestra sobre Edição Musical

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#8]
Editar vídeo palestra de Lucas Robatto sobre edição musical e salvar na pasta `Vídeos`, no Copy.

**Comment by msampaio** [comment]
@SaraFadigas, qual o estado desta tarefa?

**Comment by SaraFadigas** [comment]
3 das 4 partes do video já foram convertidas. A partir daqui só resta um trabalho de corte e renderizacao.

**Comment by SaraFadigas** [comment]
Como faço pra postar o video na conta do Youtube do GENOS?

**Comment by SaraFadigas** [comment]
As duas partes estão prontas. O video da palestra ficou com 685.212KB e o Bloco de perguntas ficou com 903.674KB. Só falta postar agora. Posto no Copy mesmo, ou espero pra postar no Youtube?

**Comment by msampaio** [comment]
Aguarde enquanto configuro a conta do Genos no Youtube

**Comment by msampaio** [comment]
@SaraFadigas, te coloquei como gerente da conta do Genos no Google Plus. Veja se consegue enviar o vídeo para o canal do Genos no Youtube por aí.

**Comment by SaraFadigas** [comment]
Já estou enviando o video.
Vou postar os dois, o video da palestra e o bloco de perguntas, pode ser?

Date: Wed, 21 Aug 2013 08:59:58 -0700

**Comment by msampaio** [comment]
Pode postar os dois. Coloque os links aqui.

**Comment by SaraFadigas** [comment]
Eu pensei em associar os links na ata da palestra.
O que o senhor acha?

**Comment by SaraFadigas** [comment]
Tipo assim Professor: http://genosmus.com/?p=2780&preview=true
Veja se dá pra visualizar mesmo estando sem publicar ainda.

**Comment by msampaio** [comment]
@SaraFadigas, bom trabalho. Eu fiz edições nas páginas dos vídeos no YouTube e no post da ata. Tenho alguns comentários:
1. Nos vídeos sempre use como título o nome da palestra, e não o nome do professor. Você inclui o nome do ministrante na descrição do vídeo.
2. Nos próximos vídeos insira uma pequena apresentação com o nome do vídeo, do palestrante, a informação de que aquela é uma atividade do Grupo de Pesquisa Genos, o link para a página do Genos, e o símbolo do Genos (preferencialmente em tamanho reduzido em todo o vídeo).
3. Na ata especifique exatamente quem participou da palestra.
4. Na ata busque simplificar as informações. Por exemplo, não precisa mencionar todos os termos apresentados. Basta colocar "terminologia".

Logomarca do Genos:
![logomarca-genos](https://f.cloud.github.com/assets/1006488/1007826/e807c472-0b11-11e3-916a-c45bf5949690.png)
