### ISSUE TITLE
Ler livro Música Eletrônica: uma introdução ilustrada

### ISSUE THREAD

**Issue by ZeRodriguez** [msampaio/flauta-solo#83]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas
- Ler todo o livro "Música Eletrônica: uma introdução ilustrada" de Eloy Fritsch
- Estudar capítulos `11` à `15`
- Fazer compilação em tópicos

Tarefa criado a pedido de @gbertis

**Comment by AlissonGSilva** [comment]
Concluída!

**Comment by msampaio** [comment]
@AlissonGSilva, onde você colocou a compilação em tópicos?

**Comment by AlissonGSilva** [comment]
Fiz Marcos, só que não formatei ainda no Word.
Ela ta escrita a mão; estou com ela aqui agora esperando Guilherme pra uma reunião hoje, ele e Menahem.
A compilação era pra  Menahem, e pra reunião. Mas vou editar ela no Word, ainda hoje ou amanhã e postar  no copy em bibliografia.

**Comment by msampaio** [comment]
Beleza. Lembrando que é no Copy Produção ;-)
