### ISSUE TITLE
Ler livro Designing Sound

### ISSUE THREAD

**Issue by ZeRodriguez** [msampaio/flauta-solo#84]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas
- Ler todo o livro "Designing Sound" de Andy Farnell
- Estudar capítulos `09` e `10`
- Fazer compilação em tópicos

Tarefa criado a pedido de @gbertis

**Comment by AlissonGSilva** [comment]
Menahem também já terminou, iremos trocar os livros!

**Comment by menahemhein** [comment]
Eu não tinha escrito ainda porque não tinha ainda trocado os livros, mas acabei !
