### ISSUE TITLE
Escrever resenha de Chakraborty et al. - A Statistical Analysis...

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#85]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa é escrever a resenha do artigo abaixo. Focar na metodologia estatística usada para alcançar os resultados.

Chakraborty, Soubhik, Rayalla Ranganayakulu, Shivee Chauhan, Sandeep Singh Solanki, and Kartik Mahto. 2009. “A Statistical Analysis of Raga Ahir Bhairav.” Journal of Music and Meaning 8: 1–9.

**Comment by SaraFadigas** [comment]
tarefa concluida

**Comment by msampaio** [comment]
Você colocou o arquivo no Copy?

**Comment by SaraFadigas** [comment]
sim.

Date: Thu, 10 Oct 2013 09:06:54 -0700
