### ISSUE TITLE
Baixar artigos da pesquisa

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#86]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa é baixar os artigos da lista seguinte. É preciso ter acesso ao [portal de periódicos da CAPES](http://periodicos.capes.gov.br) para baixá-los. Então, só é possível baixá-los de um computador ligado à rede UFBA.
Os artigos devem ser inseridos no Mendeley da pesquisa, e na pasta Bibliografia, no Copy, com o padrão "Primeiro autor - Ano - Título.pdf".
1. http://link.springer.com/article/10.1007%2FBF01830711
2. Towards a Distributed Research Environment for Music Informatics and Computational Musicology
3. Computational Musicology in Italy
4. Researchers at University of Ulster Have Published New Data on Language and Communication Science
5. A computer-aided analysis of Anglo-Canadian folktunes
6. Empirical Musicology: Aims, Methods, Prospects.(Statistics in Musicolog)(Book review)
7. Analysing Emotions in Schubert's Erlkönig: a Computational Approach
8. http://onlinelibrary.wiley.com/doi/10.1002/aris.1440370108/abstract
9. Modeling and Searching Music Collections
10. http://onlinelibrary.wiley.com/doi/10.1002/9780470050118.ecse722/abstract

**Comment by AlissonGSilva** [comment]
Faltaram 2 artigos,  o "Modeling and Searching Music Collections" não achei no portal da CAPES, achei em outro lugar, mas preciso fazer cadastro/pagar para baixar.
E o outro foi o "Computer Music Composition/Analysis" do David Cope, no portal da CAPES ele não existe nas buscas, fui nesse link que você postou, mas ele pede um cadastro.

Esse "Researchers at University of Ulster Have Published New Data on Language and Communication Science" ele está como artigo de jornal, não tem o nome de autor, e o formato que deixam baixar o texto full é HTML, não tem em PDF.

Postei na pasta Bibliografia no Copy. Vou inserir no Mendeley.

**Comment by AlissonGSilva** [comment]
Não sei se é normal, mas as vezes, quando pesquisei no portal esses artigos, eu pedia pra repetir a pesquisa,  aparecia uma menssagem: " Ocorreu um erro inesperado." !!! Em um computador na rede da UFBA.

**Comment by msampaio** [comment]
Ótimo, @AlissonGSilva. Sobre o arquivo em html, insira o link no Mendeley. Você sempre pode "imprimir" a página html em um arquivo pdf ;-)

**Comment by AlissonGSilva** [comment]
Pronto, já inseri no Mendeley!
Esse do html não achei nada sobre o autor.

**Comment by msampaio** [comment]
Massa. Vou fechar a tarefa.

**Comment by AlissonGSilva** [comment]
Talvez artigo interessante para pesquisa:
http://www.jstor.org/discover/10.2307/1576078?uid=3737664&uid=2&uid=4&sid=21102804140843

**Comment by msampaio** [comment]
Ótimo. Baixe na escola, coloque no Copy e crie uma entrada no Mendeley.
