### ISSUE TITLE
Escrever resumo do evento Oportunidades e Desafios da Extensão Universitária

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#9]
Assistir palestra "Oportunidades e Desafios da Extensão Universitária" e escrever um resumo sobre os pontos principais tratados. Ver modelos de documentos no manual da pesquisa.

Palestra inaugural do Ciclo de Seminários  “Extensão: a Bola da Vez”, proferida pelo Professor Eduardo Sílvio Sarmento Lyra, Coordenador do Fórum de Pró-Reitores de Extensão Universitária do Nordeste.
DATA: 14 de agosto de 2013
HORÁRIO: 14 horas
LOCAL: Auditório do Instituto de Matemática
ENDEREÇO: Campus Universitário de Ondina.

**Comment by ZeRodriguez** [comment]
Tranquilo @msampaio. @AlissonGSilva se disponibilizou e também assistirá à palestra comigo.

**Comment by msampaio** [comment]
Ótimo. Quando vocês concluirem a tarefa podem fechar aqui.

**Comment by msampaio** [comment]
@ZeRodriguez e @AlissonGSilva, como vocês viram no email, este é um evento que vai até dezembro. Algum de vocês pode participar para poder ter uma visão de todo? Há mais informações neste link:
http://www.extensaoaboladavez.ufba.br/

**Comment by ZeRodriguez** [comment]
@msampaio, dei uma olhada no folder da programação. Para eu participar, preciso me inscrever? Ou a inscrição é só para poder receber o certificado? São 5 palestras, uma por mês. A do dia 3 de setembro, teria que ver com minha professora, porque tomaria um pouco do horário da aula dela. Mas acredito ser possível. O problema é que seria a última aula do semestre. Quanto às palestras dos meses de novembro e dezembro, não sei como ficará meu horário, já que será outro semestre. Mas acredito ser possível também. Me tire só essa dúvida quanto à inscrição.

**Comment by msampaio** [comment]
@ZeRodriguez, eu não sei informar sobre a inscrição. @AlissonGSilva poderia ir a essas palestras?

**Comment by AlissonGSilva** [comment]
A todas eu não sei, essa mesmo do dia 03 de setembro cai numa terça-feira, tenho aula de Acústica e depois de Musica Computacional com Guilherme.
Mas vou tentar ir em todas.

**Comment by ZeRodriguez** [comment]
@msampaio, palestra assistida por mim e @AlissonGSilva. Tomamos nota do que foi dito. Vamos rever e passar a limpo, e por fim, redigirei um único texto para ser postado. De antemão, digo que a palestra de hoje foi centrada na questão do que é extensão, a política do processo. Acredito que para entendermos melhor, será realmente necessário atender à outras palestras. Se lhe interessar, a professora Angela Luhning participou da palestra com comentários interessantes.

**Comment by msampaio** [comment]
Bom trabalho, @ZeRodriguez e @AlissonGSilva. Faça um relato simplificado do conteúdo da palestra e salve na pasta `Produção`. Nas próximas palestras foque no que pode ser interessante para os objetivos do Genos, de equilíbrio entre produção artística, teórica, educacional e mercadológica.

**Comment by ZeRodriguez** [comment]
Entendido!

**Comment by msampaio** [comment]
@ZeRodriguez, estou só no aguardo do seu relatório no Copy para fechar essa tarefa. Veja o exemplo do documento que Simei postou lá.

**Comment by ZeRodriguez** [comment]
@msampaio, o exemplo de Simei seria o relatório referente à Alda na pasta `Produção`? Vi e finalmente entendi. Estou a espera das anotações de @AlissonGSilva, para que possa compilar com as minhas e resumir. Como é um texto, ele pode me enviar pela internet. Assim, posso terminar essa semana a tarefa.

**Comment by msampaio** [comment]
@ZeRodriguez, recomendo que @AlissonGSilva escreva esse texto direto no Copy. Você pode editar lá ;-)

**Comment by ZeRodriguez** [comment]
@msampaio, tarefa concluída. Postarei o arquivo `.txt`na pasta `Produções` no Copy. No entanto, peço-lhe que leia e faça as correções necessárias antes que ele seja publicado no site. Gostaria também de ressaltar, que essa primeira palestra serviu apenas de introdução. Foram levantados problemas e desafios encontrados pela extensão,e  foi mostrado que há projetos em trâmite para serem aprovados pelos órgãos públicos. Acredito que possíveis soluções e medidas mais práticas serão tratados nas próximas palestras, já que serão discutidos programas como "ACCS", "Núcleo de Extensão", "PIBIEX" e "PROEXT/MEC". Assim, o texto apenas tratou do conceito de extensão e de desafios impostos pela legislação ou a falta de.

**Comment by ZeRodriguez** [comment]
Outra dúvida é sobre o autor. A palestra foi ministrada pelo Prof. Eduardo Lyra. Mas o texto é uma compilação das anotações de Alisson e das minhas. Assim, coloquei nossos nomes como autor. Gostaria de saber se estou certo, e se não há como criar outro código como "palestrante", para que eu possa inserir o nome do professor.

**Comment by SimeiFerreira** [comment]
@msampaio, tomei a liberdade de colocar o texto produzido por @ZeRodriguez e @AlissonGSilva nos mesmos parâmetros solicitados para a resenha que escrevi.

**Comment by msampaio** [comment]
@ZeRodriguez, @AlissonGSilva e @SimeiFerreira, bom trabalho. Eu apenas inseri a informação sobre o palestrante e renomeei o arquivo. Vejam como ficou. Tarefa concluída.
