### ISSUE TITLE
Escanear Beyond computational musicology

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#90]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa é escanear o capítulo da referência abaixo no Laboratório de Musicologia (Lucas tem a chave). O livro está na bancada do GenosLab.

Kugel, Peter. 1992. “Beyond computational musicology.” In Understanding music with AI: perspectives on music cognition, 30–48. Cambridge, MA, USA: MIT Press.

**Comment by AlissonGSilva** [comment]
Tarefa concluída; @msampaio olhe se ficou num nível satisfatório de visualização. Além de meu scanner não ser o melhor que existe, eu evito causar algum atentado a integridade física do livro.  
Ta na pasta Bibliografia no copy. 
Nome do arquivo é "Kugel, Peter. 1992. - In Understanding music with AI - Chapter 2"
