### ISSUE TITLE
Levantar bibliografia sobre forma

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#91]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa é listar uma bibliografia para buscar conceitos de estrutura formal como proposto por @robattolucas na tarefa #79.

**Comment by ZeRodriguez** [comment]
@msampaio, comentarei aqui algumas dúvidas que possam surgir, principalmente de termos técnicos em inglês que eu não encontre na internet ou que a solução não seja satisfatória. Já comecei a ler e fazer meu próprio "brainstorm" por escrito.

**Comment by msampaio** [comment]
Ótimo, @ZeRodriguez. Recomendo que use um documento em Produção, no Copy, para fazer esse brainstorm.

**Comment by ZeRodriguez** [comment]
@msampaio, as notas que você me enviou são apenas recortes de autores, não é isso? Ou há alguma definição de sua autoria?

**Comment by msampaio** [comment]
Sim, sāo citações.

On Tuesday, October 8, 2013, ZeRodriguez wrote:

> @msampaio https://github.com/msampaio, as notas que você me enviou são
> apenas recortes de autores, não é isso? Ou há alguma definição de sua
> autoria?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GenosResearchGroup/FlautaSolo/issues/91#issuecomment-25939564
> .

## 

Sent from my Mobile

**Comment by ZeRodriguez** [comment]
@msampaio, eu sei que ficaria inviável pela quantidade, mas você não acha que seria válido eu ler alguns desses livros por inteiro? Se sim, quais você aconselharia? Eu levo a sério esse negócio de ser especialista! Hahaha...

**Comment by msampaio** [comment]
Por enquanto acho que não vale a pena ler por inteiro. Gosto do Green e Kohs. Eles se complementam.

**Comment by msampaio** [comment]
Aqui está minha bibliografia de forma. Peça a @menahemhein para registrar as referências que você for usar no Mendeley. Coloque APENAS as que for usar ;-)

Abromont, Claude e de Montalembert, Eugène. Guide des formes de la musique occidentale. Broché, 2010.
Bekker, Paul. The Story of Music: An Historical Sketch of the Changes in Musical Form. Reprint Services Corporation, 1990.
Benjamin, Thomas; Horvit, Michael e Nelson, Robert. Techniques and Materials of Tonal Music [$73,00].
Bent, Ian. Music Analysis in the Nineteenth Century: Volume 1, Fugue, Form And Style: MUSIC ANALYSIS IN THE 19TH CENTURY. Cambridge University Press, 2004.
Berry, Wallace. Form in Music, 2nd Edition. [$92,00].
Breitkopf and Hartel. Manual of Musical Form. Bibliolife (?).
Burkhart, Charles. Anthology for Musical Analysis, 5a ed. Fort Worth: Harcourt Brace, 1994.
Caplin, William E. (e outros). Musical Form, Forms & Formenlehre: Three Methodological Reflections (Studies in Musical Form) [$35,00].
Cook, Nicholas. A Guide to Musical Analysis. Oxford: Oxford University Press, 1994.
Davie, Cedric T. Musical Structure and Design [$10,00].
Dicks, Ernest Alfred. A Handbook Of Examinations In Music - Containing 650 Questions: with Answers, in Theory, Harmony, Counterpoint, Form, Fugue, Acoustics, Musical History…Nabu Press, 2010.
Ferrara, Lawrence. Philosophy and the Analysis Of Music: Bridges to Musical Sound, Form, and Reference.  GREENWOOD PRESS,1991.
Green, Douglass. Form in Tonal Music. An Introduction to Analysis. Chicago: Halt, Rinehart & Winston, 1979. [$114,00].
Hepokoski, James e Darcy, Warren. Elements of Sonata Theory: Norms, Types, and Deformations in the Late-Eighteenth-Century Sonata [$46,00].
Hutcheson, Jere T. Musical Form & Analysis. Taplinger Publishing.
Kohs, E. B. Musical Form: Studies in Analysis and Synthesis. Boston: Houghton Wifflin, 1976.
Laitz, Steven G . Graduate Review of Tonal Theory: A Recasting of Common-Practice Harmony, Form, and Counterpoint. Oxford University Press, 2009.
Leichtentritt , Hugo. Musical Form. Harvard University Press.
Lester, Joel. Compositional Theory in the Eighteenth Century [$38,00].
Lewin, David. Musical Form and Transformation: Four Analytic Essays. Oxford University Press, 2007.
Lidov , David . Is Language a Music?: Writings on Musical Form and Signification. Indiana University Press, 2004.
Marks, Helena. The Sonata, Its Form & Meaning As Exemplified in the Piano Sonatas by Mozart: a Descriptive Analysis with Musical Examples. 1980.
Mathes,  James R. The Analysis of Musical Form. Pearson Education, 2006.
McClary, Susan . Conventional Wisdom: The Content of Musical Form
Porter , Eleanor H. The Story of Music an Historical Sketch of the Changes in Musical Form. IndyPublish, 2005.
Prout, Ebenezer. Musical form. University Press of the Pacific, 2005.
Rosen, Charles. Sonata Forms. New York: W. W. Norton, 1985. [Edição revista, 1988.]
Spencer, Peter e Temko, Peter M. Practical Approach to the Study of Form in Music [$30,00].
Spring, Glenn  e  Hutcheson, Jere. Musical Form and Analysis [$86,00].
Stein, Leon. Anthology of Musical Forms [$130,00].
Stoïanova, Ivanka. Manuel d'analyse musicale: Les formes classiques simples et complexes. Broché, 1996.
_______ Manuel d'analyse musicale : variations, sonates, formes cycliques. Broché, 2000.
Tenney, James. Meta-Hodos & META Meta-Hodos: A Phenomenology of 20th Century Musical Materials & an Approach to the Study of Form. Frog Peak Music, 
Tobin, Joseph R. How to Understand Musical Form: Music Book Index. Reprint Services Corporation, 1993.
Turek, Ralph. Analytical Anthology of Music [Spiral-Bound, $92,00]
______The Elements of Music: Concepts and Applications, Vol. I [Plastic Comb, $102,00].
Tymoczko, Dmitri. A Geometry of Music: Harmony and Counterpoint in the Extended Common Practice (Oxford Studies in Music Theory) [$34,00].
Tyndall , Robert E. Musical Form. Greenwood Publishing, 1977.
Wade-Matthews, Max. The History of Musical Instruments and Music-Making: A Complete History of Musical Forms and the Orchestra. Annes, 2010.

**Comment by menahemhein** [comment]
Já estou aguardando !

**Comment by msampaio** [comment]
@ZeRodriguez, como esta tarefa se desdobra em várias semanas, precisarei de um comentário semanal atualizando o seu estado.

**Comment by ZeRodriguez** [comment]
Entendido fessô.

**Comment by ZeRodriguez** [comment]
@menahemhein , uma referência para você registrar no Mendeley:
Musical Form and Analysis: Time, Pattern, Proportion. Por Glenn Spring,Jere Hutcheson
Valeu!

**Comment by msampaio** [comment]
@ZeRodriguez, passe o link do livro para @menahemhein pegar as informações.

**Comment by msampaio** [comment]
@ZeRodriguez, qual o estado desta tarefa? Lembre-se que é apenas fazer o levantamento de itens bibliográficos. Precisamos encerrá-la para seguir em frente.

**Comment by ZeRodriguez** [comment]
@menahemhein , segue o link do livro.
http://books.google.com.br/books?id=vQlhAQAAQBAJ&lpg=PP1&ots=dbv7dfRyyq&dq=%22melodic%20contour%22&lr=lang_en&pg=PP1#v=onepage&q=%22melodic%20contour%22&f=false

**Comment by ZeRodriguez** [comment]
@msampaio , na próxima reunião terei um material mais concreto para falar sobre a tarefa. =D

**Comment by ZeRodriguez** [comment]
@msampaio , amanhã tenho uma material mais concreto para apresentá-lo.

**Comment by SimeiFerreira** [comment]
@ZeRodriguez, não sei se estou entendendo errado, mas se você pretende falar sobre o conteúdo da tarefa #91 na reunião amanhã, devo lhe avisar que a mesma fora cancelada:

![email](https://f.cloud.github.com/assets/3719195/1423090/4b6c0564-4005-11e3-8c11-1f9c4d65af7f.png)

**Comment by msampaio** [comment]
@ZeRodriguez, qual o estado deste levantamento de bibliografia? Preciso encerrar essa tarefa para seguir em frente.

**Comment by menahemhein** [comment]
O Musical analysis and form, foi colocado !

**Comment by ZeRodriguez** [comment]
@msampaio , como acordamos ontem, tarefa concluída!
