### ISSUE TITLE
Coletar questões de pesquisa do Humdrum

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#92]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Coletar exemplos de questões musicalmente interessantes e aplicáveis ao nosso estudo a partir da lista em http://humdrum.org/Humdrum/problems.html.
A lista contém perguntas com menor interesse, como "Count the number of barlines in a work", e com maior interesse, como "Determine whether notes at the ends of phrases tend to be longer than notes at the beginnings of phrases."
Há diversas perguntas que não se aplicam por trabalharmos com instrumento solo

**Comment by SimeiFerreira** [comment]
@msampaio, eis as questões que considerei mais aplicáveis à pesquisa:
- Amalgamate arpeggios into chords and display as notation.
- Annotate a score identifying possible cadential 6-4 chords.
- Are dynamic swells (crescendo-diminuendos) more common than dips (diminuendos-crescendos)?
- Calculate all the permuted harmonic intervals in a chord.
- Calculate harmonic intervals between concurrent parts.
- Calculate harmonic intervals in semitones.
- Calculate implied harmonic intervals between parts.
- Classify cadences as either authentic, plagal or deceptive.
- Classify flute fingering transitions as either easy, moderate, or difficult.
- Compare Beethoven's use of dynamic marking with Brahms's.
- Compare pitch-class sets used at the beginnings of slurs/phrases versus those used at the ends of slurs/phrases.
- Count the number of ascending major sixth intervals that occur in phrases that end on the dominant.
- Count the number of notes in a work that belong to the same whole-tone set.
- Count the number of phrases in a score.
- Count the number of phrases that begin on the subdominant pitch.
- Count the number of phrases that end on the subdominant pitch.
- Determine how frequently ascending melodic leaps are followed by descending steps.
- Determine the most common rhythmic pattern spanning a measure.
- Determine whether a work tends to begin quietly and end loudly, or vice versa.
- Determine whether any arpeggios form an augmented sixth chord.
- Determine whether semitone trills tend to be longer or shorter than whole-tone trills.
- Determine whether the first pitch in a phrase is lower than the last pitch in the phrase.
- Determine whether the initial phrase in a work tends to be shorter than the final phrase.
- Determine whether tonic pitches tend to be followed by a greater variety of melodic intervals than precedes it.
- Do lower pitches tend to be quieter and higher pitches tend to be louder?
- Expand repeats to a `through-composed' version of the score.
- Find all scores containing passages in any minor key.
- Find all scores containing passages in C major.
- Find all scores written in compound meters.
- Find all works composed between 1805 and 1809. (Revisar o período que estamos pesquisando)
- Find all works that contain a change of key and a change of meter.
- Find all works that contain a change of key.

Continua...

**Comment by msampaio** [comment]
@SimeiFerreira, como falei, crie um arquivo QuestoesHumdum.txt no Copy para colocar essas perguntas.

**Comment by SimeiFerreira** [comment]
Tarefa concluída!
