### ISSUE TITLE
Verificar intervalos nas fantasias de Telemann

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#93]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Verificar intervalos nas fantasias de Telemann (`ET00001...`). Em uma rápida verificação encontrei intervalos de até 24 semitons ascendentes e descendentes. Na lista abaixo há intervalos maiores que 20 semitons. Verifique se isso está correto.
1. ET00001_01aE.xml
2. ET00001_02bE.xml
3. ET00001_03aE.xml
4. ET00001_06bE.xml
5. ET00001_07aE.xml
6. ET00001_08aE.xml

**Comment by daniloabrahao** [comment]
@msampaio,  devo verificar só na lista acima ou em em todos os arquivos referentes às fantasias?
É só verificar no olho mesmo ou prefere que eu faça algo escrito? Por exemplo, uma lista incluindo as fantasias e seus respectivos intervalos de maior tamanho.

**Comment by msampaio** [comment]
@daniloabrahao, basta passar olhar e informar aqui se está tudo ok ou não. Basta olhar esses arquivos, pois são os que têm intervalos maiores que 20 semitons. Não precisa listar os intervalos de maior tamanho manualmente. O MusiAnalysis faz isso ;-)

**Comment by daniloabrahao** [comment]
Correto, @msampaio. Na lista acima encontrei intervalos grandes de até 24 semitons. Dentre esses intervalos grandes a maioria são compostos por 15 e 16 semitons (10ªM e 10ªm).

**Comment by msampaio** [comment]
Ótimo, @daniloabrahao. Fechando tarefa.
