### ISSUE TITLE
Elaborar objeto/patch PD com cadeia de Markov pequena

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#94]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

@gbertis, conforme falamos por telefone, a ideia é elaborar um objeto/patch do PD com uma cadeia de Markov pequena, com 3 entradas e 3 saídas. Irei verificar como é possível gerar uma cadeia programaticamente. Se possível faça uma cadeia sem repetição de números:

```
1 2 3
4 5 6
7 8 9
```

**Comment by msampaio** [comment]
@AlissonGSilva, estou atribuindo esta tarefa a você, conforme combinamos hoje na escola.

**Comment by gbertis** [comment]
@msampaio, estou finalizando uma cadeia de Markov a partir da nossa reunião de ontem. Vou te enviar ainda hoje.

**Comment by gbertis** [comment]
Tarefa concluída. Criei uma pasta Markov no copy, na parta PureData. Lá tem um patch do pd, cuja matrix está no objeto matrix1.coll, que é a lista da cadeia de markov. Podemos colocar qualquer lista. O arquivo markov.png é uma tabela com a cadeia implementada.
