### ISSUE TITLE
Criar entrada para Kugel 1992 no Mendeley

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#95]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Criar entrada para o artigo de Kugel no Mendeley. (continuação da tarefa #90)
Kugel, Peter. 1992. “Beyond computational musicology.” In Understanding music with AI: perspectives on music cognition, 30–48. Cambridge, MA, USA: MIT Press.

**Comment by menahemhein** [comment]
Criada !

**Comment by msampaio** [comment]
@menahemhein, observe que você não colocou o nome do períodico do artigo. Já corrigi.

**Comment by menahemhein** [comment]
Ok !
