### ISSUE TITLE
Definir próximas fontes a transcrever

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#96]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em decidir com @robattolucas e Marina uma obra ou conjunto de obras para transcrevermos. É necessário definir pelo menos a primeira obra, para atribuirmos tarefas ao resto da equipe.

**Comment by daniloabrahao** [comment]
Eu baixei previamente as fontes de:

Tromilitz (1791)
Op. 7 L'art de Préluder (1719)
Elegant Extracts for the Flute or Violin (1794)

Já que já trabalhamos com um método, talvez seja o caso de transcrevermos a terceira opção, que é uma obra anônima. @msampaio e @robattolucas, o que vocês acham?

**Comment by msampaio** [comment]
@daniloabrahao, acho boa a ideia de transcrever uma obra anônima. Se @robattolucas, peço que escolha uma e, caso necessário, identifique os movimentos no PDF como você vem fazendo.
@ZeRodriguez, assim que @daniloabrahao identificar os movimentos no PDF, pode delegar as tarefas de transcrição para a equipe. Dê preferência a @luanpiano e @DaianaMaciel.

**Comment by daniloabrahao** [comment]
Conversei com @robattolucas e ele teve a ideia de trabalhar com os Prelúdios de Hotteterre. Neste caso, são obras compostas para flauta (flauta de uma chave) por um flautista. Acho que isso é bem relevante.

**Comment by msampaio** [comment]
Entāo siga em frente. Salve os arquivos do IMSLP e gere o pdf anotado.

**Comment by daniloabrahao** [comment]
Ok!

**Comment by daniloabrahao** [comment]
Obra definida:
"L'art de Préluder" de Hotteterre.
Identificação de obras no PDF em andamento.

**Comment by daniloabrahao** [comment]
Ainda estou identificando as obras e detectei alguns problemas. Vou expor depois, mas se @ZeRodriguez  já quiser delegar tarefas, já têm 70 obras identificadas.

**Comment by msampaio** [comment]
Ótimo, @daniloabrahao.
@ZeRodriguez, pode seguir em frente.

**Comment by daniloabrahao** [comment]
@ZeRodriguez, tenha o cuidado de informar na descrição das tarefas que a clave usada é a de  Sol na primeira linha.
E também que a divisão de compassos acontece de forma diferente:
![image](https://f.cloud.github.com/assets/4681458/1366366/47ad433c-38cd-11e3-8582-330bce467032.png)

@msampaio, existe uma dissertação de mestrado da USP sobre o "L'art de Preluder" que Lucas me apresentou que    possui a tradução do livro original de Hotteterre. Está sendo muito útil pra mim. Você quer que eu coloque na pasta de bibliografia?

**Comment by ZeRodriguez** [comment]
Certo... Valeu @daniloabrahao !

**Comment by msampaio** [comment]
@ZeRodriguez , por favor crie uma tarefa para você mesmo para delegar as tarefas dessa coleçāo.
Conforme @daniloabrahao falou, lembre ao pessoal que é preciso transpor a clave para a segunda linha.

**Comment by ZeRodriguez** [comment]
Certo. @msampaio, olhe a tarefa #101 e me diga se o modelo está correto.

**Comment by msampaio** [comment]
Apenas adicione a informaçāo que a transcriçāo deverá estar na clave de sol na segunda linha.

**Comment by ZeRodriguez** [comment]
Certo, entendi.

**Comment by daniloabrahao** [comment]
O livro de Hotteterre é composto em sua maior parte por Prelúdios e "Traits" (do francês: Traço). Já identifiquei todos eles. 

Em relação aos códigos, eu pus um para cada Prelúdio:
![image](https://f.cloud.github.com/assets/4681458/1366418/b0cb4da8-38cf-11e3-9efe-675b2b9da4b1.png)

No caso dos Traits, eu coloquei um código para cada grupo de Traits (que estão agrupados por tonalidade):
![image](https://f.cloud.github.com/assets/4681458/1366426/2511520c-38d0-11e3-9538-e15a8974e432.png)

@msampaio, você vê algum problema nessa maneira como eu identifiquei os Traits? Ao que me parece até agora cada Trait é independente, mas tenho que ler o texto para confirmar isso.

**Comment by daniloabrahao** [comment]
Na tradução do Hotteterre, encontrei o seguinte sobre os Traits:

"Dei o nome de ´traits´(1) aos fragmentos que serão encontrados neste capítulo; a minha intenção foi caracterizá-los ao gosto dos caprichos que são produzidos quando se faz, por assim dizer, apenas brincar sobre um instrumento musical. Como são apenas PEDAÇOS DESTACADOS, pode-se começá-lo por outras cordas(2) que não sejam aquelas do tom."

OBS: Acho importante levar em consideração que esses Prelúdios e Traits eram possíveis motivos de improvisação.

(1) "O temo trait pode ser traduzido como traço. O ´Dictionnaire de L'Académie Frençaise de 1718´ expressa uma condição de ´modelos´, ´pontos´ de um discurso."

(2) "o temo ´cordas´é definido pelo ´Dictionnaire Portatid des beaux-arts´como notas continas na extensão de uma oitava."

**Comment by robattolucas** [comment]
Exato!

Estamos tratando aqui com algo semelhantes aos "padrões" (patterns) usados
para aprender a improvisar.

Exatamente por serem padrões reconhecidos como "importantes" por alguém da
época, teremos "matéria prima" (em termos de contornos)  para poder
comparar com "obras completas", obras escritas.

**Comment by msampaio** [comment]
@daniloabrahao, eu acho que os _traits_ estão subdivididos em movimentos. Por exemplo, neste O119, há 3 (ou 4) fragmentos. Para podermos isolar esse padrões, como @robattolucas propôs no comentário anterior, é preciso diferenciar o padrão do trecho no qual o padrão é usado. Caso concordem, recomendo usar O119M1, O119M2, ...

**Comment by msampaio** [comment]
@robattolucas, eu gostaria que você definisse as próximas obras para transcrever, depois do Hotteterre. Temos deixado a equipe de transcrição muito tempo ociosa. Isso pode resultar em sobrecarga de trabalho na segunda metade da pesquisa. Meu objetivo é manter uma continuidade de tarefas para essa equipe até concluirmos as transcrições. Podemos dividir a tarefa de anotação das subdivisões do pdf entre @daniloabrahao e Marina.

**Comment by robattolucas** [comment]
Ok. Sugiro então que a equipe de transcrição elabore uma tabela preliminar
com tudo que encontrarem para flauta solo, peças e métodos. Só isto já vai
dar bastante trabalho. Com esta lista podemos então estabelecer uma ordem
de transcrição.

Em 20 de outubro de 2013 08:39, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

**Comment by msampaio** [comment]
Ótimo, @robattolucas. Vou delegar essa tarefa a @MarinaMonroy.

**Comment by msampaio** [comment]
@robattolucas e @daniloabrahao, já temos uma lista preliminar com 21 obras para transcrever (vide arquivo IMSLP-FlautaSolo.txt, em Produção). Se possível, vamos começar por essas obras.

**Comment by robattolucas** [comment]
Ok. Vamos enfrentar primeiramente as obras de concerto (menos
problemáticas} ou os métodos?

Em 4 de novembro de 2013 16:17, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

**Comment by daniloabrahao** [comment]
Acho que talvez seja melhor resolver os problemas maiores antes, não?

**Comment by msampaio** [comment]
@daniloabrahao e @robattolucas, sugiro alternarmos as categorias das obras. Precisamos resolver os problemas tanto quanto ter volume de dados para avançar na área de Computação, Composição e Estatística.

**Comment by robattolucas** [comment]
Concordo. Alternar então. So next...

Em 4 de novembro de 2013 17:11, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

**Comment by daniloabrahao** [comment]
@robattolucas, quais edições vamos usar para a Partita de JS Bach e a Sonata em La menor de CPE Bach?

**Comment by robattolucas** [comment]
Para evitar trabalho, vamos adotar:

J.S. Bach - Partita BWV 1013 - Bärenreiter (H.P. Schmitz) -  edição já
consagrada (e um tanto tradicional)

C.P.E. Bach - Sonata Lá menor WK 132 (H562)- Uma cópia digitalizada do
manuscrito Gieddes, ou o próprio manuscrito, ou a 1 edição (1762) - todos
são praticamente idênticos e de fácil leitura (claro que a cópia digital é
mais fácil ainda) pode decidir entre estas.

Todas estas fontes estão disponíveis no  dvd com o repertório da classe de
flauta. Talvez a 1a edição do C.P.E., ainda não esteja lá, mas eu o tenho
em pdf.

2013/11/8 daniloabrahao notifications@github.com

**Comment by msampaio** [comment]
@daniloabrahao, coloque essas fontes indicadas por Lucas no Copy. Lembre-se de usar nosso código de identificação.

**Comment by daniloabrahao** [comment]
Ok! Vou fazer isso em breve!

**Comment by daniloabrahao** [comment]
Os arquivos já se encontram na pasta `Fontes>Processadas`. Dei o seguinte nome aos arquivos:

`EF00002-JSBach - Partita for Solo Flute`
`EF00003-CPEBach - Sonata in Aminor for Solo Flute`

Ambos com suas respectivas cópias anotadas.

**Comment by daniloabrahao** [comment]
@msampaio, pensei em fazer uma cópia da lista que Marina fez e ir marcando as fontes já transcritas, para que não fique faltando nada. O que você acha?

**Comment by msampaio** [comment]
Bom trabalho, @daniloabrahao. Deixarei esta tarefa aberta por enquanto, até termos um volume maior de fontes para transcrever
@ZeRodriguez, assim que concluirmos o Hotteterre podemos seguir com as fontes indicadas aqui. Pode seguir o fluxo normal de trabalho: atribuir uma tarefa a você mesmo, para delegar as transcrições para os demais, em seguida, atribuir as tarefas de cada um.

**Comment by msampaio** [comment]
@daniloabrahao, sobre a lista de @MarinaMonroy, boa ideia. Basta inserir algum símbolo direto na lista dela para indicar o que já foi transcrito.

**Comment by daniloabrahao** [comment]
Beleza. Os nomes dos arquivos estão corretos? Os `0002` e `0003` eu criei porque não são provenientes do IMSLP. Como no caso do Telemann.

**Comment by msampaio** [comment]
@daniloabrahao, veja no guia do código de identificação ;-)

**Comment by msampaio** [comment]
@robattolucas, precisamos de mais obras para transcrição. Seria bom decidir pelo menos as próximas 10 obras. A equipe já concluiu a última transcrição de CPE e JS Bach. Podemos usar a lista de @MarinaMonroy para escolher.

**Comment by msampaio** [comment]
@robattolucas e @MarinaMonroy, se vocês concordarem, podemos usar transcrever logo as obras abaixo. Caso concordem, @ZeRodriguez já pode começar a delegar as tarefas.
-   Ausführlicher und gründlicher Unterricht die Flöte zu spielen (Tromlitz, Johann George)
-   The Compleat Country Dancing-Master (Walsh, John)
-   24 Country Dances for the Year 1803 (Various)
-   Elegant Extracts for the Flute or Violin (Various)
-   Fantasies and Preludes for Flute (Quantz, Johann Joachim)
-   24 Favorite Country Dances, Hornpipes and Reels (Various)
-   8 Flute Capriccios (Quantz, Johann Joachim)
-   6 Flute Partitas (Tromlitz, Johann George)
-   The Flute Preceptor, Op.6 (Wragg, Jacob)
-   Flute Sonata in A minor (Kotecki, Andrew)
-   6 Grande solos, Op.1 (Berbiguier, Tranquille)
-   25 grandes études, Op.13 (Hugot, Antoine)

**Comment by MarinaMonroy** [comment]
@msampaio eu acredito que seja melhor deixar o Berbiguier para depois. Melhor fazer ao invés dele o 
• Méthode pour apprendre à jouër la flûtte (Corrette, Michel)

**Comment by msampaio** [comment]
Pode ser, @MarinaMonroy. Por hora, enquanto você se acostuma com o trabalho, recomendo selecionar composições originais ao invés de métodos.

**Comment by MarinaMonroy** [comment]
@msampaio, então dessas obras que você sugeriu juntamente com o Corrette é melhor deixar o Tromlitz para o final desse bloco de transcrições, pois se tratam ambos de métodos. O Berbiguier melhor deixar para a próxima etapa por questões de período (ainda não resolvi quanto as obras dele em específico).

Tem uma nova lista no Copy com mais algumas novas obras que usaremos intitulada IMSLP-ObrasDeInteresse com apenas obras relevantes para facilitar a visualização (devo colocar um sinalizador para as obras da lista já transcritas?). Algumas delas apenas partes nos interessam, mas a medida em que formos transcrevê-las eu digo quais são essas partes. Vou dar uma olhada mais específica nas obras desse bloco atual. 

@robattolucas fica bom assim?

**Comment by msampaio** [comment]
@MarinaMonroy, eu escolhi as obras aleatoriamente, entre as que você marcou com +.
Já existe um arquivo IMSLP-FlautaSolo. É possível juntar com esse arquivo que você criou com obras de interesse?

**Comment by MarinaMonroy** [comment]
Sim @msampaio é possível. No caso manterei apenas o arquivo IMSLP-FlautaSolo (o original) mudando a forma de organização dele por blocos (interesse ou não)  ao invés de ordem alfabética, acho que já fica legal desse jeito.

**Comment by robattolucas** [comment]
Acho também que devemos deixar os metodos para depois (tromlitz, etc)
efocar nas peças autorais e começar a explorar as coleções anônimas.
Em 03/12/2013 19:27, "MarinaMonroy" notifications@github.com escreveu:

**Comment by msampaio** [comment]
Ótimo. @MarinaMonroy, preciso de uma lista de 10 obras para transcrever. Não precisa aguardar ter as 10 para divulgar aqui, pois precisamos delegar as tarefas para a equipe.
@ZeRodriguez: após @MarinaMonroy divulgar as obras aqui, por favor delegue para ela a tarefa de anotar os arquivos PDF das fontes.

**Comment by ZeRodriguez** [comment]
Certo.

**Comment by MarinaMonroy** [comment]
@ZeRodriguez pode delegar as tarefas para 

24 Country Dances for the Year 1803 (Various)
Elegant Extracts for the Flute or Violin (Various)
204 Favourite Country Dances (Various)
24 Favorite Country Dances, Hornpipes and Reels (Various)
25 grandes études, Op.13 (Hugot, Antoine)
A Select Collection of Airs, Jigs, Marches and Reels (Various)
A Selection of Scotch, English, Irish and Foreign Airs (Aird, James)
6 Solo Flute Sonatas: Idea dell'Articolare (Moldenit, Joachim)
12 Variations and Solos for Flute, Op.10b (Kuhlau, Friedrich)
Vocal Music, or the Songster's Companion (Various)

**Comment by msampaio** [comment]
Bom trabalho, @MarinaMonroy. Antes de @ZeRodriguez delegar as tarefas ha tres tarefas:
1. escolher a fonte de cada uma dessas obras
2. baixar o pdf da fonte escolhida na pasta Fontes, no Copy.
3. Anotar o pdf indicando o codigo de cada obra e ou movimento.

Para a tarefa 1, recomendo combinar com @robattolucas. Para a tarefa 3 recomendo olhar os arquivos indicados como 'anotados', na pasta Fontes.
Se tiver qualquer duvida basta perguntar

**Comment by MarinaMonroy** [comment]
@msampaio @robattolucas, dessas obras indicadas algumas são coletâneas de músicas folclóricas provavelmente compostas até antes do período, porém tomei como base o ano de publicação para validá-las (digam-me se agi corretamente).
As fontes delas não são variadas, mas sim em geral apenas um arquivo do imslp. Estou iniciando o trabalho com elas. Assim sendo, a definição de fontes deve ser feita com as obras mais tradicionais  (Hugot, Moldenit e Kuhlau). Lucas, por favor, indique o que devo seguir nelas.

**Comment by MarinaMonroy** [comment]
Já fiz os passos 1 e 2 de:

24 Country Dances for the Year 1803 (Various)
204 Favourite Country Dances (Various)
24 Favorite Country Dances, Hornpipes and Reels (Various)
A Select Collection of Airs, Jigs, Marches and Reels (Various)
A Selection of Scotch, English, Irish and Foreign Airs (Aird, James)

**Comment by msampaio** [comment]
@MarinaMonroy, alterei a atribuição dessa tarefa para você.
