### ISSUE TITLE
Escrever resenha de Camilleri - Computational Musicology...

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#97]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa é escrever uma resenha do artigo abaixo.
Camilleri, Lelio. 1988. “Computational Musicology in Italy.” Leonardo 21 (4): 454–456.

**Comment by SimeiFerreira** [comment]
Tarefa concluída.
