### ISSUE TITLE
Escrever resenha de Kugel - Beyond Computational Musicology

### ISSUE THREAD

**Issue by msampaio** [msampaio/flauta-solo#98]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa é escrever uma resenha do artigo abaixo.
Kugel, Peter. 1992. “Beyond Computational Musicology.” In Understanding Music with AI, edited by Mira Balaban, Kermal Ebcio\uglu, and Otto Laske, 30–48. Cambridge, MA, USA: MIT Press.

**Comment by SimeiFerreira** [comment]
@msampaio, precisarei refazer a leitura do referido texto porque ainda não consegui compreender com exatidão o sentido do mesmo. Eu ainda não sou fluente em inglês, então isso também dificulta um pouco a compreensão. Hoje farei a leitura novamente e se conseguir captar melhor a mensagem, faço a resenha.

**Comment by msampaio** [comment]
@SimeiFerreira, caso tenha alguma dúvida basta perguntar aqui.

**Comment by SimeiFerreira** [comment]
@msampaio, esse livro me remete exatamente à conversa que tive com @AlissonGSilva sobre os seus estudos em PD. Muito interessante! Estou me valendo do google translator para tirar as dúvidas com algumas expressões em inglês que eu ainda não conhecia e adiantando a resenha. Se você quiser já passar alguma outra tarefa para a próxima terça, pode passar.

**Comment by SimeiFerreira** [comment]
Tarefa concluída!
