### ISSUE TITLE
Digitalizar capítulos 2 e 6 do livro Melodic Similary

### ISSUE THREAD

**Issue by ZeRodriguez** [msampaio/flauta-solo#99]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [manual de procedimentos](http://genosmus.com/pesquisa/flauta-solo/manual/)
- A [página da pesquisa](http://genosmus.com/pesquisa/flauta-solo/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas
- Escanear capítulos 2 e 6 do livro "Melodic Similary: Concepts,Procedures, and Applications Computing in Musicology 11" de Walter B.Hewlett e Eleanor Selfridge-Field

**Comment by ZeRodriguez** [comment]
@AlissonGSilva, qual o estado da tarefa?

**Comment by msampaio** [comment]
@AlissonGSilva, qual o estado da tarefa?

**Comment by AlissonGSilva** [comment]
Concluída! Já inseri no Mendeley também.
